dotnet/diagnostics

eng/Build-Native.cmd
eng/build-native.sh
eng/build.yml
eng/common/CIBuild.cmd
eng/common/build.ps1
eng/common/build.sh
eng/common/cibuild.sh
eng/common/is-vsts.ps1
eng/common/is-vsts.sh
eng/common/templates/phases/base.yml
eng/common/templates/steps/telemetry.yml
src/Directory.Build.targets

Update common eng scripts and files. Add missing is-vsts.* ones.

Fix internal yaml build.

---

README.md
eng/Build-Native.cmd
eng/Build.cmd
eng/build-native.sh
eng/build.sh
eng/install-test-runtimes.ps1
eng/install-test-runtimes.sh
src/Microsoft.Diagnostic.TestHelpers/TestConfiguration.cs
src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt

Add "daily-test" option to scripts/config.

Add downloading and testing the latest master runtime.

---

src/SOS/CMakeLists.txt
src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
src/SOS/SOS.UnitTests/SOSRunner.cs
src/SOS/runcommand/CMakeLists.txt
src/SOS/runcommand/runcommand.cpp

Add cdb extensions that prints a reliable prompt.

---

documentation/diagnostics-planing.md

This is my larger planning doc and it makes sense to put it there.

Add planning document

---

src/SOS/SOS.UnitTests/Scripts/GCTests.script
src/SOS/Strike/strike.cpp
src/SOS/Strike/util.cpp
src/inc/MSCOREE.IDL
src/inc/cor.h
src/inc/cordebug.idl
src/inc/corhdr.h
src/inc/dacprivate.h
src/inc/switches.h

Merge all the recent fixes and changes from the coreclr SOS. This also allows the tests to pass on the 3.0 runtime/master branch.

Update from coreclr SOS.

---

src/Tools/README.md

Looks like the README got left off Andrew's original PR

Add README for diagnostics tools

---

documentation/design-docs/dotnet-tools.md

grabbed a few comments from existing threads and stuck them
in a doc in the repo so we can iterate on it.

starting dotnet diag tools design

---

.vsts-dotnet.yml
eng/Build-Native.cmd
eng/CreateVersionFile.csproj
eng/GalleryManifest.xml
eng/Versions.props
eng/create-gallery-zip.ps1
src/SOS/Strike/hostcoreclr.cpp
src/SOS/Strike/sos_unixexports.src
src/SOS/Strike/sosdocs.txt
src/SOS/Strike/sosdocsunix.txt
src/SOS/Strike/strike.cpp
src/SOS/lldbplugin/inc/lldbservices.h
src/SOS/lldbplugin/services.cpp
src/SOS/lldbplugin/services.h
src/SOS/lldbplugin/soscommand.cpp

Update help docs.
Enable FinalizeQueue command on xplat

Fix extension gallery zip layout

---

documentation/design-docs/dotnet-tools.md

@dotnet/dotnet-diag @shirhatti @davidfowl @vancem @KathleenDollard @mikem8361 @jorive @sywhang 
I think this is a reasonable starting point for a design and I would appreciate getting your feedback!
Thanks : )

Strawman for CLI diagnostic tools design

---

src/SOS/Strike/strike.cpp

Port https://github.com/dotnet/coreclr/pull/22913 to dotnet/diagnostics
cc: @mikem8361

Fix DumpAsync to understand ContinuationWrapper

---

src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/DiagnosticMessageType.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/MessageHeader.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/Provider.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/SessionConfiguration.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Extensions.cs
src/Tools/dotnet-trace/CommandLine/Commands/PortsCommandHandler.cs
src/Tools/dotnet-trace/CommandLine/Commands/ProvidersCommandHandler.cs
src/Tools/dotnet-trace/CommandLine/Commands/StartCommandHandler.cs
src/Tools/dotnet-trace/CommandLine/Commands/StopCommandHandler.cs
src/Tools/dotnet-trace/CommandLine/Commands/StreamCommand.cs

I missed this stashed changes before I merged.

[dotnet-trace] Update namespaces based on previous PR feedback.

---

documentation/design-docs/dotnet-tools.md
documentation/dotnet-dump-instructions.md
documentation/lldb/osx-instructions.md
eng/Versions.props

Reconcile dotnet-dump spec/implementation. Issue #126.

Misc doc and version updates for preview5

---

src/SOS/Strike/sos.cpp
src/SOS/Strike/sos.h
src/SOS/lldbplugin/services.cpp
src/SOS/lldbplugin/setsostidcommand.cpp

Integer Conversion Issues from GCC
From PR https://github.com/dotnet/coreclr/pull/23934 in coreclr.

Add a destructor for sos::GCHeap

---

documentation/design-docs/dotnet-tools.md
documentation/dotnet-trace-instructions.md
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
src/Tools/dotnet-trace/TraceFileFormatConverter.cs

* adds format option
* incorporates @adamsitnik's code from #114 
* adds extensible infrastructure for additional formats should we decide to add more later.
CC - @jorive @tommcdon @adamsitnik @sywhang

Speedscope format

---

documentation/lldb/centos7/build-install-lldb.sh
documentation/lldb/fedora24/build-install-lldb.sh
documentation/lldb/linux-instructions.md
documentation/lldb/opensuse/build-install-lldb.sh

For CentOS 7, Fedora 24 and OpenSUSE.

Fix lldb build instructions and scripts.

---

documentation/design-docs/dotnet-tools.md
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
src/Tools/dotnet-trace/CommandLine/Commands/ConvertCommand.cs
src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
src/Tools/dotnet-trace/Program.cs
src/Tools/dotnet-trace/TraceFileFormatConverter.cs

* make default format for all platforms 'netperf'
* update spec to refelct impl
#180

Add Convert command

---

documentation/dotnet-dump-instructions.md
documentation/dotnet-trace-instructions.md
documentation/installing-sos-instructions.md
documentation/installing-sos-windows-instructions.md

Update tool installation docs to 1.0.3-preview5.19228.1

---

src/Tools/dotnet-counters/Program.cs

Merging #218 to release/3.0 branch.
cc @mikem8361

Fixing list command (#218)

---

src/Tools/dotnet-counters/ConsoleWriter.cs
src/Tools/dotnet-counters/CounterProvider.cs

This is port of #222 to release/3.0.

Fix issue with dotnet-counters not being able to target user-defined EventSource

---

documentation/dotnet-dump-instructions.md
documentation/dotnet-trace-instructions.md
documentation/installing-sos-instructions.md
documentation/installing-sos-windows-instructions.md

Add Release notes for dotnet-dump.
Remove --add-source in installation instructions.

Preview5 doc update.

---

documentation/dotnet-dump-instructions.md
documentation/dotnet-trace-instructions.md
documentation/installing-sos-instructions.md
documentation/installing-sos-windows-instructions.md

Add Release notes for dotnet-dump.
Remove --add-source in installation instructions.

Preview5 doc update. (#225)

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Ignore any provider specified via --profile option if they are already specified with --providers option

---

README.md
documentation/building/windows-instructions.md
documentation/dotnet-dump-instructions.md
documentation/dotnet-trace-instructions.md
documentation/installing-sos-instructions.md
documentation/installing-sos-windows-instructions.md

Update the tools version to 1.0.3-preview5.19251.2.

Update docs for preview 5.

---

README.md
documentation/design-docs/dotnet-tools.md
src/Tools/dotnet-counters/README.md

Updating doc for dotnet-counters.

Dotnet counters doc

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Terminate dotnet-trace when the runtime closes the eventpipe

---

src/Tools/dotnet-counters/Program.cs

Fixes https://github.com/dotnet/diagnostics/issues/233

[dotnet-counters] Make refresh-interval optional

---

src/Tools/dotnet-counters/CounterMonitor.cs

Make dotnet-counters exit gracefully on runtime shutdown

---

src/Tools/dotnet-counters/CounterMonitor.cs

Filter event counter payloads using CounterType payload

---

documentation/tutorial/README.md
documentation/tutorial/diagscenario.cs
documentation/tutorial/hung_app.md
documentation/tutorial/src/uniquestacks/UniqueStack.cs

Added a new hang (/deadlock) scenario

Added new hang scenario

---

src/Tools/dotnet-counters/Program.cs

Add list-processes command to dotnet-counters

---

src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticHelpers.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/DiagnosticMessageType.cs

This is the diagnostics change to work with https://github.com/dotnet/coreclr/pull/24670

Add profiler attach message

---

src/SOS/Strike/strike.cpp
src/SOS/Strike/util.cpp
src/SOS/Strike/util.h

Ports https://github.com/dotnet/coreclr/pull/24775
cc: @noahfalk, @mikem8361, @patrickcarnahan

Two changes to !dumpasync

---

src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Do not swallow exception and stuck in case we have an exception thrown during tracing

---

documentation/design-docs/ipc-protocol.md

* Adds profiler attach docs
* Adds create dump docs
* updates spec to use HRESULTS for response messages
CC - @noahfalk @tommcdon @jorive 
resolves #284 
resolves #278 
resolves #279

Ipc spec update

---

src/SOS/Strike/strike.cpp

The -wi feature added recently walks every item on the heap looking for thread pool queues.  It currently does this by comparing object names, but it's much faster to compare module and type def.  On my machine on an ~1GB dump, this improved execution time ~20x, from 2:15 to 0:07.
cc: @mikem8361, @noahfalk, @PatrickCarnahan

Improve perf of `!threadpool -wi`

---

src/Tools/dotnet-counters/ConsoleWriter.cs
src/Tools/dotnet-counters/CounterMonitor.cs

Offer visual cues for monitor status

---

src/Tools/dotnet-counters/ConsoleWriter.cs
src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-counters/KnownData.cs

Add P6 runtime counters to the list of known counters. 
Also contains some bug fixes on ConsoleWriter.

Add new counters to list

---

src/Tools/dotnet-counters/Program.cs
src/Tools/dotnet-trace/CommandLine/Commands/ListProcessesCommandHandler.cs

Do not print elevated processes' FileName

---

eng/CreateVersionFile.csproj
eng/GalleryManifest.xml
eng/create-gallery-zip.ps1

The arm directory, etc. needs to be "arm32" for it to work.

Fix extension gallery arm support

---

src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs

related to dotnet/coreclr#25031
resolves dotnet/coreclr#24859

Change default transport name to align with spec

---

src/SOS/Strike/util.cpp

Issue https://github.com/dotnet/diagnostics/issues/350

Fix UNKNOWN types in dumpheap -stat

---

documentation/design-docs/ipc-protocol.md
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/SessionConfiguration.cs
src/Microsoft.Diagnostics.Tools.RuntimeClient/Extensions.cs
src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Along with dotnet/coreclr#25363
resolves dotnet/coreclr#25275

Remove OutputPath from EventPipe Collect command

---

src/Tools/dotnet-counters/CounterMonitor.cs

Resolve issue https://github.com/dotnet/diagnostics/issues/228

Add Ctrl-C handler for dotnet-counters

---

eng/Versions.props
src/SOS/Strike/sos.def
src/SOS/Strike/sos_stacktrace.h
src/SOS/Strike/strike.cpp

Instead of reading "gCurrentThreadInfo.m_pThread" in the runtime.

Add _EFN_GetManagedThread for !analyze

---

src/Tools/dotnet-counters/CounterMonitor.cs

Improves https://github.com/dotnet/diagnostics/pull/364
CC @sywhang

dotnet-monitor: Use CommandHandler CancellationToken for SIGINT detection

---

src/Tools/dotnet-counters/ConsoleWriter.cs
src/Tools/dotnet-counters/KnownData.cs

Also cleaned up some stuff from #379.

Fix issue 387

---

global.json

My latest PR broke building locally.

Rollback arcade version update

---

src/SOS/Strike/strike.cpp

My goal is to make SOS output corresponding IL interleaved with the disassembly. 
This idea came up when I was stuck trying to debug a test case written in IL. For long IL method, trying to correlate assembly instruction with IL is manual, tedious and error-prone, that's why I started this work.
This can be done without changing the runtime - we need:
With all these done we should be able to come up the disassembly with IL interleaved.
Help wanted and welcome.
@dotnet/dotnet-diag

!u -il prototype (Part 1)

---

src/Tools/dotnet-counters/KnownData.cs

These shipped with 3.0 preview 7. Somewhat late to the game but better than nothing :-)

Add ASP.NET Counter to known list of counters

---

src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-counters/CounterPayload.cs

Fix IncrementingCounter payload generation

---

src/SOS/Strike/strike.cpp

Fix memory leak

---

src/Tools/dotnet-counters/CounterMonitor.cs

Backport #492 to release/3.0. 
/cc @mikem8361

[3.0 port] Fix a timeout exception causing unhandled exception crash

---

src/SOS/Strike/disasm.h
src/SOS/Strike/disasmARM.cpp
src/SOS/Strike/disasmARM64.cpp
src/SOS/Strike/disasmX86.cpp
src/SOS/Strike/exts.h
src/SOS/Strike/sildasm.cpp
src/SOS/Strike/sildasm.h
src/SOS/Strike/strike.cpp
src/SOS/Strike/util.h

This change is an attempt to fix #452 but at present the changes done so far have been refactoring to clean up the code before the final implementation can be made. Since, the changes are a lot more than I originally anticipated and as suggested by @cshung via offline conversation I am submitting pull request (although not complete) for build and test validation.

Dev il with disassem

---

src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Fix the error message when not a valid process ID is specified

---

documentation/dotnet-counters-instructions.md

Change `--refreshInterval` to `--refresh-interval`. 
Fix #520

Fix dotnet-counters documentation

---

documentation/design-docs/dotnet-tools.md
documentation/dotnet-counters-instructions.md
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
src/Tools/Common/Commands/ListProcesses.cs
src/Tools/Common/Commands/ProcessStatus.cs
src/Tools/dotnet-counters/Program.cs
src/Tools/dotnet-counters/dotnet-counters.csproj
src/Tools/dotnet-dump/Program.cs
src/Tools/dotnet-dump/dotnet-dump.csproj
src/Tools/dotnet-trace/CommandLine/Commands/ListProcessesCommandHandler.cs
src/Tools/dotnet-trace/dotnet-trace.csproj

Also renaming it to "ps" (see #527).

Refactor out list-processes command handler and add it to dotnet-dump

---

eng/Versions.props
src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt

Fix SOS failure in daily scheduled build.

Fix CI build failures (Microsoft.SymbolStore version missing)

---

documentation/design-docs/dotnet-tools.md
documentation/dotnet-counters-instructions.md
src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
src/Tools/Common/Commands/ProcessStatus.cs
src/Tools/dotnet-counters/Program.cs
src/Tools/dotnet-counters/dotnet-counters.csproj
src/Tools/dotnet-dump/Program.cs
src/Tools/dotnet-dump/dotnet-dump.csproj
src/Tools/dotnet-trace/CommandLine/Commands/ListProcessesCommandHandler.cs
src/Tools/dotnet-trace/dotnet-trace.csproj

… (#534)
* Refactor out ps command handler and add it to dotnet-dump
* More refactoring
* Some renaming
* update doc
* More docs update
* fix broken renamed file reference
* catch InvalidOperationException only

[3.0] Refactor out list-processes command handler and add it to dotnet-dump

---

documentation/design-docs/ipc-protocol.md

Fix incorrect description of CreateCoreDump command - diagnostics argument

---

eng/build.yml

Report test failures directly on the pipeline

Try using the test reporter to report tests

---

documentation/dotnet-trace-instructions.md

It looks like list-processes is no longer a command and instead it's ps.

list-processes -> ps

---

src/Tools/dotnet-counters/CounterPayload.cs
src/tests/dotnet-counters/CSVExporterTests.cs
src/tests/dotnet-counters/JSONExporterTests.cs
src/tests/dotnet-counters/TestHelpers.cs

Make dotnet-counters aware of DisplayUnits

---

eng/install-test-runtimes.ps1
eng/install-test-runtimes.sh
src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
src/SOS/Strike/sosdocs.txt
src/SOS/Strike/sosdocsunix.txt

Update help doc with some missing aliases.

Test 3.1 runtime, stop testing on 1.1 and 2.2

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Avoid exceptions when console is not available

---

src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs

Make MultiplePublishedProcessTest more stable

---

src/SOS/Strike/strike.cpp
src/Tools/dotnet-dump/Commands/ClrModulesCommand.cs
src/Tools/dotnet-dump/Commands/ModulesCommand.cs

Add version info to modules command.

Add verbose info to clrmodules command.

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

This makes dotnet-trace print that a rundown is in progress when the user presses ctrl-c or enter to stop a tracing session. This will only get printed if the user manually triggers the session to end. When the session ends on its own (i.e. the app being traced is terminated), it won't be displayed.
This fixes #717.

Display rundown in progress when stopping trace on dotnet-trace

---

src/SOS/Strike/gcroot.cpp

Parallel changes of microsoft/clrmd#510.

Add weak WinRT handle kind

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Do not clear the screen if returning error at launch

---

src/SOS/Strike/strike.cpp

dotnet-dump analyze dso

---

src/SOS/Strike/runtime.h
src/SOS/Strike/strike.cpp

Add runtime logic to disable Windows only code
when diagnosing Linux dumps on Windows

Add IsWindowsTarget()

---

src/Tools/Common/Commands/ProcessStatus.cs

Filter the tools' own PID out of ps command result

---

src/Tools/dotnet-counters/dotnet-counters.csproj

Remove dotnet-counters' unnecessary dependencies

---

src/tests/DacCompareNativeTypes/DacCompareNativeTypes.csproj
src/tests/DacCompareNativeTypes/DwarfParse.cs
src/tests/DacCompareNativeTypes/Member.cs
src/tests/DacCompareNativeTypes/PdbParser.cs
src/tests/DacCompareNativeTypes/Program.cs
src/tests/DacCompareNativeTypes/Readme.md
src/tests/DacCompareNativeTypes/Type.cs
src/tests/DacCompareNativeTypes/Whitespace.cs

This is the tool to manually test DAC layout. Related to #912

Initial commit DacCompareNativeTypes

---

diagnostics.yml
eng/build.sh
src/SOS/SOS.Package/SOS.Symbol.Package.csproj
src/sos-packaging.props

Enable Alpine Arm64 SOS builds

---

src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs

This is causing issues in container scenarios.

Remove https binding for now

---

src/Tools/dotnet-counters/Exporters/JSONExporter.cs
src/tests/dotnet-counters/JSONExporterTests.cs

Fix dotnet-counter's JSON exporter to produce a valid JSON format 

---

src/Tools/dotnet-counters/KnownData.cs

Update descriptions on some runtime counters

---

diagnostics.yml
eng/InstallRuntimes.proj
eng/Versions.props
src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
src/SOS/SOS.UnitTests/Debuggees/DesktopClrHost/CMakeLists.txt
src/SOS/SOS.UnitTests/Debuggees/DivZero/DivZero.csproj
src/SOS/SOS.UnitTests/Debuggees/GCWhere/GCWhere.csproj
src/SOS/SOS.UnitTests/Debuggees/LineNums/LineNums.csproj
src/SOS/SOS.UnitTests/Debuggees/NestedExceptionTest/NestedExceptionTest.csproj
src/SOS/SOS.UnitTests/Debuggees/Overflow/Overflow.csproj
src/SOS/SOS.UnitTests/Debuggees/ReflectionTest/ReflectionTest.csproj
src/SOS/SOS.UnitTests/Debuggees/SimpleThrow/SimpleThrow.csproj
src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestApp/SymbolTestApp.csproj
src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestDll/SymbolTestDll.csproj
src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/RandomUserLibrary/RandomUserLibrary.csproj
src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/TaskNestedException/TaskNestedException.csproj
src/SOS/SOS.UnitTests/Debuggees/WebApp3/WebApp3.csproj
src/SOS/lldbplugin.tests/TestDebuggee/TestDebuggee.csproj
src/tests/DacCompareNativeTypes/DacCompareNativeTypes.csproj
src/tests/EventPipeTracee/EventPipeTracee.csproj
src/tests/Grape/Grape.csproj
src/tests/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.UnitTests.csproj
src/tests/Tracee/Tracee.csproj
src/tests/benchmarks/benchmarks.csproj
src/tests/dotnet-counters/DotnetCounters.UnitTests.csproj
src/tests/dotnet-monitor/DotnetMonitor.UnitTests.csproj
src/tests/dotnet-trace/DotnetTrace.UnitTests.csproj
src/tests/eventpipe/EventPipe.UnitTests.csproj

Remove testing on Ubuntu 14.04 (end of life) to fix official builds.
Update test version to 2.1.17 and 3.1.3.
Removed testing on 3.0.x.
Updated netcoreapp3.0 to netcoreapp3.1 in all the test/debuggee projects

Various version updates

---

src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj

Generate NuGet packages for dotnet-monitor assemblies so that other teams can tentatively consume them.

Generate NuGets for dotnet-monitor core and rest server assemblies.

---

src/Tools/dotnet-counters/KnownData.cs

This adds the 3 new runtime counters to the `dotnet-counters list` command.

Update dotnet-counters list command with new counters

---

src/tests/dotnet-monitor/DiagnosticsMonitorTests.cs

Skipping test to unblock dependency merge

---

src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagControllerExtensions.cs
src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
src/Microsoft.Diagnostics.Monitoring/Logging/ScopeState.cs
src/Microsoft.Diagnostics.Monitoring/Logging/StreamingLogger.cs
src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
src/tests/dotnet-monitor/DiagnosticsMonitorTests.cs

Add text/event-stream support to /logs

---

src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs

Remove Exception keyword from gc-collect profile

---

src/Tools/dotnet-monitor/dotnet-monitor.csproj

Version dotnet-monitor independently.

Update dotnet-monitor to preview 2

---

eng/Versions.props
src/Microsoft.Diagnostics.Monitoring/DiagnosticsEventPipeProcessor.cs

Fixes #1206, #454 
The actual fix: https://github.com/microsoft/perfview/pull/1212
@josalem @noahfalk

update TraceEvent to latest version with SpeedScope|Chromium bug fixes

---

diagnostics.yml
eng/Versions.props
global.json
src/SOS/Strike/strike.cpp

Enabled Windows x86 build in public CI to catch these kind of problems.

Fix Windows x86 and arm build.

---

documentation/diagnostics-client-library-instructions.md
src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs

Add overload for starting EventPipe session with a single EventPipeProvider

---

src/Tools/dotnet-counters/KnownData.cs

Add System.Net.Http and Kestrel counters to list of well-known counters

---

src/Tools/dotnet-counters/CounterPayload.cs
src/tests/dotnet-counters/CSVExporterTests.cs
src/tests/dotnet-counters/JSONExporterTests.cs

Better formatting for incrementing counters

---

src/Tools/dotnet-counters/KnownData.cs

Add description of counter added by https://github.com/dotnet/runtime/pull/38851

Add GC heap fragmentation counter to known list of counters

---

src/Microsoft.Diagnostics.Monitoring/Metrics/MetricsStore.cs

Fix metrics snapshot to prevent modified collection exception.

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

#1257 changed the "while true read byte" loop to a simpler call to `Stream.CopyToAsync`.  It, however, neglected to handle the case where the returned task would complete before a user asked the trace to stop.  This change adds an async continuation that sets the MRE that handles exiting.  It also doesn't attempt to send the stop command if the copy task is already complete.
CC @tommcdon @mikem8361

Handle target process ending before user input

---

src/SOS/SOS.UnitTests/SOS.cs

Increase the LLDBPluginTests time to 10min

---

src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
src/tests/dotnet-monitor/EndpointInfoSourceTests.cs

Disable failing tests for darc update to come in

---

eng/Version.Details.xml
eng/Versions.props
src/SOS/SOS.Hosting/SOS.Hosting.csproj

- Add dependency information on CLRMD
- Add dependency on the SDK for testing

Add dependencies on CLRMD and SDK

---

src/Microsoft.Diagnostics.Repl/Command/CommandBase.cs
src/Tools/dotnet-dump/ExtensionCommands/ClrMDHelper.cs
src/Tools/dotnet-dump/ExtensionCommands/DumpConcurrentQueueCommand.cs
src/Tools/dotnet-dump/ExtensionCommands/TaskStateCommand.cs
src/Tools/dotnet-dump/ExtensionCommands/ThreadPoolItem.cs
src/Tools/dotnet-dump/ExtensionCommands/ThreadPoolQueueCommand.cs
src/Tools/dotnet-dump/ExtensionCommands/ThreadRoot.cs

- dump concurrent queue
- thread pool queue
Share TryParseAddress() between all commands to support hex address with 0x... or 0000... format

Add extended commands to dotnet-dump

---

src/SOS/Strike/eeheap.cpp

The pinned object heap follows the same alignment rules as the large object heap. As far as I can tell you will only run in to an issue when verifying objects, which only happens if you pass the -verify flag to !traverseheap. Other uses of GCHeapTraverse such as !dumpheap or !traverseheap without the -verify flag will see the free object and skip past it without trying to verify it.
This PR moves the POH traverse logic from the loop that does the normal segments to the LOH loop

use alignlarge for poh in gcheaptraverse

---

eng/Versions.props
src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
src/Microsoft.Diagnostics.Repl/Console/ConsoleProvider.cs
src/Microsoft.Diagnostics.Repl/Microsoft.Diagnostics.Repl.csproj
src/Tools/Common/Commands/ProcessStatus.cs
src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-counters/Program.cs
src/Tools/dotnet-counters/dotnet-counters.csproj
src/Tools/dotnet-dump/Analyzer.cs
src/Tools/dotnet-dump/Commands/HelpCommand.cs
src/Tools/dotnet-dump/Dumper.cs
src/Tools/dotnet-dump/Program.cs
src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
src/Tools/dotnet-gcdump/Program.cs
src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
src/Tools/dotnet-monitor/Program.cs
src/Tools/dotnet-monitor/dotnet-monitor.csproj
src/Tools/dotnet-sos/Program.cs
src/Tools/dotnet-sos/dotnet-sos.csproj
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
src/Tools/dotnet-trace/CommandLine/Commands/ConvertCommand.cs
src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
src/Tools/dotnet-trace/Program.cs
src/Tools/dotnet-trace/dotnet-trace.csproj

Workaround ordering problem in 2.0

Upgrade to System.CommandLine 2.0 (2.0.0-beta1.20427.1)

---

src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
src/SOS/Strike/strike.cpp

Linux arm32 clrstack -f issue: https://github.com/dotnet/diagnostics/issues/1235
Fix dotnet-dump command error message where it is printing the whole stack.

Fix some misc minor things

---

src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Clean up reversed server sockets upon exit

---

src/Tools/dotnet-counters/Exporters/CSVExporter.cs
src/Tools/dotnet-counters/Exporters/JSONExporter.cs

Fix race condition in Exporters for dotnet-counters

---

src/Microsoft.Diagnostics.Monitoring.RestServer/DiagnosticServices.cs

This fixes an issue where the command line for .NET Core 3.X runtimes was not reported in the REST API for dotnet-monitor. The issue is that the API was getting the command line information from the IEndpointInfo, which only has it available if the runtime instance connected to dotnet-monitor (which is only supported for .NET 5+). The fix is to change the ProcessInfo object to fallback back to reporting the command line from the EventProcessInfoPipeline invocation when the IEndpointInfo doesn't have command line information.

Fix issue where command line was not reported for .NET Core 3.X runtimes

---

documentation/design-docs/ipc-protocol.md

* Fix broken link
* Remove references to outdated environment variables and terms.

Update diagnostics IPC protocol doc

---

src/Tools/dotnet-counters/KnownData.cs

clarify CPU usage in dotnet-counters list command

---

src/Tools/dotnet-counters/KnownData.cs

Add more counters that were added in .NET 5 to dotnet-counters list.

Add more known counters to dotnet-counters list

---

src/Tools/dotnet-counters/dotnet-counters.csproj
src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
src/Tools/dotnet-stack/dotnet-stack.csproj
src/Tools/dotnet-trace/dotnet-trace.csproj

Update tool descriptions:
* .NET Core -> .NET as we rebranded since .NET 5.0
* Fix incorrect dotnet-gcdump descriptions
* Fix inconsistent casing in dotnet-stack

Update tool descriptions

---

documentation/FAQ.md
documentation/design-docs/dotnet-dump-extensibility.md
documentation/installing-sos-windows-instructions.md
documentation/lldb/linux-instructions.md
src/SOS/Strike/exts.h

Issues:
https://github.com/dotnet/diagnostics/issues/1491
https://github.com/dotnet/diagnostics/issues/1089

Misc doc updates

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

This should hopefully fix the CentOS issues identified in #2011

Address a race condition identified in CI

---

src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
src/Tools/dotnet-counters/CounterMonitor.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

Handle SIGINTs gracefully while waiting for client connection

---

src/SOS/Strike/eeheap.cpp
src/SOS/Strike/gcroot.cpp
src/SOS/Strike/util.h

Fixes https://github.com/dotnet/runtime/issues/52233

Fix verifyheap for objects larger than 4GB

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs

Make EventPipeSession stop on Dispose

---

eng/Versions.props
src/SOS/SOS.Extensions/CMakeLists.txt
src/SOS/SOS.Extensions/SOS.Extensions.csproj
src/SOS/SOS.Package/SOS.Package.csproj
src/SOS/Strike/symbols.cpp
src/sos-packaging.props

Fixes https://github.com/dotnet/diagnostics/issues/324
/cc: @tommcdon

Add Microsoft.DiaSymReader.Native for arm64

---

eng/build.sh
src/pal/src/locale/utf8.cpp

Fix issue https://github.com/dotnet/diagnostics/issues/2389

Fix build break on xcode 12

---

src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs

Fixes #2486 and xamarin/xamarin-macios#12366

Use absolute path for unix domain socket in listen mode

---

src/Tools/dotnet-counters/CounterMonitor.cs

Added code to work with input redirection in dotnet-counters, uncovered other issues.
Fixes #2329

altered dotnet-counters to work with inputRedirection #2329

---

src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessInfoTests.cs

Validate ProcessInfo is same (except entrypoint) before and after resume.

---

src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/AspNet/AspNetTrigger.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/AspNet/AspNetTriggerSettings.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/AspNet/GlobMatcher.cs
src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/AspNetTriggerUnitTests.cs
src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/GlobMatcherTests.cs

Load testing in Aks and local profiler testing did not show a lot of impact from Regex, but it's probably something we can optimize in the future.

Add glob support for asp.net triggers

---

src/SOS/Strike/strike.cpp

This is to align how `setclrpath` and `setsymbolserver -directory` commands' output appear in REPL/interactive mode.
Before:
```gdb
(lldb) setclrpath ../helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0
Set load path for DAC/DBI to '/home/helixbot/helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0'
(lldb) setsymbolserver -directory ../helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0
Added symbol directory path: ../helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0
```
After:
```gdb
(lldb) setclrpath ../helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0
Set load path for DAC/DBI to '/home/helixbot/helix_payload/System.Text.Json.Tests/shared/Microsoft.NETCore.App/7.0.0'
(lldb) …
```

Resolve relative path in setsymbolserver -directory

---

diagnostics.yml
eng/build.yml

Per https://github.com/dotnet/core-eng/issues/14276.

Switch to 1ES R&D pools on main

---

src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleService.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleServiceFromDataReader.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/TargetFromDataReader.cs
src/Microsoft.Diagnostics.DebugServices/MemoryServiceExtensions.cs
src/Microsoft.Diagnostics.ExtensionCommands/Host/ModulesCommand.cs
src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
src/SOS/SOS.UnitTests/SOS.cs
src/SOS/lldbplugin/services.cpp
src/SOS/lldbplugin/services.h

Fix crashreport test on MacOS
Add metadata mapping memory service for OSX

Enable dotnet-dump tests on OSX

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs

Add byte[] to SerializePayloadArgument

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs

Use non-infinite timeout for async connection.

---

src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs

dotnet-trace collect --show-child-io displays child process' IO only

---

documentation/design-docs/dotnet-tools.md

Created branch in my fork of diagnostics.
@shirhatti @brianrob

Adding dotnet-trace report (draft 2)

---

eng/prepare-release.yml

Update pool for prepare release step

---

THIRD-PARTY-NOTICES.TXT
src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestApp.sln
src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/TaskNestedException.sln
src/Tools/Common/Commands/ProcessStatus.cs
src/Tools/Common/ProcessNativeMethods/ProcessNativeMethods.cs
src/Tools/Common/WindowsProcessExtension/WindowsProcessExtension.cs
src/Tools/dotnet-counters/Program.cs
src/Tools/dotnet-counters/dotnet-counters.csproj
src/Tools/dotnet-dump/Program.cs
src/Tools/dotnet-dump/dotnet-dump.csproj
src/Tools/dotnet-gcdump/Program.cs
src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
src/Tools/dotnet-stack/Program.cs
src/Tools/dotnet-stack/dotnet-stack.csproj
src/Tools/dotnet-trace/Program.cs
src/Tools/dotnet-trace/dotnet-trace.csproj

Adding Commandline args to dotnet-tool ps

---

src/SOS/Strike/util.cpp
src/shared/inc/dacprivate.h

Companion to dotnet/runtime#66507

Add OSR to DacpTieredVersionData

---

src/Tools/Common/Commands/ProcessStatus.cs

Fixes #2946 
add the case where no supported managed processes were found

dotnet-tool ps case with no supported managed processes

---

src/dbgshim/pkg/Directory.Build.props

While other details are sorted out, mark the packages as not shipping.

Mark dbgshim as not shipping

---

documentation/lldb/linux-instructions.md

Mostly just delete distro versions that are not supported for any supported .NET version.

Update lldb instructions

---

src/Tools/dotnet-trace/CommandLine/PrintReportHelper.cs

Add case for when name does not match Regex. fixes #2994

Update tool to account for missing symbol

---

src/Tools/dotnet-stack/ReportCommand.cs

fixes #3030
Needs some local testing, but should fix the issue you saw @noahfalk.

Write temp files to tempdir

---

src/dbgshim/debugshim.cpp
src/dbgshim/pkg/Microsoft.Diagnostics.DbgShim.props
src/shared/pal/inc/rt/ntimage.h

This doesn't fix the dbgshim symbols not being published.

Fix dbgshim's OpenVirtualProcess on windows arm64

---

src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs

Issue: https://github.com/dotnet/diagnostics/issues/3392

Fix overflow exception in Microsoft.Diagnostics.Monitoring

---

src/Tools/dotnet-counters/KnownData.cs

Update the list of available networking counters

---

src/Tools/dotnet-dump/Dumper.cs

Related PR : https://github.com/dotnet/diagnostics/pull/3522

Change the return value to a non-zero in case of failure

---

eng/SourceBuildPrebuiltBaseline.xml
eng/Version.Details.xml
eng/Versions.props
eng/build.sh

Resolves https://github.com/dotnet/diagnostics/issues/3582
CC: @MichaelSimons @crummel

add souce-build pre-built detection

---

src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterFilter.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPipeline.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPipelineSettings.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterPipelineUnitTests.cs

Feedback for https://github.com/dotnet/diagnostics/pull/3587

PR for feature branch

---

src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPipelineSettings.cs
src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterTriggerTests.cs

Also fixing build/test failures from a call to `GetMetadata`.
FYI @wiktork

[SDM] Changes To MetricType

---

src/Microsoft.Diagnostics.ExtensionCommands/ClrMemoryPointer.cs
src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs

Fixes an issue introduced in https://github.com/dotnet/runtime/pull/67885.
.Net 7 will treat LoaderHeaps as ExplicitControlLoaderHeap, which is only true for the loader heaps used for the JIT.  Currently we only check for .Net 7, because I'm hoping we can put a fix in for .Net 8.
We don't have direct usage of these APIs in ClrMD, but since we now have to work around this behavior it'll be better to put this logic directly into ClrMD instead of having multiple copies of this workaround floating around.
Since I'm not doing ClrMD feature work right now, I'm directly working around this issue here.

maddress: Work around .Net 7 LoaderHeap traversal issue

---

eng/Version.Details.xml
eng/Versions.props
src/Microsoft.Diagnostics.ExtensionCommands/GCRootCommand.cs

Update ClrMD to apply proposed fix for stack/handle walking

Fix !gcroot issue

---

src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs

- Added a way to list all kinds of a specific memory type
- Added caching to NativeAddressHelper, as it was recalculating every run

Add -list to !sos maddress

---

src/SOS/SOS.Extensions/MemoryRegionServiceFromDebuggerServices.cs

Fix an IndexOutOfRangeException with !sos maddress.

Fix IndexOutOfRangeException

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/ProcessInfo.cs

Implement the ProcessInfo3 command as described in #3476
Corresponding runtime change: https://github.com/dotnet/runtime/pull/87707

ProcessInfo3 diagnostic command

---

eng/Versions.props
src/Microsoft.Diagnostics.DebugServices.Implementation/CrashInfoService.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/DataReader.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/Microsoft.Diagnostics.DebugServices.Implementation.csproj
src/Microsoft.Diagnostics.DebugServices.Implementation/SpecialDiagInfo.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/Target.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/TargetFromDataReader.cs
src/Microsoft.Diagnostics.DebugServices/ICrashInfoService.cs
src/Microsoft.Diagnostics.DebugServices/IManagedException.cs
src/Microsoft.Diagnostics.DebugServices/IRuntime.cs
src/Microsoft.Diagnostics.DebugServices/IStackFrame.cs
src/Microsoft.Diagnostics.DebugServices/IType.cs
src/Microsoft.Diagnostics.ExtensionCommands/CrashInfoCommand.cs
src/SOS/SOS.Extensions/DebuggerServices.cs
src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
src/SOS/SOS.Extensions/RemoteMemoryService.cs
src/SOS/SOS.Extensions/SOS.Extensions.csproj
src/SOS/SOS.Extensions/TargetFromFromDebuggerServices.cs
src/SOS/SOS.Hosting/RuntimeWrapper.cs
src/SOS/Strike/dbgengservices.cpp
src/SOS/Strike/dbgengservices.h
src/SOS/Strike/sos.def
src/SOS/Strike/strike.cpp
src/SOS/inc/debuggerservices.h
src/SOS/inc/specialdiaginfo.h
src/SOS/lldbplugin/services.cpp
src/SOS/lldbplugin/soscommand.cpp
src/SOS/lldbplugin/sosplugin.h

Reads the JSON crash info from the triage buffer in the NativeAOT runtime.
Adds a ICrashInfoService and SpecialDiagInfo helper class.

Add the "crashinfo" command for NativeAOT.

---

src/Microsoft.Diagnostics.DebugServices.Implementation/DataReader.cs
src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
src/tests/eventpipe/ContentionEvents.cs
src/tests/eventpipe/LoaderEvents.cs
src/tests/eventpipe/MethodEvents.cs
src/tests/eventpipe/ThreadPoolEvents.cs

Some test fixes to make them more reliable.

Use new ModuleInfo.TryCreateResourceRoot in DataReader impl

---

src/SOS/SOS.UnitTests/Scripts/OtherCommands.script

Addresses issue #https://github.com/dotnet/diagnostics/issues/3516

Re-enable dumpmt tests in OtherCommands.script

---

src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs

Fixes an issue reported by the GC team.
On windows, VirtualQuery information (bounds of allocated segments) is very accurate in dumps because we have an entire segment of the dump format which describes it.  On Linux, it seems like we smash together regions which came from two different calls of VirtualAlloc (well, the Linux equivalent).
So, only use a heuristic of attributing regions of allocated memory on Windows.  Additionally, we are 100% accurate in reporting every byte of memory that the GC allocates as of .Net 8.  We shouldn't be ever using this heuristic to attribute any memory to the GC.

!maddress misattributes memory to the GC

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcTransport.cs

This PR includes a speculative change for dsrouter connection string.  I'll will wait for @lateralusX to respond.

Provide better error messages for IPC connect failures

---

src/SOS/SOS.InstallHelper/InstallHelper.cs
src/SOS/SOS.InstallHelper/SOS.InstallHelper.csproj
src/SOS/SOS.Package/SOS.Package.csproj
src/SOS/SOS.Package/SOS.Symbol.Package.csproj

Change SOS installer to copy subdirectories

Fix some packaging issues

---

src/SOS/Strike/clrma.cpp
src/SOS/extensions/extensions.cpp
src/SOS/extensions/hostdesktop.cpp

Don't call ICLRRuntimeHost::Stop() on desktop hosting failures
Fix ICLRManagedAnalysis instance ref count

Fix a few Watson/!analyze issues

---

src/Tools/dotnet-trace/Extensions.cs
src/tests/dotnet-trace/ProfileProviderMerging.cs
src/tests/dotnet-trace/ProviderParsing.cs

Change provider defaults for dotnet-trace

---

global.json

ref: https://github.com/dotnet/arcade/pull/14485

Update SDK to P1 release

---

src/SOS/inc/symbolservice.h

/cc @GrabYourPitchforks @mikem8361

Fix incorrect return type.

---

src/shared/utilcode/sstring_com.cpp

Fix CONTRACT return type

---

diagnostics.yml
eng/Versions.props

Issue: https://github.com/dotnet/diagnostics/issues/3882

Add ubuntu 22.04 testing. Update 6,7 and 8 runtime versions

---

eng/native/configurecompiler.cmake

Reenable SDL requirements

---

eng/pipelines/prepare-release.yml
eng/release/Scripts/AcquireBuild.ps1

Use darc's MI support with WIF connection + Az Cli

Update usage of darc in release

---

eng/Version.Details.xml
eng/Versions.props
eng/common/cross/build-rootfs.sh
eng/common/cross/riscv64/sources.list.noble
eng/common/post-build/nuget-validation.ps1
eng/common/post-build/publish-using-darc.ps1
eng/common/tools.ps1
eng/common/tools.sh
eng/pipelines/prepare-release.yml
eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj
eng/release/Scripts/AcquireBuild.ps1
global.json
src/SOS/SOS.UnitTests/SOSRunner.cs
src/tests/eventpipe/ContentionEvents.cs
src/tests/eventpipe/CustomEvents.cs
src/tests/eventpipe/GCEvents.cs
src/tests/eventpipe/LoaderEvents.cs
src/tests/eventpipe/MethodEvents.cs
src/tests/eventpipe/ThreadPoolEvents.cs
src/tests/eventpipe/providers.cs

- [main] Update dependencies from dotnet/aspnetcore (#4736)
- Bump Azure.Identity from 1.11.3 to 1.11.4 in /eng/release/DiagnosticsReleaseTool (#4734)
- [main] Update dependencies from dotnet/aspnetcore (#4738)
- [main] Update dependencies from dotnet/aspnetcore (#4740)
- [main] Update dependencies from dotnet/aspnetcore (#4742)
- Fix race in setting results in SOS runner (#4745)
- Update usage of darc in release (#4744)
- [main] Update dependencies from dotnet/arcade (#4737)

Merge main into release

---

src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeProvider.cs
src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs
src/Microsoft.Diagnostics.DebugServices/IRuntimeProvider.cs
src/Microsoft.Diagnostics.DebugServices/IRuntimeService.cs
src/Microsoft.Diagnostics.DebugServices/RuntimeEnumerationFlags.cs
src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
src/SOS/SOS.Package/SOS.Symbol.Package.csproj
src/sos-packaging.props

Add runtime enumeration control to runtime service and providers

---

documentation/symbols/SSQP_Key_Conventions.md
src/Microsoft.FileFormats/StreamAddressSpace.cs
src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/KeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/MachOKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/PDBFileKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/PerfMapFileKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/PortablePDBFileKeyGenerator.cs
src/Microsoft.SymbolStore/KeyGenerators/SourceFileKeyGenerator.cs
src/Microsoft.SymbolStore/SymbolStoreFile.cs
src/Microsoft.SymbolStore/SymbolStoreKey.cs
src/tests/Microsoft.FileFormats.UnitTests/Microsoft.FileFormats.UnitTests.csproj
src/tests/Microsoft.SymbolStore.UnitTests/KeyGeneratorTests.cs
src/tests/Microsoft.SymbolStore.UnitTests/Microsoft.SymbolStore.UnitTests.csproj

Change debug asserts to release argument exceptions for better parameter validation

Add PDZ indexing to symbol store

---

src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
src/Tools/dotnet-trace/TraceFileFormatConverter.cs

Fixes https://github.com/dotnet/diagnostics/issues/4908

[Tools] Explicitly log new format file creation

---

debuggees.sln
src/SOS/SOS.UnitTests/Debuggees/DynamicMethod/DynamicMethod.csproj
src/SOS/SOS.UnitTests/Debuggees/DynamicMethod/Program.cs
src/SOS/SOS.UnitTests/SOS.cs
src/SOS/SOS.UnitTests/Scripts/DynamicMethod.script
src/SOS/Strike/strike.cpp

Fix dynamic methods "resolver" field name.

Fixes issue https://github.com/dotnet/diagnostics/issues/4850

---

src/Microsoft.Diagnostics.TestHelpers/AcquireDotNetTestStep.cs
src/Microsoft.SymbolStore/KeyGenerators/SourceFileKeyGenerator.cs
src/SOS/Strike/clrma/exception.cpp
src/SOS/Strike/clrma/thread.cpp

codeQL issues

---

documentation/FAQ.md

This work around can be applicable to all MacOS devices. @am11

SOS workarounds for MacOS

---

src/SOS/extensions/hostcoreclr.cpp

I forgot to remove hosting SOS on net 7.0 if my previous PR.

Remove hosting on net 7.0

---

src/SOS/Strike/crosscontext.h
src/SOS/Strike/disasmLOONGARCH64.cpp

Implement LOONGARCH64Machine:: Unassembly function to support disassembly.

[LoongArch64] Add disassembly support in disasmLOONGARCH64.cpp

---

src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs

Fixes #3631
Add support for creating a `DiagnosticClient` from a diagnostic port string. Currently we have to rely on `System.Reflection`, so it makes it hacky today to create our own advanced tooling on top of `DiagnosticClient`, while all the tooling developed in this repo are able to access internal APIs.

Add support for creating a DiagnosticClient from a diagnostic port

---

eng/Version.Details.xml
eng/Versions.props
eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.sln
src/SOS/Strike/util.cpp

- **Fix release tool parameter (#5337)**
- **Update thread statics format (#5341)**
- **Fix staging parameter path (#5342)**

Merge main into release/stable

---

src/SOS/SOS.UnitTests/Scripts/StackTraceFaultingExceptionFrame.script
src/SOS/SOS.UnitTests/Scripts/StackTraceSoftwareExceptionFrame.script

Regex brackets were not escaped and matched any of the interior characters

Fix cDAC SOS test scripts

---

src/SOS/SOS.UnitTests/SOS.cs
src/SOS/SOS.UnitTests/Scripts/ClrStackWithNumberOfFrames.script
src/SOS/SOS.UnitTests/Scripts/DivZero.script
src/SOS/Strike/sosdocs.txt
src/SOS/Strike/strike.cpp
src/SOS/Strike/util.cpp
src/SOS/Strike/util.h

Implement support to -c parameter on !ClrStack command
