- .vsts-dotnet.yml
- documentation/debugging-instructions.md
- eng/build-native.sh
- eng/build.yml
- eng/cibuild.sh
- eng/docker-cibuild.sh
- eng/docker-init.sh
- src/Microsoft.Diagnostic.TestHelpers/TestConfiguration.cs
- src/Microsoft.Diagnostic.TestHelpers/TestRunner.cs
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/lldbhelper.py
- src/SOS/Strike/gcroot.cpp
- src/SOS/Strike/sos.cpp
- src/SOS/lldbplugin/services.cpp
Fix some other problems in the internal builds.
Fixed problem in sos test runner that ignored sos commands failing.
Added a file or directory exists condition for configuration file entries.
Change the dump generation to use createdump for 2.1/2.0. Still uses gdb for 1.1.
Fixed ReadVirtualCache::Read problem on lldb that caused the tests to fail on OSX.  The lldb
services Read/WriteVirtual needed to properly return a partial read or write.
Fixed issue #35
> Test on more Linux distros.

- src/pal/src/thread/thread.cpp
Fix for https://github.com/dotnet/coreclr/issues/18486
- Lock release needs to be at least volatile
coreclr master PR: https://github.com/dotnet/coreclr/pull/19604
> Fix a PAL spin lock issue

- src/Tools/dotnet-collect/ConfigPathDetector.cs
This adds the ability to collect EventPipe traces via `--process-id` parameter on OSX. 
Addresses #128
> Add ConfigPath detection mechanism on OSX

- .vsts-dotnet.yml
- README.md
- documentation/design-docs/dotnet-tools.md
- documentation/installing-sos-instructions.md
- documentation/installing-sos-windows-instructions.md
- eng/Versions.props
- eng/build-native.sh
- eng/build.yml
- eng/cipack.cmd
- src/SOS/SOS.Hosting/AssemblyResolver.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.InstallHelper/InstallHelper.cs
- src/Tools/dotnet-collect/ConfigPathDetector.cs
- src/Tools/dotnet-dump/AnalyzeContext.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/ExitCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Dumper.Linux.cs
- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
- src/Tools/dotnet-dump/dotnet-dump.csproj
- src/Tools/dotnet-sos/Program.cs
- src/Tools/dotnet-sos/dotnet-sos.csproj
Bring dotnet-dump collect up to spec.
Issue #125
Spec changes:
Remove the --number and --interval-sec dotnet-dump collect options.
Change the dotnet-dump collect file naming to timestamp based.
Change the collect spew to match createdump's.
Lowercase all the dotnet-dump analyze commands to match sos on Linux/lldb.
Add some installing sos documentation.
Bring up dotnet-sos syntax up to spec.
Restrict the assembly resolver to just SOS.NETCore.
Fix some official build artifacts:
Break up "DropArtifacts" build variable into "DropPackages" and "DropBinaries".
Pushes all packages to dotnet-core blob feed.  # Optionally publish the packages MyGet feed
> Bring dotnet-sos and dotnet-dump up to spec

- eng/build-native.sh
So they work on the supported versions of macOS.
> Force lldb plugin/SOS to build with macOS 10.12 SDK

- src/Tools/dotnet-counters/CollectionConfiguration.cs
- src/Tools/dotnet-counters/ConfigPathDetector.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/CounterProvider.cs
- src/Tools/dotnet-counters/EventCollector.cs
- src/Tools/dotnet-counters/EventPipeCollector.cs
- src/Tools/dotnet-counters/KnownData.cs
- src/Tools/dotnet-counters/Program.cs
- src/Tools/dotnet-counters/StringParser.cs
- src/Tools/dotnet-counters/dotnet-counters.csproj
Adding dotnet-counters CLI tool. As of this PR, this implements
- CLI commands as documented here: https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/dotnet-tools.md
- Collecting a .netperf file that contains counters events
Once runtime can stream events through IPC, part of this needs to be rewritten to start monitoring. Also, the UI part that displays the counters need to be written as this isn't something that's supported now. 
Filed https://github.com/dotnet/diagnostics/issues/138 to track what needs to be done in the future.
> Add dotnet-counters 

- src/Tools/dotnet-counters/Program.cs
dotnet-counters was not using `UseDefaults()` that's provided by System.CommandLine. This allows the tool for misc. CLI things like spitting out help messages or erroring out when not all parameters are provided, etc. Mike suggested I change this, so here it is.
> Make dotnet-counters use UseDefaults() with System.CommandLine

- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
We shouldn't be calling `Bind()`, otherwise we get an exception for address already in use.
> Remove call to Bind() from EventPipeClient

- .gitignore
- src/Common.props
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/DiagnosticMessageType.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeSessionType.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/Provider.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/SessionConfiguration.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Extensions.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Microsoft.Diagnostics.Tools.RuntimeClient.csproj
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/dotnet-counters.csproj
- src/Tools/dotnet-trace/CommandLine/Commands/PortsCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ProvidersCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Commands/StartCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Commands/StopCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Commands/StreamCommand.cs
- src/Tools/dotnet-trace/build.sh
- src/Tools/dotnet-trace/dotnet-trace.csproj
- src/Tools/dotnet-trace/run.sh
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/Assert.cs
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/Program.cs
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/Workload.cs
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/eventpipetests.csproj
- Move common csproj properties to a common props file
- Add more tracing file extensions to .gitignore
- Update runtime client to enable streaming on non-Windows platforms.
- Added helper bash scripts
- Update RunTimeClient
- Updated `DiagnosticMessageType` private -> public
- Ignore `sessionId == 0` on the "Disable" command
- Added a `SessionLoggingType` to be added to the command protocol
- Removed `multi file sec` related functionality
- Ignore buffer size of zero
- Added some initial tests that need to be moved to CoreClr.
> [dotnet-trace] Minor updates to match recent CoreClr changes, error handling, and tests

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/dotnet-trace.csproj
Use the `\u001b[` family of ANSI escape codes to reset the console line.  Should work crossplat.
> Change ResetCurrentConsoleLine() to use explicit ANSI escape codes 

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ProfilesCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
- src/Tools/dotnet-trace/Extensions.cs
- Before, not passing `--profile` still required the `--providers` option. Now, a single Provider is required by the tool. The provider would come either from the `--profile` option or from the `--providers` option. **
- Move non-common options to the 'collect' file.
- Changed hardcoded keywords for already defined `enums`.
**Found the bug while testing the `--pack` option.
> [dotnet-trace] Small changes

- src/Tools/dotnet-trace/CommandLine/Commands/ProfilesCommandHandler.cs
This is the new mapping:
`--profile gc` -> [GCOnly](https://github.com/Microsoft/perfview/blob/28a1477d4d0b0316294b2942f90a787449e08a79/src/PerfView/CommandLineArgs.cs#L441)
`--profile gc-collect` -> [GCCollectOnly](https://github.com/Microsoft/perfview/blob/28a1477d4d0b0316294b2942f90a787449e08a79/src/PerfView/CommandLineArgs.cs#L461)
> Updating gc/gc-collect options to map PerfView flags.

- documentation/lldb/centos7/build-install-lldb.sh
Changed downloading binutils from sourceware.org to http://ftp.gnu.org/gnu/binutils.
> Fix the build-install-lldb.sh network failure.

- src/Tools/dotnet-trace/CommandLine/Commands/ProfilesCommandHandler.cs
Not ready on Non-Windows platform for **.NET 3.0 Preview5**. This is related to this bug fix: https://github.com/dotnet/coreclr/pull/24198, which will be included in **Preview6**.
The issue manifests when EventPipe is enabled without LTTng. In this case, GC events are disabled after the first GC because LTTng probes are disabled.
> Temporarily disable gc profiles.

- documentation/design-docs/dotnet-tools.md
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ListProcessesCommandHandler.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
- src/Tools/dotnet-trace/Program.cs
Related to the Preview5 release spec alignment here: https://github.com/dotnet/diagnostics/issues/180
> Renaming non-spec options on dotnet-trace

- src/Tools/dotnet-counters/CounterFilter.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/CounterProvider.cs
- src/Tools/dotnet-counters/KnownData.cs
- src/Tools/dotnet-counters/Program.cs
This adds the following:
- Filtering counters via specifying them on the command line like: `System.Runtime[cpu-usage,exception-count]`
- Changing some hard-coded descriptions of Runtime event counters
- Fixing broken alignment on list command.
I also found out that for some reason, EventCounter payloads don't have the fields that they should have, namely the `Series` and `CounterType` fields. It's unclear why those fields are missing, but that would require runtime investigation/change, so for the time being I'm reverting back some of the tool change that was trying to read those fields .
After this there will be another PR that specifically handles the 'p', 'r', 'q' commands on the spec.
> Bringing dotnet counters up to spec [part 1]

- src/Tools/dotnet-counters/ConsoleWriter.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
This adds a command handler to dotnet-counters that supports these commands as documented in the spec:
- `p` for pause
- `r` for resume
- `q` for quit
Please let me know if there is anything that doesn't match the spec as of this PR. 
I will be following up with a PR that modifies the documentation & creates a README for dotnet-counters.
> Bringing dotnet-counters up to spec [part 2]

- src/Tools/dotnet-counters/Program.cs
The spec for dotnet-counters say that we need to write the EventSource name for `list` command in dotnet-counters. 
Also, there was a debug print that went in accidentally... So I'm removing that.
> Fixing dotnet-counters list command

- src/Tools/dotnet-counters/ConsoleWriter.cs
- src/Tools/dotnet-counters/CounterProvider.cs
Addresses #221. 
Also, if the user-defined counter didn't specify any `DisplayName` property, just display its `Name`.
> Fix issue with dotnet-counters not being able to target user-defined EventSource

- src/SOS/SOS.Hosting/LLDBServicesWrapper.cs
- src/SOS/SOS.NETCore/MetadataHelper.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/datatarget.h
- src/SOS/Strike/disasmARM64.cpp
- src/SOS/Strike/dllsext.cpp
- src/SOS/Strike/gchist.cpp
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/hostcoreclr.h
- src/SOS/Strike/sos.cpp
- src/SOS/Strike/soshostservices.h
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/SOS/lldbplugin/services.cpp
Issue #https://github.com/dotnet/diagnostics/issues/56
Both Windows and Linux minidumps don't save all the assemblies' metadata which can cause
stack traces to display !Unknown. On Windows most debuggers like Windbg and VS can load
the module from file for this kind of dumps. On Linux lldb/SOS doesn't load the native
modules and really doesn't know anything about the managed assemblies.
Add metadata callback to datatarget and it's implementation in SOS.NETCore.
Add IsMetadataMemory() and the metadata region list. This is because lldb on core dumps
returns 0's on missing metadata memory reads instead of an error.
> Fix missing metadata in Linux core dumps.

- documentation/tutorial/app_is_leaking_memory_eventual_crash.md
There was a small typo in the tutorial for memory leak example that specified an incorrect name for the provider in the command for dotnet-counters. 
cc @MarioHewardt
> Fix a small typo in memory leak tutorial

- .vsts-dotnet.yml
- eng/build-native.sh
- eng/docker-build.sh
- eng/init-distro-rid.sh
- src/SOS/SOS.Hosting/SOS.Hosting.csproj
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.InstallHelper/InstallHelper.cs
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
- src/Tools/dotnet-dump/dotnet-dump.csproj
- src/Tools/dotnet-sos/dotnet-sos.csproj
Build on alpine docker container.
Add new MUSL SOS binaries to dotnet-dump/dotnet-sos.
Add new "linux-musl-x64" rid to SOS installer and
dotnet-dump.
Skip the "clrstack -i" tests that fail on alpine and 3.0.x.
> Add alpine/MUSL SOS build/packaging

- eng/Versions.props
- src/Microsoft.Diagnostic.Repl/Command/Attributes.cs
- src/Microsoft.Diagnostic.Repl/Command/CommandBase.cs
- src/Microsoft.Diagnostic.Repl/Command/CommandProcessor.cs
- src/Microsoft.Diagnostic.Repl/Microsoft.Diagnostic.Repl.csproj
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/ClrModulesCommand.cs
- src/Tools/dotnet-dump/Commands/ExitCommand.cs
- src/Tools/dotnet-dump/Commands/HelpCommand.cs
- src/Tools/dotnet-dump/Commands/ModulesCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Commands/SetThreadCommand.cs
- src/Tools/dotnet-dump/Program.cs
Update System.CommandLine to 0.2.0-alpha.19254.1.
Fixes issues: https://github.com/dotnet/diagnostics/issues/127 https://github.com/dotnet/diagnostics/issues/234
Remove the separate older System.CommandLine version for the Repl. Replaced
the depreciated MethodBinder usage with explicit reflection invoke.
Added the CommandInvoke and HelpInvoke attributes to mark the entry
points into the command class.
Changed the command invoke from async (Task InvokeAsync) to synchronous
(void Invoke) because SOS and CLRMD are basically single threaded.
> Update System.CommandLine for dotnet-dump

- src/Tools/dotnet-dump/Commands/HelpCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Commands/SetThreadCommand.cs
User feedback determined that using the artificial thread index to select the thread in dotnet-dump is less confusing than the OS ID.  Both cdb and lldb select threads this way.
> Change the dotnet-dump setthread command to take the thread index

- documentation/dotnet-trace-instructions.md
The providers help mention profile, but it is not in the docs.
I took the profile description from https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/dotnet-tools.md
But I'm not sure if we should keep the information in both places
It also refers to some profiles not available in the current release 1.0.3-preview5.19251.2. The only profile in this version is runtime-basic
> Missing profile argument

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
When the `-tasks` flag is set, we look at every object on the heap and walk its hierarchy to decide if it's a task or a task-derived type.  But we currently do that by comparing the name of every object against "System.Threading.Tasks.Task", which is very expensive.  This switches to comparing by module and type def.  On my machine, a `!dumpasync -tasks` command that previously took ~1 minute now takes ~30 seconds.
cc: @PatrickCarnahan, @mikem8361, @noahfalk
> Improve perf of `!dumpasync -tasks`

- src/Tools/dotnet-counters/ConsoleWriter.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
This will fix https://github.com/dotnet/diagnostics/issues/297
Also removed some useless code that can't be reached.
> Display unknown EventSource's provider name properly

- src/Tools/dotnet-counters/CounterMonitor.cs
Fix issue #298. 
This was added mainly for debugging purposes during development but an end user might think of it as a crash rather than a graceful exit even though it's supposed to be a graceful exit case.
> Do not display exception on graceful exit case

- src/Tools/dotnet-counters/Program.cs
dotnet-counters might throw when we have a leftover pipe from a process that is not running anymore
> Fix dotnet-counters to not throw on list-processes command

- documentation/dotnet-trace-instructions.md
Two people have asked me so far on how to view `netperf` file - I checked and it seems like we only have a section on how to collect the trace, but not on how to actually use/view the trace. Adding that section.
Also I tried to mention the word dotnet-trace more in the doc. I searched for `dotnet-trace` on Google/Bing and this doc doesn't show up in the first page. For dotnet-counters, it shows up in the top 3 result in both Google and Bing. Not exactly sure why but I think I just mentioned that word more often in the doc when I wrote it. (I also tweeted about it - maybe that affects it?) Anyways, I'm not a SEO expert but I tried...
cc @tommcdon @noahfalk @jorive @cshung @josalem
> Update dotnet-trace documentation

- src/Tools/dotnet-counters/ConsoleWriter.cs
Fixes #318. 
Also modified `displayPosition`'s key slightly to be robust to potential key collisions when same counter names are used across different providers.
> Clear out correct length for counter value 

- eng/install-test-runtimes.ps1
- eng/install-test-runtimes.sh
- src/SOS/SOS.NETCore/SOS.NETCore.csproj
When the 3.0 preview 6 runtime is the only one available, it causes
dotnet-dump to throw a missing method exception. This is because it
tries to load the wrong SOS.NETCore.dll assembly from the runtime
directory instead of the one that comes with dotnet-dump/SOS.
The workaround is to change the SOS.NETCore assembly version
to 4.8.0.x which is greater than the 4.7.x version of the
preview 6 runtime.
> Fix dotnet-dump when running on preview 6

- src/Tools/dotnet-counters/KnownData.cs
Active timer counter was added via https://github.com/dotnet/coreclr/pull/25186. This is the client side change to reflect it.
> Add active timer count to known list of counters

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Fixes #316 
The trace recording is displayed in the UI as:
`Recording trace 1.733 (MB)`
This fix aligns the unit of the trace recording size (MB) so that it does not move left and right when the number of digits changes.
> Fix width of trace recording to be constant

- documentation/design-docs/dotnet-tools.md
- documentation/design-docs/ipc-protocol.md
- documentation/dotnet-trace-instructions.md
- documentation/tutorial/app_running_slow_highcpu.md
- documentation/tutorial/installing_the_diagnostics_tools.md
- eng/Versions.props
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/SessionConfiguration.cs
- src/Tools/dotnet-analyze/Program.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ConvertCommand.cs
- src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
- src/Tools/dotnet-trace/TraceFileFormatConverter.cs
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/Program.cs
This is a breaking change. You need to use a corresponding version of the runtime that supports selecting the format in the IPC message. I'm attempting to merge both changes at the same time to minimize the disruption.
> Update tools to use the newer NetTrace EventPipe format

- src/Microsoft.Diagnostic.Repl/Command/Attributes.cs
- src/Microsoft.Diagnostic.Repl/Command/CommandBase.cs
- src/Microsoft.Diagnostic.Repl/Command/CommandProcessor.cs
- src/Microsoft.Diagnostic.Repl/Console/CharToLineConverter.cs
- src/Microsoft.Diagnostic.Repl/Console/ConsoleProvider.cs
- src/Microsoft.Diagnostic.Repl/Console/OutputType.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticHelpers.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcCommands.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcHeader.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcMessage.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/DiagnosticMessageType.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/MessageHeader.cs
- src/Tools/dotnet-dump/AnalyzeContext.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/ClrModulesCommand.cs
- src/Tools/dotnet-dump/Commands/ExitCommand.cs
- src/Tools/dotnet-dump/Commands/HelpCommand.cs
- src/Tools/dotnet-dump/Commands/ModulesCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Commands/SetThreadCommand.cs
- src/Tools/dotnet-dump/Dumper.Linux.cs
- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
- src/tests/Microsoft.Diagnostics.Tools.RuntimeClient/Program.cs
This handles all the occurrences that are capitalized.
All I did is replace "Diagnostics" -> "Diagnostic" and then replace "Diagnostic" -> "Diagnostics" on all C# files, case sensitive.
The test related files are intentionally unchanged.
> Standardize on spelling (Diagnostic -> Diagnostics)

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
The dotnet-trace version of [this](https://github.com/dotnet/diagnostics/commit/a87793919aed645d4594b3891de75904f1453d55) commit.
To see why I switched to use HandlerDescriptor, see the implementation of [`System.CommandLine.Invocation.CommandHandler.Create`](https://github.com/dotnet/command-line-api/blob/c26fbd19464a9117a6c86de749424d5c723eccc5/src/System.CommandLine/Invocation/CommandHandler.cs#L135) method. It wouldn't accept 8 generic arguments, so I simply called what it would have called instead.
@tmds
> Using CancellationToken in dotnet-trace

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
This fixes #339 and improves the error message displayed when we exit with a FileCreationError.
> Avoid unnecessary allocation & better error message on file exists error

- src/SOS/Strike/strike.cpp
- In particular for the pointer to saved original code when using GCStress, which is specific to the code version
- Part of https://github.com/dotnet/coreclr/pull/25261
- Part of fix for https://github.com/dotnet/coreclr/issues/17646
> For sos.u on a code address, pass in the code address to retrieve information about that code version

- .vsts-dotnet.yml
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/disasm.cpp
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/hostcoreclr.h
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
The previous fix forced the metadata to always go through
the metadata locator callback interface. This fix the problem
when the metadata in the core dump isn't complete, but broke
getting metadata for user/app assemblies that only exist in
the core dump.
Needed to "fallback" to reading the core dump memory for the
metadata when the assembly can't be found or downloaded.
Cleaned up building the module list.
> Fix missing metadata problems

- eng/Build-Native.cmd
- eng/CreateVersionFile.csproj
- eng/Versions.props
- eng/create-gallery-zip.ps1
Change the major/minor/patch to 3.0.0 to match our runtime.
Changed the extension gallery zip file and version to the file version
generated by Arcade.
> Change SOS and diagnostic tool versioning

- src/Tools/dotnet-counters/ConsoleWriter.cs
Fixes #317
Displays counter names and counter values in separate columns. Also accommodates for user adding counter names that are longer than the width of the counter names column.
> Align counter values

- src/SOS/Strike/disasm.cpp
- src/SOS/Strike/disasm.h
- src/SOS/Strike/disasmARM.cpp
- src/SOS/Strike/disasmARM64.cpp
- src/SOS/Strike/disasmX86.cpp
- src/SOS/Strike/strike.cpp
Rewrite the "u -gcinfo" code to not require Windows fibers,
and enable it for non-Windows platforms.
Also,
1. Enable "u -gcinfo" for ARM.
2. Fix minor issues with EHinfo/GCinfo to ensure end-of-function info is displayed
> Enable disasm mixed gc info

- documentation/dotnet-trace-instructions.md
There are some confusions regarding how to use `dotnet-trace` to collect EventCounter data - I'm adding a brief instruction on how to do that to `dotnet-trace` docs.
> Add instructions about how to collect counter data via dotnet-trace

- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.Hosting/dbgeng/DebugDataSpaces.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/SOS.NETCore/Tracer.cs
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/hostcoreclr.h
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/LoggingCommand.cs
Finds or downloads the native modules like coreclr.dll or managed
assemblies into the virtual address space of the core dump. Emulates
what the Windows debugger do for minidumps.
> Add Windows PE reading to dotnet-dump

- documentation/dotnet-trace-instructions.md
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/Provider.cs
Something is double escaping escape characters in the input arguments.  If someone specifies a provider of `Microsoft-DotNETCore-Runtime:0:0:filter="reallycool\r\nfilter"`, it will have been converted to `Microsoft-DotNETCore-Runtime:0:0:filter="reallycool\\r\\nfilter"` by the time it reaches `CollectCommand` in the `providers` input argument.  Using the `System.Text.RegularExpressions.Regex.Unescape` method, we can ensure that this double escape is removed and we send the _correct_ bytes across the IPC transport.
DiagnosticSourceEventSource uses new-line delimited strings in its provider filter to specify transforms for diagnostics messages, so this change plus dotnet/coreclr#26159 should unblock anyone using DiagnosticSourceEventSource via dotnet-trace.
CC - @tommcdon
> Remove double escape in provider filter strings

- src/Tools/dotnet-counters/ConsoleWriter.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/CounterPayload.cs
**This change improves output formatting in dotnet-counters by:**
1. Right aligning counter values.
2. Decimal numbers are aligned on the decimal separator.
3. Introducing thousand separators.
**It fixes the following bug:**
- If monitoring multiple providers (for example System.Runtime and a user-defined one), the provider and counter names get mixed up in the output.
I simplified the logic in `ConsoleWriter.cs` a great deal with these changes, so it has 63 fewer lines than before now.
**This is how it looked before this change:**
```
Press p to pause, r to resume, q to quit.
Status: Running
[Driver-Volume-b]
GetPathStatus /sec                              422.127609176254
[System.Runtime]
CPU Usage (%)                                   7
[Driver-MmfStore]
Files downloaded /sec …
```
> Improve output formatting and fix bugs in dotnet-counters

- src/Tools/dotnet-trace/CommandLine/Commands/ConvertCommand.cs
- src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
If you run `dotnet-trace convert` without any --format argument, it defaults to nettrace format, which causes an exception like the one reported in https://github.com/dotnet/diagnostics/issues/454. 
Changing the default behavior of the convert command to convert to speedscope format instead of the nettrace format.
> Make a different option to change the default format for convert command

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Adds a new `--duration` option to `dotnet-trace` that allows a user to specify a time in seconds after which the trace will automatically end.  The trace can be prematurely stopped using the same inputs as a regular trace.
This is one step in making automation using `dotnet-trace` easier.
CC - @tommcdon
> Add duration option to dotnet-trace

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Fix nullref caused in System.CommandLine by having a default value of null for duration.
Turns out you can't use `null` as a default value for an argument with the version of System.CommandLine that we are using.  Fixed by using `default(TimeSpan)` instead.
CC - @tommcdon
> Fix nullref thrown in System.CommandLine for dotnet-trace collect

- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
We originally disabled these profiles in https://github.com/dotnet/diagnostics/pull/178 because of a runtime issue which caused GC events to not show up and was fixed around preview 6 timeframe (https://github.com/dotnet/coreclr/pull/24198). Now that the runtime fix has been out for a while, these profiles should be public again.
> Make gc/gc-collect profiles available

- documentation/design-docs/dotnet-tools.md
1) Rename 'runtime-basic' -> 'cpu-sampling' to better align with what we are going to tell users to use it for. Technically you can do other things with it too, but I think we should favor names that describe what it is usually used for vs. being generic to cover less common possibilities.
2) Eliminated the 'none' option. We got feedback this option was confusing and hard to discover. The original goal was that final providers = --profile config + --providers config. Since --profile defaulted to cpu sampling you needed a way to disable that part of it, the 'none' profile. The new approach is to only provide a default profile when both --profile and --providers haven't been specified. I am also suggesting some help and command-line output spew to make it obvious why the default profile …
> Improve dotnet-trace profile CLI syntax

- eng/Versions.props
- eng/build.yml
- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
- src/SOS/SOS.Hosting/LLDBServices.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.Hosting/dbgeng/DebugSymbols.cs
- src/SOS/SOS.UnitTests/Debuggees/GCWhere/GCWhere.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
- src/SOS/Strike/exts.cpp
- src/SOS/Strike/exts.h
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/sos_unixexports.src
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/SOS/Strike/xplat/dbgeng.h
- src/SOS/lldbplugin/inc/lldbservices.h
- src/SOS/lldbplugin/services.cpp
- src/SOS/lldbplugin/services.h
- src/SOS/lldbplugin/soscommand.cpp
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommandForWindows.cs
- src/inc/dacprivate.h
Implement GetEEVersion for xplat using the embedded "@(#)Version" string.
Enabled/add the "eeversion" command for xplat.
Added LLDBService2::GetModuleVersion to get the version string via the "sccid" symbol. Fallback
to using search the data sections to the version string.
Added same to SOSHost so eeversion works in dotnet-dump.
Fixed initializing g_moduleInfo for Linux. It is used by dumpmt. Added new LLDBService2::GetModuleInfo api to do this.
Added "dumparray" alias to lldb command aliases.
Add testing for the eeversion command.
> Fix dumpmd/ip2md commands for < 3.x runtimes

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices/RegisterService.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/Strike/strike.cpp
- src/pal/prebuilt/inc/fxver.h
Update cdb version to 10.0.18362 and fixes a program in the dotnet-dump analyze register service because the dumps generated by this new cdb have bigger thread context's.
Fix issue in the read virtual memory module mapping for dotnet-dump analyze on Windows.
> Various fixes and update cdb

- src/Tools/dotnet-counters/CounterMonitor.cs
@josalem just reported an issue where if the app exits before dotnet-counters, we get a timeout on StopTracing command and it crashes dotnet-counters with an unhandled exception. This fixes that bad behavior.
> Fix a timeout exception causing unhandled exception crash

- src/Tools/dotnet-counters/ConsoleWriter.cs
This change is a fix for #500. 
When the `DisplayName` of the `DiagnosticCounter` is empty or null the fallback is to use the name of the Counter.
> Fix output of console writer of dotnet-counters when displayname is not set

- src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsHelpers.cs
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs
The `BitConverter.ToXXX(ReadOnlySpan<Byte>)` methods are not available when targetting .NET standard 2.0 (it is only available when targetting .NET standard 2.1 preview). The methods can simply be replaced by the `BitConverter.ToXXX(Byte[], Int32)` methods instead.
> Fix BitConverter calls

- .vsts-dotnet.yml
- eng/Versions.props
- eng/build.yml
- src/Directory.Build.props
- src/Microsoft.Diagnostics.DebugServices/Microsoft.Diagnostics.DebugServices.csproj
- src/Microsoft.Diagnostics.Repl/Microsoft.Diagnostics.Repl.csproj
- src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
- src/Microsoft.Diagnostics.Tools.RuntimeClient/Microsoft.Diagnostics.Tools.RuntimeClient.csproj
- src/SOS/SOS.NETCore/SOS.NETCore.csproj
- src/SOS/SOS.Package/SOS.Package.csproj
- src/SOS/SOS.UnitTests/Debuggees/Directory.Build.props
Both Windows and Portable PDBs are published.
Change to Windows PDB for SOS.NETCore.dll in sos symbol zip file
Publish Microsoft.Diagnostics.TestHelpers, DebugServices, Repl and RuntimeClient symbols
> Publish symbols part 2

- src/Tools/dotnet-trace/TraceFileFormatConverter.cs
Related issue: #521 
When the app being traced exists abruptly from unhandled exceptions or signals, they don't flush all the events that are in the runtime's buffer that holds the events, which leads to the last payload to have truncated values in them. This is an expected behavior by design that we don't intend to change. 
When the user views the trace file from such a case, they may run into issues where TraceEvent won't be able to properly parse the event payload due to incomplete tags, so tools like PerfView throws an exception and refuses to continue. However, PerfView has the /ContinueOnError option to continue on such error and make "best effort" to parse the trace file, to show whatever *can* be parsed. 
This changes dotnet-trace's speedscope converter to do the same thing, but …
> Add /ContinueOnError option to speedscope converter

- documentation/design-docs/dotnet-tools.md
- src/Tools/dotnet-trace/Extensions.cs
- src/tests/dotnet-trace/ProviderParsing.cs
> [dotnet-trace] Allow user to specify text version of event level

- src/Tools/dotnet-trace/TraceFileFormatConverter.cs
* Add /ContinueOnError option to speedscope converter
* Display a warning message when we have to continue on error
* Only retry if the exception thrown is from a broken trace
> Add /ContinueOnError option to speedscope converter (#526)

- src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/Provider.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/Extensions.cs
- src/Tools/dotnet-trace/Profile.cs
- src/tests/dotnet-trace/ProfileProviderMerging.cs
Some minor refactoring to accommodate testing the logic for merging providers specified by `--providers` and those specified with `--profile`.  We only have 3 profiles right now and they all essentially use the same provider, so the tests are minimal for now, but the refactors make it trivial to add more of these tests as we add providers.
CC - @tommcdon
> [test] Profile-Provider Merging Tests

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices/MemoryCache.cs
- src/Microsoft.Diagnostics.DebugServices/MemoryService.cs
- src/Microsoft.Diagnostics.DebugServices/Microsoft.Diagnostics.DebugServices.csproj
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.Hosting/dbgeng/DebugDataSpaces.cs
- src/SOS/SOS.UnitTests/Scripts/WebApp.script
- src/SOS/Strike/dllsext.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/Tools/dotnet-dump/Analyzer.cs
Issue: https://github.com/dotnet/diagnostics/issues/503
The "new" dumpheap testing found problems in the Windows minidump read memory that "maps" the actual PE module into the virtual space. The new tests caused the DAC/SOS to read sections of the PE modules that had relocations but were not fixed up in the original module mapping code.  This only happens on Windows minidumps because Linux core dumps have all the necessary fixed up sections (except the metadata which is handled in the native SOS code for xplat) and Windows minidumps don't.
Add MemoryService to package up all the read memory "mapping" logic.
Add MemoryCache to module mapping logic.
Rewrote ReadVirtualCache because of a couple of bugs that caused
some test failures on triage dumps making !pe displaying the exception
message …
> Fix dumpheap failures on certain dumps.

- documentation/dotnet-trace-instructions.md
I noticed the none profile has been removed.
How can we disable all providers and use only the ones in --providers?
> Updated profiles

- src/tests/benchmarks/benchmarks.csproj
This adds support for benchmarks in 3.1 and 5.0 runtimes/SDK.
> Update benchmarkdotnet version to 0.12.0

- src/Tools/dotnet-counters/CounterPayload.cs
- src/tests/dotnet-counters/CSVExporterTests.cs
- src/tests/dotnet-counters/JSONExporterTests.cs
An incorrect name/value was being displayed for rate (Incrementing) counters that are user-defined. 
This fixes #563.
> Fix incorrect value displayed for rate counters

- documentation/design-docs/dotnet-tools.md
This is an initial specification for a commandline tool capable of collecting GC Heap Dumps of dotnet processes on Linux, Mac, and Windows.
CC - @caslan
> Add initial spec for gcheap dump tool

- THIRD-PARTY-NOTICES.TXT
- documentation/design-docs/ipc-protocol.md
- documentation/dotnet-gcdump-instructions.md
- src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
- src/Tools/dotnet-gcdump/CommandLine/ProcessStatusCommandHandler.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapInfo.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/GCHeapDump.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/MemoryGraph.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/README.md
- src/Tools/dotnet-gcdump/Program.cs
- src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
Adds the `dotnet-gcdump` tool.  The spec for this tool is in another PR (#512).
This PR includes some code that has been copied from  Microsoft/PerfView.  The reasoning is in the README that is included in the directory they were copied to.  To sum it up, the refactoring required to expose these classes via TraceEvent was turning into more of a hassle than it was worth.  There were diamond dependencies and target framework conflicts that would have been very disruptive to TraceEvent.
This tool will _only_ work with .NET Core 3.1-preview2 or newer (.NET 5).
If this tool is used with runtimes older than that, then _only_ the first gcdump will be viable.  All subsequent dumps will be missing type information due to an issue in the runtime.  Additionally, older runtimes will be missing COM …
> dotnet-gcdump

- .vsts-dotnet-ci.yml
- .vsts-dotnet.yml
As part of repo consolidation, we're cleaning up the root `cross` folders in coreclr, corefx, and core-setup and moving over to the Arcade `eng/common/cross` folder. As part of this work, we're updating the `eng/common/cross` folder to use the `toolchain.cmake` from CoreCLR. That `toolchain.cmake` uses CMake features in 3.13, so this PR updates the docker images used to build to match CoreCLR (which uses at minimum CMake 3.14).
I didn't update the Windows images since we don't use the toolchain.cmake file there.
> Update the docker images used to have a newer version of CMake.

- documentation/design-docs/diagnostics-client-library.md
This is a draft proposal for the diagnostics client library - which we've been calling the "runtime client library" till now - (yes the rename is part of the proposal but I really want us to stop calling it the runtime client library :p). 
Some of the sample code is still left TODO, but I think this is at a point where we can openly start discussing about the design choices.
cc @noahfalk @josalem @mikem8361 @tommcdon
> Draft Proposal for Diagnostics Client Library (a.k.a. "Runtime Client Library")

- src/Microsoft.Diagnostics.TestHelpers/ProcessRunner.cs
Before, the ProcessRunner waited for the process completion as well as stream
buffer flushing for stdout and stderr. This is problematic if the process
it ran dies, but its spawned child processes keep the defunct's standard
streams alive by redirecting to them. We have had no way of harvesting
the children, so this process hung the runner.
After this change, we wait for the spawned process to die. As soon as that happens,
we give the pipes a grace period of 15 seconds to flush, after which we assume
the process is dead. This has the shortcoming of two potentially problematic
situations:
- We've potentially left an unobserved aggregate exception unobserved that will throw
on the finalizer thread once the tasks get collected in exceptional cases.
- This might leak threadpool threads.
> Wait for process exit independently of waiting for stream flushing

- src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
- src/Tools/dotnet-gcdump/runtimeconfig.template.json
Prevent default value for pid
add roll forward runtimeconfig to dotnet-gcdump
> Fix default PID value and add rollforward forgcdump

- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
Adds the following options to the test helper condition attribute:
```
Contains(string, string)
StartsWith(string, string)
EndsWith(string, string)
```
And adds argument validation.
> Add new function options to conditions in test runner

- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
- src/Microsoft.Diagnostics.TestHelpers/TestRunner.cs
* The config parser had one remaining bug in the case of negative expressions
* Logging paths can't have wildcards, but runtime specifiers can. In that case I resorted to use `<Major.Minor.Patch>` as the version for the log while preserving old behavior. That way xUnit still displays the full arg list for test disambiguation, but the logs only contain valid file names.
> Fix config parser and logging path to support

- src/Tools/dotnet-trace/TraceFileFormatConverter.cs
SpeedScope handles only CPU samples, events are not supported. Using a PerfView analogy, it has `CPU Stacks` view, but no `Events` view.
So when we are creating `SampleProfilerThreadTimeComputer` we need to filter out the events, otherwise every event is treated as CPU sample in https://github.com/microsoft/perfview/blob/8897bb64c2a252fff7282e89a4cfafabeb1e4ffc/src/TraceEvent/Stacks/SpeedScopeStackSourceWriter.cs#L58 and hence we get events in the output speedscope file.
Fixes #623
> SpeedScope handles only CPU samples, events are not supported

- src/tests/eventpipe/ContentionEvents.cs
The test failed in daily CI runs in Windows X64 Debug build.
The captured ContentionEvents count is 47 but not more than 50.
[https://dev.azure.com/dnceng/internal/_build/results?buildId=453484&view=ms.vss-test-web.build-test-results-tab](https://dev.azure.com/dnceng/internal/_build/results?buildId=453484&view=ms.vss-test-web.build-test-results-tab)
So I changed the events count check to > 0 to make the test more stable in CI runs.
> Fix ContentionEvents test to make it more stable

- src/tests/eventpipe/GCEvents.cs
`GCCreateConcurrentThread` events may be fired before we see the first event from the runtime, so checking this always being > 0 causes this test to randomly fail.
> Fix GCEvent test being flakey

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
As you know we want to add a new profiling plugin to BenchmarkDotNet based on EventPipe and SpeedScope (https://github.com/dotnet/BenchmarkDotNet/pull/1321)
Every BenchmarkDotNet library targets .NET Standard 2.0. Currently `Microsoft.Diagnostics.NETCore.Client` targets .NET Core 2.1 only. If we want to consume it, we either need to add .NET Core 2.1 to all our libraries or introduce a new library with the new plugin only (I would prefer to avoid that).
It would make our life easier if `Microsoft.Diagnostics.NETCore.Client` could target .NET Standard 2.0 as well.
This PR adds the .NET Standard 2.0 support. I've tested it on Ubuntu and it works fine.
> [Proposal] add .NET Standard 2.0 for diagnostics client library

- src/tests/Grape/Grape.csproj
- src/tests/Grape/Program.cs
- src/tests/Grape/TestRunner.cs
- src/tests/Grape/TraceGeneratorConfiguration.cs
- src/tests/Grape/TraceGenerators/EtwTraceGenerator.cs
- src/tests/Grape/TraceGenerators/EventPipeTraceGenerator.cs
- src/tests/Grape/config.json
This is the first of many steps involved to achieve #571. To prevent myself from checking in a PR that's too large to review I'm breaking it down to small pieces.
This PR adds a way to generate EventPipe and ETW traces. I ripped out LTTng trace generation for now because I ran into some issues regarding piping out perfcollect and haven't figured out how to consume perfcollect (download it manually per each run from aka.ms/perfcollect or check in the script to this repo, etc.).
Following this PR will be:
- LTTng trace generation
- Trace validation (Consuming & Validating the events from the generated trace)
- Trace comparison (Comparing two different traces generated from private builds of runtime)
- Integration with the diagnostics CI for automation
- Docs on how to use this
> Initial commit for Grape - a testing framework for trace generation on .NET 

- eng/build.yml
- src/tests/eventpipe/ContentionEvents.cs
- src/tests/eventpipe/EventPipe.UnitTests.csproj
- src/tests/eventpipe/GCEvents.cs
- src/tests/eventpipe/LoaderEvents.cs
- src/tests/eventpipe/MethodEvents.cs
- src/tests/eventpipe/ThreadPoolEvents.cs
- src/tests/eventpipe/common/IpcTraceTest.cs
- src/tests/eventpipe/providers.cs
> Fix EventPipe tests to use the new DiagnosticsClient library

- documentation/design-docs/diagnostics-client-library.md
This is a simple fix to the sample code to actually print string name of the CLR events (instead of printing it as "Task-something")
> Fix sample code in DiagnosticsClient library docs

- src/pal/src/misc/sysinfo.cpp
glibc has deprecated sys/sysctl.h:
In file included from /coreclr/src/pal/src/misc/sysinfo.cpp:32:
/usr/include/sys/sysctl.h:21:2: error: "The <sys/sysctl.h> header is deprecated and will be removed." [-Werror,-W#warnings]
#warning "The <sys/sysctl.h> header is deprecated and will be removed."
^
1 error generated.
Fix that by preferring sysconf and only including sys/sysctl.h if
HAVE_SYSCONF is not true. This mirrors the order of the implementation
code in this file (sysinfo.cpp) which checks for HAVE_SYSCONF
before HAVE_SYSCTL.
Fixes #27008
> Handle glibc sys/sysctl.h deprecation (#27048)

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
> Fix newline formatting for dotnet-trace provider info

- documentation/dotnet-trace-instructions.md
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/Extensions.cs
- src/tests/dotnet-trace/CLRProviderParsing.cs
This adds `--clrevents` flag to dotnet-trace similar to how PerfView does it. 
Example usage:
`dotnet-trace collect -p <pid> --clrevents gc+gchandle`.
> Add --clrevents flag to dotnet-trace

- .vsts-dotnet.yml
- eng/Build-Native.cmd
- eng/build.ps1
- src/SOS/CMakeLists.txt
- src/SOS/SOS.NETCore/CMakeLists.txt
- src/SOS/SOS.NETCore/SOS.NETCore.csproj
- src/SOS/SOS.Package/SOS.Package.csproj
- src/SOS/SOS.Package/SOS.Symbol.Package.csproj
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/util.h
- src/sos-packaging.props
Make sure that the "BuildArch" msbuild property is always passed to managed and native builds.
Add the arm64 SOS to the various packages and zip files.
The diasymreader package for Windows PDB support is currently disabled for arm64 waiting
for issue https://github.com/dotnet/diagnostics/issues/324 to be addressed.
Issue: https://github.com/dotnet/diagnostics/issues/430
> Build Windows arm64 version of SOS.

- src/SOS/SOS.UnitTests/Scripts/OtherCommands.script
- src/SOS/Strike/runtime.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
Change "dbgout" command not to require EE or DAC (use INIT_API_EXT).
Fix case where the DAC is already in the temp directory because of a
loadsymbols command when symlink'ing it on Linux.
Allow just setsymbolserver -log without any other options.
> Misc SOS fixes

- src/Tools/dotnet-dump/Dumper.cs
> dotnet-dum output text to say 'dump' rather than 'minidump'

- README.md
- documentation/privatebuildtesting.md
- documentation/sos.md
- eng/CleanupPrivateBuild.csproj
- eng/InstallRuntimes.proj
- eng/build.ps1
- eng/build.sh
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/DualRuntimes.script
- src/SOS/Strike/runtime.cpp
- src/SOS/Strike/runtime.h
- src/SOS/Strike/sos.def
- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/Strike/strike.cpp
- src/SOS/lldbplugin/setclrpathcommand.cpp
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
Enable the "setclrpath" for Windows.
Change the SOS test harness and scripts to set the runtime path for triage dumps.
Add -privatebuildpath option to build scripts that installs the test runtimes, copies
the private runtime build and on Windows regedit's the necessary keys to create dumps.
> Fix the Windows private runtime build testing problems

- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/TestRunner.cs
Change TestRunner to not rely on having arbitrary sleep and instead poll for the socket file creation.
> Make diagnostics client library tests not sleep

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeProvider.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeProviderTests.cs
Semicolon is a special character in EventSource argument parser. To embed a semicolon inside the argument string it needs to be wrapped with quotation.  
This fixes #753.
> Properly encode semicolon in argument strings for EventPipeProvider

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
Try to get UnixDomainSocketEndPoint from System.Core if not found in System.Net.Sockets
Fixes #821
> Try to get UnixDomainSocketEndPoint from System.Core if not found in System.Net.Sockets

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeProvider.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeProviderTests.cs
This addresses the same issue as #824 but for the keys of the argument dictionary.
> Escape EventPipeProvider argument key as well

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
Get UnixDomainSocketEndPoint using Type.GetType() to avoid FileNotFoundException
Fixes #821
> Get UnixDomainSocketEndPoint using Type.GetType() to avoid FileNotFoundException

- documentation/diagnostics-client-library-instructions.md
This is an API doc for Microsoft.Diagnostics.NETCore.Client. I also included the sample code that used to be in the design doc.
> Microsoft.Diagnostics.NETCore.Client Documentation

- eng/cross/tryrun.cmake
Fix cross build:
```
...
-- Performing Test HAVE_COMPATIBLE_ACOS
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
HAVE_COMPATIBLE_ACOS_EXITCODE (advanced)
HAVE_COMPATIBLE_ACOS_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see /home/viewizard/Desktop/diagnostics/artifacts/obj/Linux.armel.Release/TryRunResults.cmake
-- Performing Test HAVE_COMPATIBLE_ACOS - Success
-- Performing Test HAVE_COMPATIBLE_ASIN
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
HAVE_COMPATIBLE_ASIN_EXITCODE (advanced)
HAVE_COMPATIBLE_ASIN_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see /home/viewizard/Desktop/diagnostics/artifacts/obj/Linux.armel.Release/TryRunResults.cmake
-- Performing …
```
> Updates tryrun.cmake for cross build

- eng/build.yml
- src/SOS/SOS.UnitTests/Scripts/lldbhelper.py
> Update build.yml to use OSX 10.14

- diagnostics.yml
Fixes the "DUP" errors in the symbol publishing stage.
> Add symbol publishing property to disable the special indexing

- eng/Version.Details.xml
- eng/Versions.props
This reverts commit ee8ed8048c825db6af021dc794e3ecc0d649df03.  This version of the AspNetCore runtime still works against a busted version of the runtime.
> Revert "[master] Update dependencies from dotnet/aspnetcore (#886)"

- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
The new "full" dump collection type includes all the module images
on both Windows and Linux. The old default type "Heap" is still
the same and can be used if the dump is too big.
Full dumps are roughly 1.5 times bigger on Windows and 30%
bigger on Linux for a simple webapp.
Issue: https://github.com/dotnet/diagnostics/issues/808
> Change the "dotnet-dump collect" default to "full" dumps.

- src/SOS/Strike/hostcoreclr.cpp
Look for the /etc/dotnet/install_location file on Linux/MacOS
for the .NET Core runtime to host SOS's managed code.
Didn't add the check for Windows registry key at this time
because we may switch to the desktop CLR as the host.
Issue #https://github.com/dotnet/diagnostics/issues/882
Add 5.0 to the list of hosting runtime versions.
> Add .NET Core hosting location file support

- src/Microsoft.Diagnostics.Repl/Console/ConsoleProvider.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/ExitCommand.cs
The exit command would fail to exit the analyze process when
executed from the command line.
> Fix dotnet-dump analyze <dump-path> -c exit

- src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
Given #913 I'm disabling this test until it can get investigated.
This path is exerted in https://github.com/dotnet/diagnostics/blob/d366deb72b8dc114e2c74075134bf300224fa1ff/src/Tools/dotnet-dump/Dumper.cs#L77 
dotnet-dump has several tests for collecting dump types, so even if we disable the test, we still get some coverage.
> Disable Microsoft.Diagnostics.NETCore.Client.WriteAllDumpTypesTest

- src/SOS/SOS.UnitTests/Scripts/DualRuntimes.script
- src/SOS/Strike/EventCallbacks.cpp
- src/SOS/Strike/exts.h
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/runtime.cpp
- src/SOS/Strike/runtime.h
- src/SOS/Strike/strike.cpp
Feels a bit messy/clumsy, but it is good enough to at least start a conversation...
Fixes #908 & #909
> Fix Runtime::GetRuntime*Name() for cross-dac

- src/SOS/Strike/strike.cpp
> dotnet-dump analyze clrthreads -special

- src/SOS/Strike/strike.cpp
Some commands are not included in dotnet-dump analyze Linux support.
Add ONLY_SUPPORTED_ON_WINDOWS_TARGET() to disable these
commands when working with Linux dumps on Windows.
> Add ONLY_SUPPORTED_ON_WINDOWS_TARGET()

- src/SOS/Strike/strike.cpp
Mark all commands not reachable from Linux LLVM
or dotnet-dump analyze on Linux ONLY_SUPPORTED_ON_WINDOWS_TARGET
> Mark more APIs ONLY_SUPPORTED_ON_WINDOWS_TARGET

- diagnostics.yml
- eng/InstallRuntimes.proj
- eng/build.ps1
- eng/build.sh
- eng/build.yml
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
Adds 2 pipeline variables that need to be set testing an internal service release:
DotNetRuntimeVersion - the service release version to test i.e. 2.1.17, 3.1.3, etc,.
DotNetRuntimeDownloadVerison - the service release version to download i.e. 3.1.3-servicing.20128.1,
No longer runs the tests on desktop framework if private build or internal service release.
Remove dailytest option
> Support testing internal service releases

- documentation/debugging-coredump.md
The --host-only dotnet-symbol option has some problems.
> Update core dump debugging workflow

- documentation/design-docs/dotnet-tools.md
Proposing new verb for reading from a gcdump and write the result in stdout.
The PR for the code is here: https://github.com/dotnet/diagnostics/pull/791
> dotnet-gcdump: Update docs to include print verb

- src/Tools/dotnet-counters/CounterProvider.cs
- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
- src/Tools/dotnet-counters/KnownData.cs
- Cleanup unused field DisplayName as dotnet-counters now knows how to parse DisplayName field from the counter payloads.
- Fix description of GC collection counts in list command
> Fix description list command

- src/SOS/Strike/eeheap.cpp
Testing arm dump analyze on Linux showed:
```
Large object heap starts at 0x72500000
segment     begin  allocated      size
724FF000  72500000  72502250  0x2250(1812174861)
4A62D000  4A62E000  5A62E020  0x10000020(1812174861)
2962C000  2962D000  2962D000  0x0(1812174861)
Total Size:              Size: 0x1000dab4 (268491444) bytes.
```
On Windows it showed:
```
Large object heap starts at 0x72500000
segment     begin  allocated      size
724FF000  72500000  72502250  0x2250(8784)
4A62D000  4A62E000  5A62E020  0x10000020(268435488)
2962C000  2962D000  2962D000  0x0(0)
Total Size:              Size: 0x1000dab4 (268491444) bytes.
```
Windows version is correct.
> Fix eeheap output on 32-bit targets

- src/SOS/SOS.Hosting/LLDBServices.cs
- src/SOS/SOS.Hosting/SOSHost.cs
Use the platform default calling convention to support dotnet-dump on Linux x86.
Partially fixeees https://github.com/dotnet/diagnostics/issues/846.
> Use Winapi calling convention to support Linux x86

- src/Tools/dotnet-counters/CounterMonitor.cs
dotnet-counters currently starts an EventPipeSession with default EventPipe session buffer size which is 256MB, which shouldn't be necessary given that most counter payloads are < 500 bytes in size.
> Reduce the default buffer size requested for counter session to 10MB

- diagnostics.sln
- src/SOS/CMakeLists.txt
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/CMakeLists.txt
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/datatarget.h
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/hostcoreclr.h
- src/SOS/Strike/runtime.cpp
- src/SOS/Strike/runtime.h
- src/SOS/Strike/sos_unixexports.src
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/dbgutil/CMakeLists.txt
- src/SOS/dbgutil/dbgutil.cpp
- src/SOS/dbgutil/dbgutil.vcxproj
- src/SOS/dbgutil/elfreader.cpp
- src/SOS/dbgutil/elfreader.h
- src/SOS/lldbplugin/soscommand.cpp
- src/SOS/lldbplugin/sosplugin.cpp
- src/Tools/dotnet-dump/Analyzer.cs
- src/inc/clrdata.idl
- src/inc/llvm/Dwarf.def
- src/inc/llvm/Dwarf.h
- src/inc/llvm/ELF.h
- src/inc/runtimeinfo.h
- src/pal/prebuilt/idl/clrdata_i.cpp
- src/pal/prebuilt/inc/clrdata.h
Adds the elfreader from the runtime repo to use to find the "DotNetRuntimeInfo" export when search for the runtime module. 
Plumbs through the build ids from this runtime info to download the DAC and DBI modules.
Add ICLRRuntimeLocator DAC interface (that returns the runtime module base address) to datatarget provided to the DAC.
Cleaned up the DAC/DBI  download code using new Microsoft.SymbolStore support.
> Single-file exe SOS support

- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
When you use dotnet-counters monitor in a pc that has any culture with diferent decimal separator than english's separator the process crashes.
Not any error is displayed but the terminal doesn't update and doesn't respond to inputs
This PR fix the problem related with the use of literals for decimal separator adding support for other culures.
> Support to non english cultures in the terminal display

- eng/Versions.props
- src/SOS/SOS.Hosting/dbgeng/DebugAdvanced.cs
- src/SOS/SOS.Hosting/dbgeng/DebugClient.cs
- src/SOS/SOS.Hosting/dbgeng/DebugControl.cs
- src/SOS/SOS.Hosting/dbgeng/DebugDataSpaces.cs
- src/SOS/SOS.Hosting/dbgeng/DebugRegisters.cs
- src/SOS/SOS.Hosting/dbgeng/DebugSymbols.cs
- src/SOS/SOS.Hosting/dbgeng/DebugSystemObjects.cs
- src/SOS/Strike/strike.cpp
- src/Tools/dotnet-dump/Commands/ClrModulesCommand.cs
Add assembly version to clrmodules -v command.
Add more info to dumpmodule.
Update clrmd to version 1.1.122004. See PR https://github.com/microsoft/clrmd/pull/609 for details.
> Update clrmd to fix dotnet-dump module enum perf.

- eng/Analyzers.props
- eng/CodeAnalysis.Repository.ruleset
- eng/CodeAnalysis.Security.ruleset
- eng/CodeAnalysis.ruleset
- src/Directory.Build.props
- src/Microsoft.Diagnostics.Monitoring/Logging/LogValuesFormatter.cs
- src/Microsoft.Diagnostics.Monitoring/Logging/LoggerException.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSessionConfiguration.cs
- src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/Tools/dotnet-dump/Program.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs
- src/tests/eventpipe/common/IpcTraceTest.cs
Add roslyn analyzers and corresponding rules to ensure compliance with compliance and fix basic errors spotted by first round of analyzers.
> Enable roslyn analyzers

- diagnostics.yml
- eng/build.yml
Uses new runtime parameters yml feature for URL/Token resolution in the installation of testing runtimes. See https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runtime-parameters?view=azure-devops&tabs=script
Adds 3 alternate sources to choose when kicking off the pipeline that look like this:
- **Custom**: Can specify a special feed/blob container to try to fetch packages from picked from the `DotnetRuntimeDownloadFeed` pipeline variable.
- **msrc-feed**: Points to the MSRC feed
- **dotnetclimsrc-feed** This contains for example our testing bits for 3.1 and 2.1
There's the same 3 options to select the tokens for the SAS base 64 read token to use in authenticated feeds, with the custom variable being `DotnetRuntimeDownloadBase64SasToken`.
3.1 build: …
> Servicing testing fixes

- src/Tools/dotnet-gcdump/DotNetHeapDump/EventPipeDotNetHeapDumper.cs
Fixes issue where the log messages had erroneous times in them.  The "ticks" returned by `Stopwatch.GetTimestamp()` are potentially a different "tick" than the ticks expected by `TimeSpan.FromTicks` depending on the resolution of the system's internal clock.
> Use DateTime.Now instead of Stopwatch.GetTimestamp()

- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessModel.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/RuntimeInfo.cs
- src/Tools/dotnet-monitor/Startup.cs
These changes update the existing api controller methods of the dotnet-monitor tool to match the changes in #1014 and the comments that were provided. Some of the highlights are:
- The api root is now at / e.g. http//:localhost:52323/ is the root of the api.
- The dump and cpuprofile verbs now allow implicit process selection if a process ID is not specified. There is a specialization for docker where it will go directly to process 1 if it exists.
- The processes verb returns process objects with pids (object to be filled out once reverse api server is available to use).
- Changed the defaults of some of the parameters to match the OpenAPI definition and its suggested changes.
> Refactor DiagController to better match the OpenAPI description.

- src/tests/DacCompareNativeTypes/Program.cs
Revise type mismatch to be a more condensed readable format
Require all pdb type alternates to have a match
Print all alternate types
Add a list of types to ignore based on manual observation
Ignore problematic offset of Basetypes
> Revise DacCompareNativeTypes

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeProvider.cs
- src/tests/eventpipe/CustomEvents.cs
Fix #1062. 
- Change default keyword of EventPipeProvider to `0xF00000000000`
- Add test that verifies events without keywords are produced with EventPipeProvider without keywords specified.
> Fix EventPipeProvider to enable listening to events without keyword

- src/Microsoft.Diagnostics.Monitoring/Configuration/AggregateSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring/Configuration/HttpRequestSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
The logs endpoint does not need the HTTP request configuration information since it is not capturing that information from the event pipe event source. This refactors the HTTP request configuration separate from logging configuration and then aggregates the two for the trace endpoint.
> Split HTTP request configuration from logging configuration.

- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring/Configuration/AggregateSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
Combine all nettrace-producing endpoints into the trace endpoint.
Client can specify which event profiles they want using the profile query parameter.
> Unify all nettrace endpoints into single trace endpoint.

- documentation/dotnet-counters-instructions.md
- documentation/dotnet-gcdump-instructions.md
- documentation/dotnet-trace-instructions.md
- src/Tools/Common/Commands/Utils.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Program.cs
- src/Tools/dotnet-counters/dotnet-counters.csproj
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
- src/Tools/dotnet-dump/dotnet-dump.csproj
- src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
- src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Options/CommonOptions.cs
- src/Tools/dotnet-trace/dotnet-trace.csproj
Address #296.
This adds the `--name` option support to dotnet-counters (collect, monitor), dotnet-trace (collect), dotnet-dump (collect), and dotnet-gcdump (collect). 
Also fixed a few typos in dotnet-gcdump along the way.
> Add --name option to CLI tools

- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs
Have dotnet-monitor check that the Docker entrypoint process is dotnet with diagnostics transport before assuming that it's a viable process when using the REST APIs without specifying a process.
> Validate Docker entrypoint is dotnet process with diagnostics transport.

- src/Tools/dotnet-counters/CounterPayload.cs
- src/tests/dotnet-counters/CSVExporterTests.cs
- src/tests/dotnet-counters/JSONExporterTests.cs
This changes dotnet-counters behavior when the payload has DisplayRateTimeScale property. Specifically, we heard many feedback that it is confusing for them to see the values extrapolated to a seemingly random value. For instance, "Gen 2 GC / min" would always show up as multiples of 60 if user requested 1 second as `--refresh-interval`. It is easy for users to confuse that as "60 Gen 2 GCs has happened in the past minute", which is not what happened. What really happens here is that if there has been 1 Gen 2 GC happened in the interval at which the user requested, it gets extrapolated to a "/ min" value, so it gets multiplied by 60 and shows up as 60 Gen 2 GCs / min. 
This PR removes that behavior by simply ignoring the DisplayRateTimeScale property and only showing the value that it …
> Remove extrapolation from dotnet-counters

- eng/InstallRuntimes.proj
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/build.ps1
- eng/common/build.sh
- eng/common/internal/Tools.csproj
- eng/common/native/CommonLibrary.psm1
- eng/common/performance/perfhelixpublish.proj
- eng/common/performance/performance-setup.ps1
- eng/common/performance/performance-setup.sh
- eng/common/pipeline-logging-functions.sh
- eng/common/post-build/publish-using-darc.ps1
- eng/common/post-build/symbols-validation.ps1
- eng/common/sdk-task.ps1
- eng/common/sdl/execute-all-sdl-tools.ps1
- eng/common/templates/job/job.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/tools.ps1
- eng/common/tools.sh
- global.json
- src/Microsoft.Diagnostics.TestHelpers/Microsoft.Diagnostics.TestHelpers.csproj
Add the IsTestProject false property to TestHelpers so it will build with the new arcade.
Add the 3.1.4 runtime to global.json so the non-SOS tests (Microsoft.Diagnostics.NETCore.Client.UnitTests, etc.) run.
Remove always installing 2.1 in InstallRuntimes.proj since 3.1 is required for xunit tests and always installed.
> Fix and apply the arcade update

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
The speculation here:
- In docker scenarios where the main process is pid 1 and so is the dotnet monitor process, we open the stream to verify it exists, and then open it again and use it. The first creates a file which the second call might attempt to use to communicate with the event pipe.
> Make underlying stream own the socket

- eng/Versions.props
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/Strike/runtime.cpp
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
Update to CLRMD version 1.1.127808
Enabled dotnet-dump collect for MacOS
> Add MacOS dotnet-dump support

- src/Tools/dotnet-trace/Extensions.cs
- src/tests/dotnet-trace/ProviderParsing.cs
Fix #1190. 
The issue was caused by two issues:
1) When you specify argument filter string via dotnet-trace and the character `"` is used to escape the argument string, it gets double-escaped by the logic in DiagnosticsClient library that tries to escape characters that have special characters (`=`, `;`) in them.
2) `\r\n` is not properly passed in.  
To avoid this, we can remove the wrapping `"` character from dotnet-trace side before we pass it to `EventPipeProvider`. To solve the second issue, we can just apply `Regex.Unescape`.
cc @davidmikh
> Remove quotations from dictionary values when populating the argument dictionary for EventPipeProvider

- src/Tools/dotnet-monitor/dotnet-monitor.csproj
Set dotnet-monitor version to preview 1. This is mostly used to allow the dotnet-docker dependency update mechanism to correctly update the dotnet-monitor version in the docker file manifest.
> Set dotnet-monitor to Preview 1

- eng/Publishing.props
- src/Directory.Build.targets
These changes generate and publish package version files to blob feed so that other processes can determine the latest package version within a blob group. These changes also refactor how the package artifact files (namely, checksum and version) are discovered by keying off of each package file and attempting to discover the related files rather than keying off of the checksum files.
> Upload NuGet packages with blob group to installers blob feed

- src/SOS/Strike/exts.h
- src/SOS/Strike/strike.cpp
Choose registers to display at runtime based on actual target
Fixup Arm64 to use the Arm64Context (not the ArmContext)
Fixup Arm64 to display all registers (instead of displaying some multiple times)
Fixup Arm64 formatting to right justify register values in three columns.
Fixes #1245 
Fixes #1246
> Fix up SOS PrintManagedFrameContext

- eng/Publishing.props
The previous change did not set that Category metadata correctly. It was set as metadata on the ItemsToPushToBlobFeed item which means it was not written out the manifest. Thus, the artifact publishling step would just try to upload the nupkg to the NuGet feed twice rather than once to the NuGet feed and once to the blob feed (when Category is not present in the artifact metadata, it determines the destination feed based on the file extension). This change fixes it to be set in the ManifestArtifactData metadata so that it is written out to the manifest and consumed by publishing correctly.
ManifestArtifactData for package before change:
`<ManifestArtifactData>NonShipping=true</ManifestArtifactData>`
ManifestArtifactData for package after change: …
> Add category metadata to ManifestArtifactData metadata instead of Category metadata

- src/Microsoft.Diagnostics.DebugServices/AnalyzeContext.cs
- src/Microsoft.Diagnostics.DebugServices/DiagnosticsException.cs
- src/Microsoft.Diagnostics.DebugServices/IThreadService.cs
- src/Microsoft.Diagnostics.DebugServices/RegisterInfo.cs
- src/Microsoft.Diagnostics.DebugServices/ThreadInfo.cs
- src/Microsoft.Diagnostics.DebugServices/ThreadService.cs
- src/SOS/SOS.Hosting/LLDBServices.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.UnitTests/Scripts/OtherCommands.script
- src/SOS/SOS.UnitTests/Scripts/WebApp.script
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/RegistersCommand.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/Tools/dotnet-dump/Commands/SetThreadCommand.cs
Renames the RegisterService to ThreadService and adds methods to implement these issues:
https://github.com/dotnet/diagnostics/issues/558 "setthread should support different types of thread ids"
https://github.com/dotnet/diagnostics/issues/559 "Sort threads by thread id"
> Add thread service

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
dotnet-trace was not respecting the --buffersize flag.
> respect --buffersize flag in dotnet-trace

- eng/Publishing.props
Publish Assets pipeline step failed to upload the dotnet-monitor nupkg file to the other category feed because the categories are put into a case sensitive dictionary as uppercased keys (see https://github.com/dotnet/arcade/blob/74b625183ecd38826808b62118bafa22b2daf182/src/Microsoft.DotNet.Build.Tasks.Feed/src/PublishArtifactsInManifest.cs#L437). Fixing it here to specify the Other category as uppercase.
> Change blob item category to uppercase.

- src/SOS/Strike/eeheap.cpp
- src/SOS/Strike/gcroot.cpp
- src/SOS/Strike/sos.cpp
- src/SOS/Strike/sos.h
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.h
- src/inc/sospriv.idl
- src/pal/prebuilt/inc/sospriv.h
Fixes #1068
Corresponding runtime changes in https://github.com/dotnet/runtime/pull/37853. I have an editor extension that removes trailing whitespace, sorry for the large amount of whitespace changes. I was not aware how much trailing whitespace there was in the SOS sources.
> Add POH to SOS commands

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices/MemoryService.cs
This is at least an interim fix until microsoft/clrmd#774 is fixed.
/cc @leculver @hoyosjs
> Handle 32-bit CLRDATA_ADDRESS semantics in ReadMemory

- src/SOS/SOS.UnitTests/SOS.cs
This change disables four SOS unit tests for the .NET 5 x86 configuration due to issue #1289, which has been consistently failing builds for the last several days.
> Skip tests that invoke DumpHeap command on .NET 5 x86.

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices/MemoryService.cs
* Handle 32-bit CLRDATA_ADDRESS semantics in ReadMemory
* Use clrMD 1.1.132302
> Handle 32-bit CLRDATA_ADDRESS semantics in ReadMemory (#1280)

- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/Strike/sos.cpp
Re-enable GC tests for Windows x86 disabled in https://github.com/dotnet/diagnostics/issues/1289
> Fix Windows x86 dumpheap

- src/Tools/dotnet-counters/CounterMonitor.cs
> Catch ServerNotAvailableException being thrown on non-abrupt exits of target app

- src/SOS/Strike/gcroot.cpp
The std::List<t>::size() method was not guaranteed to be linear complexity
until C++11.  Apparently the Centos Containers we are using to build the
diagnostic repo do not have C+11 compliant StdLib headers installed.
Fixes #633
> Fix performance issue with gcroot

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/inc/sospriv.idl
- src/pal/prebuilt/idl/sospriv_i.cpp
- src/pal/prebuilt/inc/sospriv.h
Issue: https://github.com/dotnet/runtime/issues/27309
We should get this version check in for our next SOS/global tools release next week.
> Add check for the breaking change version with the new ISOSDacInterface9 interface

- src/Tools/dotnet-counters/CounterMonitor.cs
Related issue: #1260. 
A `NullReferenceException` may be thrown when `_session` object hasn't been initialized (i.e. the tool tried to start an EventPipe session but it hasn't been able to establish a connection yet) and the user tries to exit the tool.
> Fix a potential NullReferenceException when counter session hasn't started yet

- src/Microsoft.Diagnostics.Monitoring.RestServer/CorsConfiguration.cs
- src/Tools/dotnet-monitor/Startup.cs
Enable Cors policy to allow client side script apps to access dotnet monitor apis.
Resolves #1346 
Note there are some simplifications here from the original proposed solution:
- Policy is for origins only, no granular policy for methods or headers
- Origins can be specified through environment variables: 
e.g. `DotnetMonitor_CorsConfiguration__AllowedOrigins=http://localhost`
or through appsettings.json:
`{
"Logging": {
"LogLevel": {
"Default": "Warning"
}
},
"AllowedHosts": "*",
"CorsConfiguration": {
"AllowedOrigins":  "http://localhost"
}
}
`
> Add support for CORS

- src/Microsoft.Diagnostics.Repl/Command/CommandBase.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/ExtensionCommands/ClrMDHelper.cs
- src/Tools/dotnet-dump/ExtensionCommands/ExtensionCommandBase.cs
- src/Tools/dotnet-dump/ExtensionCommands/TimerInfo.cs
- src/Tools/dotnet-dump/ExtensionCommands/TimersCommand.cs
- TimerInfo lists timers details and displays a summary
- both ClrMD 1.1 and 2.0 implementations are provided (based on ClrMD2 symbol
defined or not to make the move to 2.0 simple by just removing the 1.1 code)
> Add new "extended" commands based on ClrMD to dotnet-dump

- src/Tools/Common/Commands/Utils.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
* Uses `Stream.CopyToAsync` instead of manually copying bytes using `Stream.Read` and `Stream.Write`
* Simplifies try/catch blocks
* Improves rendering of console text due to ordering of the new loop
* Removes need for polling in the UI thread, which greatly simplifies code
* Removes the console clear since the rendering is cleaner now 
* removes `hasConsole` to allow for redirection of input and output
> Simplify dotnet-trace main loop

- src/Tools/dotnet-gcdump/CommandLine/CollectCommandHandler.cs
This ensures that collection taken in the afternoon are sorted after
those taken in the morning.
> Use 24 Hour Time in Default Output Format

- src/Tools/dotnet-counters/CounterProvider.cs
- src/Tools/dotnet-counters/KnownData.cs
- src/Tools/dotnet-counters/Program.cs
For #1368. 
Note that the default runtime version is chosen to be 3.1 (since 5.0 is still in Preview and won't ship till later this year). 
Example output:
```
➜  dotnet-counters git:(dev/suwhang/1368) dotnet-counters list --runtime-version 5.0
Showing well-known counters for .NET (Core) version 5.0 only. Specific processes may support additional counters.
To see counters supported in other veresions of .NET (Core), try using --runtime-version flag.
System.Runtime
cpu-usage                        		 Amount of time the process has utilized the CPU (ms)
working-set                      		 Amount of working set used by the process (MB)
gc-heap-size                     		 Total heap size reported by the GC (MB)
gen-0-gc-count                   		 Number of Gen 0 GCs / min
gen-1-gc-count …
```
> Add --runtime-version flag to dotnet-counters list command

- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsService.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/ProcessFilter.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
- src/Tools/dotnet-monitor/Startup.cs
This change allows the user to specify the runtime instance ID instead of the process ID when executing diagnostic operations via the REST API. This is most useful in the reversed server scenario when process ID usage can be ambiguous. For example, if the /processes endpoint returns `{ "pid": 1, "uid": "EC73140B-5B14-45D1-AF86-864CD62E7ADC" }`, then the trace endpoint can be executed using either `/trace/1` or `/trace/EC73140B-5B14-45D1-AF86-864CD62E7ADC`. All of the REST API endpoints that formerly only took a process ID have been updated to accept both identifiers.
> Allow process selection using runtime instance cookie.

- diagnostics.yml
- src/SOS/SOS.Package/SOS.Package.csproj
- src/SOS/Strike/runtime.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
Extension gallery manifest fix.
Fix coreclr reload message for linux dumps on Windows.
Fallback to getting assembly name (like when SOS is running on Linux/OSX) when building a function name when either GetModuleByteOffset or GetModuleNames fail.
Add target based get directory separator char function (GetTargetDirectorySeparatorW) to use in the linux module name returned by dbgeng for linux core dumps on Windows.
> Misc SOS changes

- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
When helping one of our customers, we noticed dump async didn't work.
We were trying to lookup SPC by name, but the path separator was assuming a target=host separator.
> Fix module lookup by name

- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
> Fix diagnostics client test hang in CentOS 

- src/Microsoft.Diagnostics.Monitoring/ServerEndpointInfoSource.cs
- src/Microsoft.Diagnostics.Monitoring/ServiceCollectionExtensions.cs
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
- src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
- src/tests/dotnet-monitor/EndpointInfoSourceTests.cs
This change separates the concern of having the reversed server needing a listening loop from allowing the caller to accept new connections. Now the caller can invoke AcceptAsync as need rather than needing to continuously await it.
Example usage of new API surface:
```
await using var server = new ReversedDiagnosticsServer(transportPath);
server.Start(maxConnections: 100);
while (true)
{
var endpointInfo = await server.AcceptAsync(token);
Task _ = Task.Run(() => HandleNewEndpointInfo(endpointInfo), token);
}
```
The naming changes make the ReversedDiagnosticsServer API surface analogous to the TcpListener API surface (without the Stop method; stopping the server is currently done by disposing it).
Note: It is required that that caller invoke the Start method before calling any other …
> Separate accepting new connections from loop that listens for all connections.

- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/Strike/strike.cpp
On Linux/MacOS '/' isn't allowed as an option but the dumpil command had '/i'. The reason '/' is not allowed on xplat is that it caused problems parsing file paths as args. It most cases '-' is used except for this case and for the dml '/d' which isn't supported on lldb.
I'll fix it by adding -i as an option to dumpil and add it to the doc.
This also give me the chance to remove a bunch of unnecessary #ifndef FEATURE_PAL around the "/d" DML option.
Issue #https://github.com/dotnet/diagnostics/issues/1478
> Fix the dumpil /i on Linux

- src/SOS/Strike/strike.cpp
On ARM64, running on Linux, 64-bit registers printed in truncated form: only least significant 32 bits. This PR fixes this issue. Basically, issue caused by usage of PRIxxx macro from inttypes.h. See details in commit commentary.
Issue caused by #1250 (when "%llx" was changed to PRIx64).
Related PRs: #1249 and #1250
> Fix bug in SOS PrintManagedFrameContext (64-bit regs)

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/UnixDomainSocket.cs
Fix #821 again because it broke after we moved the code to UnixDomainSocket.cs.
> fix UnixDomainSocketEndPoint type exception on Mono

- src/Tools/dotnet-monitor/dotnet-monitor.csproj
Bumping the dotnet-monitor version to preview 3 to version the newer packages above the ones that used the older version scheme.
> Bump dotnet-monitor to 5.0.0-preview.3.*

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
I have also chosen to improve the code by converting it into a generator method. This will save us from necessity to call `Regex.Match` twice and parse numbers twice (in a callback to `Where` and in a callback to `Select`).
Also, I've explicitly passed `CultureInfo.InvariantCulture` to the number parsing method, since I believe this is the right thing to do.
> Fix #1531: filter too long numbers in DiagnosticClient.GetPublishedProcesses

- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/SOS.NETCore/MetadataHelper.cs
- src/SOS/Strike/cordebugdatatarget.h
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/hostcoreclr.h
This was also useful when testing the DBI changes to enable this callback for cross-OS DAC.
> Add ICorDebug metadata locator for clrstack -i failures

- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
Disables the tests for the new failures coming in from the latest 5.0 rc-2 builds.
https://github.com/dotnet/runtime/issues/42296
https://github.com/dotnet/diagnostics/issues/1567
> Disable eeversion test for Alpine

- documentation/tutorial/app_is_leaking_memory_eventual_crash.md
- documentation/tutorial/app_running_slow_highcpu.md
- documentation/tutorial/hung_app.md
- documentation/tutorial/intermittent_memory_spike.md
> Update outdated list-processes command on diagnostics tutorials doc

- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
The logging causes the tests to timeout because of the excessive stack overflow logging.
> Disable createdump dump logging for stack overflow tests

- eng/Versions.props
- src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
Remove workaround in command processor.
This update also fixes option aliases like "lm -v".
> Update to latest System.CommandLine (2.0.0-beta1.20467.2)

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Fixes #1577
The upgrade of S.CommandLine changed the `T defaultValue` on arguments to `Func<T> getDefaultValue`.  `default` for a `Func<T>` is `null`, so we nullrefed when it tried to build the command line parser.
> Fix GetDefaultValue func

- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsService.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessIdentifierModel.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Models/ProcessModel.cs
- src/Microsoft.Diagnostics.Monitoring/ClientEndpointInfoSource.cs
- src/Microsoft.Diagnostics.Monitoring/CommandLineHelper.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/IDiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/Contracts/IEndpointInfoSource.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticServices.cs
- src/Microsoft.Diagnostics.Monitoring/DiagnosticsEventPipeProcessor.cs
- src/Microsoft.Diagnostics.Monitoring/EndpointInfo.cs
- src/Microsoft.Diagnostics.Monitoring/ServerEndpointInfoSource.cs
- src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/IpcEndpointInfo.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerHelper.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
- src/tests/dotnet-monitor/CommandLineHelperTests.cs
- src/tests/dotnet-monitor/EndpointInfoSourceTests.cs
Summary:
- Get additional process information when collecting diagnosable processes.
- Get command line via event pipe if GetProcessInfo command failed.
- Fix getting command line via event pipe to wait for information before completing.
- Add additional process information to the /processes/{id} and the environment block to the /proceses/{id}/env endpoints.
closes #1470
> Get command line, process name, os, process architecture, and process environment.

- eng/InstallRuntimes.proj
- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices/ThreadService.cs
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/Scripts/DivZero.script
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
- src/SOS/SOS.UnitTests/Scripts/WebApp.script
- src/SOS/Strike/ExpressionNode.cpp
- src/SOS/Strike/cordebugdatatarget.h
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/disasm.h
- src/SOS/Strike/disasmARM.cpp
- src/SOS/Strike/disasmX86.cpp
- src/SOS/Strike/exts.h
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/inc/dbgtargetcontext.h
Disabled installing and running on 2.1.x when arm/arm64.
Fix the test scripts for arm64 registers.
Upgraded to testing on 3.1.8 and 2.1.23.
Add IMachine::SetContextFlags() and IMachine::GetFullContextFlags() to better support
cross-architecture/cross-OS. Had to use a hard coded context flags for each architecture
because the normal DT_CONTEXT_FULL define only exists for the currently building arch.
The main reason `clrstack -i -a` was failing because the architecture bits in the context
flags were being passed into the DAC/DBI were wrong so the context wasn't being copied.
DAC/DBI context copy helper function that is very sensitive to the dst/src context flags
(at the architecture specific bit) matching.
```
void CORDbgCopyThreadContext(DT_CONTEXT* pDst, const DT_CONTEXT* pSrc)
{
DWORD …
```
> Fix testing on arm64.

- diagnostics.yml
- eng/build.yml
- src/SOS/SOS.Package/SOS.Symbol.Package.csproj
- src/sos-packaging.props
This is roughly what I think should work...
+ I Hijacked the osGroup usage a bit adding MacOS_cross, but it seemed simplest for now.  Probably will eventually need to be cleaned up.  Possibly when we move all the builds to using the XCode12 tool chain.
+ I am not sure exactly about pool configuration/queue names.
+ I am not sure whether prepare machine might need extra work...
> Add osx-arm64 to packges/CI

- src/Tools/dotnet-counters/Exporters/CSVExporter.cs
- src/Tools/dotnet-counters/Exporters/JSONExporter.cs
Fixes https://github.com/dotnet/diagnostics/issues/1643
The `CSVExporter` and `JSONExporter` use the invariant culture to write (double) values.
Additional change is to use a "stringbuilder pattern" that avoids some string-concatenations (= allocationns).
This want make a huge difference for the counter global-tool, but can be "nice" in server environments.
/cc: @sywhang
> dotnet-counters collect export with invariant culture

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
The ServerSourceAddRemoveSingleConnectionTest fails very often when checking that the CommandLine, OperatingSystem, and ProcessArchitecture fields are not null. These fields are filled by issuing a GetProcessInfo command and may be null if the runtime doesn't respond within the timeout period (currently 3 seconds) or if the runtime doesn't understand the command. It's likely that the runtime isn't responding to the command in a timely manner given that this test is failing against the .NET 5.0 RC2 runtime. I've increased the timeout in IpcClient to be even longer to accommodate resource constrained environments.
closes #1609
> Increase IpcClient connect timeout for resource constrained environments

- src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
- src/Tools/dotnet-monitor/Program.cs
Rename the reversed server transport argument for dotnet-monitor to make it consistent with the diagnostic port terminology.
> Rename reversed-server-address arg to diagnostic-port.

- src/Microsoft.Diagnostics.DebugServices/MemoryService.cs
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/Strike/datatarget.cpp
- src/SOS/Strike/exts.h
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/runtime.cpp
Remove the address sign extending in memory service
Fix sosstatus display and error messages for x86/arm32
> Fix dotnet-dump cross-OS arm32 issues on Windows 

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
Related to and depends on https://github.com/dotnet/runtime/pull/38225
When the managed portable thread pool is enabled:
- Made the `ThreadPool` command work as expected, including `ThreadPool -ti` to show in-memory hill climbing thread adjustment history
- After the command queries the native side for info, it looks for a couple of static variables to determine if the portable thread pool is available and enabled
- If it's enabled, it collects equivalent information from the managed side
- Verified that the command works with and without the changes in https://github.com/dotnet/runtime/pull/38225, and with the changes in both modes (portable thread pool enabled and disabled)
> Fill ThreadPool command data from portable thread pool info when enabled

- documentation/design-docs/ipc-protocol.md
Fix #1678. 
This reflects changes that were made via https://github.com/dotnet/runtime/pull/40499 to the diagnostics IPC protocol doc.
> Document changes to reverse server in ipc protocol doc

- documentation/building/official-build-instructions.md
- eng/Versions.props
We moved the nightly publishing of the tools to the [dotnet-tools](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json) feed as we are not part of the in-box components.
FYI @shirhatti in case you want to update the dotnet-monitor blogpost.
cc: @jander-msft @wiktork @dotnet/dotnet-diag
> Change feed in docs to dotnet-tools

- documentation/design-docs/dotnet-tools.md
We've had customer requests for a mechanism to get a single set of stack traces from a target process (#1660).  This proposal is to add a `dotnet-stack` tool that would do just that.  I have most of the code for this already implemented in [josalem/DotStack](https://github.com/josalem/DotStack), so implementation shouldn't be too involved.
CC @tommcdon
> Add proposal spec for dotnet-stack tool

- eng/Build-Native.cmd
- src/SOS/Strike/strike.cpp
This was the root cause of the issue reported by the vendors for crossdac `arm` `clrthreads`.
I did an audit of all `%p` usage in strike.cpp, and fixed everything I saw.
I also fixed the automatic copying of SOS on build.
I would love for this to be included in the release, but it can also wait if you want.
> Use SOS_PTR(x) when using %p with varargs

- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/hostcoreclr.cpp
Changes the order on Windows from desktop first then netcore to netcore then desktop CLR.
> Use .NET Core runtime to host on Windows; fallback to desktop CLR

- documentation/dotnet-counters-instructions.md
- documentation/dotnet-trace-instructions.md
[NOT TO BE MERGED UNTIL 5.0 TOOLS SHIP]
Part of #1666 
Since we have docs in both docs.microsoft.com and this repo, we should try to keep them sync'd until we retire the docs in this repo. 
This update is all from the docs that was submitted in the docs repo PR: https://github.com/dotnet/docs/pull/21193/files
> Add instructions on dotnet-counter and dotnet-trace usage at startup

- src/SOS/SOS.UnitTests/Scripts/lldbhelper.py
- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessEnvironmentTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/TestRunner.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
Fixes:
* TestRunner used by Microsoft.Diganostics.NETCore.Client tests - Introduce timeout to tracee process
* lldbhelper script that hangs forever when an ImportError is thrown.
> [Test PR] Stabilize CIs 

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClientExceptions.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/WriteDumpTests.cs
The library throws the unidentified error message: `Profiler attach failed (HRESULT: 0x80131385)`. It is very complicated to understand from the original message that .NET Core 3.1 on macOS doesn't support attach.
> Implemented extended error processing for attaching to .NET Core 3.1 on macOS.

- src/tests/Microsoft.Diagnostics.NETCore.Client/RemoteTestExecution.cs
Increase the process timeout for process launched by RemoteTestExecution because these tests take a bit longer than the other Microsoft.Diagnostics.NETCore.Client tests.
> Increase timeout for dotnet monitor tests to a minute

- src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsOptions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsService.cs
- src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
- src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
Custom metrics example. 
```
{
"Metrics":
{
"Providers":[
{
"Provider": "TestEventSource",
"Counters": [
"TestCounterName",
"TestCounterName2"
]
}
] 
}
}
```
> Add support for configuration of custom metrics

- eng/Build-Native.cmd
- eng/CreateVersionFile.csproj
- src/SOS/SOS.NETCore/SymbolReader.cs
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/Tools/dotnet-dump/Analyzer.cs
Update to test 3.1.10/3.1.24 runtimes and build with 5.0.100 SDK
Upgrade to testing on 2.1.23 runtime
Stop testing latest runtime until DARC update to 6.0
> Use sccsid version.cpp variable to display SOS version on xplat

- documentation/design-docs/ipc-protocol.md
Updates the IPC spec to include dotnet/runtime#40888.
Some minor prose changes and typo fixes as well.
> Update IPC design doc

- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
These tests have been randomly failing in CI due to insufficient timeout. Increasing timeout to make them more stable.
> Increase timeout on EventPipeSession tests

- eng/Versions.props
- global.json
Upgrade to testing on 2.1.23 runtime
Stop testing latest runtime until DARC update to 6.0
> Update to test 3.1.10/3.1.24 runtimes and build with 5.0.100 SDK

- src/SOS/Strike/eeheap.cpp
- src/SOS/Strike/sos.cpp
- src/SOS/Strike/sos.h
- src/inc/sospriv.idl
- src/pal/prebuilt/inc/sospriv.h
The 64-bit implementation of GC now uses one more bit in the methodtable pointer, so SOS needs to mask out one more bit as well.
> Changes for doubly linked freelists in the 64-bit GC

- documentation/dotnet-counters-instructions.md
- documentation/dotnet-dump-instructions.md
- documentation/dotnet-gcdump-instructions.md
- documentation/dotnet-trace-instructions.md
We have duplicate documentation in this repo that may divert over time. Until we can fully migrate to the official docs and remove the duplicate in this repo, linking these docs to the official docs allows us to: 
1. keep the official docs up-to-date with the latest shipped features
2. still check in docs on WIP features while spec'ing
> Link the official documentation in the dev versions of the docs for all CLI tools

- src/Tools/dotnet-counters/Program.cs
Related issue: #1754 
The underlying cause in the issue is System.CommandLine simply calling .ToString() on the default argument. This *can* be fixed by defining a CounterList class and overriding the ToString() (very hacky, yes...), but will be addressed in a different PR, if at all.
I think the best way to address it instead is to deprecate this argument because we now have the `--counters` option which is the preferred way to specify the counters.
This also updates the description for the `--counters` argument.
> Hide counter argument and update --counters option description

- eng/CreateVersionFile.csproj
- src/SOS/SOS.NETCore/CMakeLists.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/strike.cpp
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Program.cs
1) Stop printing the "@(#)Version" prefix of the SOS version on Linux.
2) Change the default symbol cache for dotnet-dump on Windows to VS's.
3) Fix eeversion unhandled exception on Linux when hosted on 5.0.0.
4) Fix `dotnet-dump collect --help` ArgumentOutOfRangeException by reformatting the --type option description.
> Fixes for some vendors issues for the stable release

- eng/CreateVersionFile.csproj
- src/SOS/SOS.NETCore/CMakeLists.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/Strike/hostcoreclr.cpp
- src/SOS/Strike/strike.cpp
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Program.cs
* Fixes for some vendors issues for the stable release
1) Stop printing the "@(#)Version" prefix of the SOS version on Linux.
2) Change the default symbol cache for dotnet-dump on Windows to VS's.
3) Fix eeversion unhandled exception on Linux when hosted on 5.0.0.
4) Fix `dotnet-dump collect --help` ArgumentOutOfRangeException by reformatting the --type option description.
* Fix eeversion unhandled exception on Linux hosted on 5.0.0
This turned out to be that the dotnet-sos installed included runtime binaries
like System.Memory, System.Buffer, etc. that were wrong version for hosting on
5.0.0. This didn't get catch by the normal testing because only certain project
references were copied to the bin directory.
The main part of this fix was to be very explicit in which assemblies are added …
> Fixes for some vendors issues for the stable release (#1785)

- eng/Publishing.props
- src/Directory.Build.targets
Create version files for nupkg that have blobgroup specification. When publishing to blob storage, these files should have an aka.ms latest link generated for them, which should allow other repositories (e.g. dotnet-docker) to more easily pick up the latest version within a versioning line. This change is to mitigate the breaking change from arcade that ignores custom categorization.
> Create and publish nupkg version files

- src/Tools/dotnet-counters/KnownData.cs
The counter description for "/sec" or "/min" is outdated because we decided that it was confusing since it can change depending on the report interval. This updates the descriptions that will show up in the `dotnet-counters list` command to "some-value between interval" instead of "some-value/sec". 
Fix #1813.
> Update outdated known counter descriptions

- eng/Versions.props
- src/SOS/SOS.UnitTests/Debuggees/DotnetDumpCommands/Program.cs
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/Scripts/DumpGen.script
- src/Tools/dotnet-dump/ExtensionCommands/ClrMDHelper.cs
- src/Tools/dotnet-dump/ExtensionCommands/DumpGen.cs
- src/Tools/dotnet-dump/ExtensionCommands/DumpGenCommand.cs
- src/Tools/dotnet-dump/ExtensionCommands/DumpGenStats.cs
- src/Tools/dotnet-dump/ExtensionCommands/GCGeneration.cs
This command allows to see heap content for a specific generation (gen0, gen1, gen2, or loh) like the SOS DumpHeap command.
- Stats for all types (or only types matching the type name if provided)
- Objects adresses matching a MethodTable address
> Add DumpGen command to dotnet-dump

- src/Tools/dotnet-monitor/Program.cs
closes #1639 
Adds a simple warning message that always prints when running dotnet-monitor.
I'm opening this in draft mode so we can discuss the phrasing of the message.  Currently, it will be the first thing printed _always_.
CC @tommcdon
> Add warning message to dotnet-monitor

- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
When exiting dotnet-counters, the caret stays at the position of the last updated counter. This causes garbage when trying to execute new commands:
That's not a big issue in a Windows environment, since I can just execute `cls` to clear the screen. That's much more troublesome on a SSH/Linux session where no such command is available.
This PR moves the caret back to the end of the output when exiting.
> Move caret back to the end when exiting

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Microsoft.Diagnostics.Monitoring.RestServer/Microsoft.Diagnostics.Monitoring.RestServer.csproj
- src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
Fix the monitoring library versions to the 5.0.X range before they are implicitly incremented out of the range. This allows us to reserve the decision to later increment the version manually or to change back to keep versioning in sync with other diagnostic tools.
> Set monitoring library versions to 5.0.X

- src/Tools/dotnet-counters/CounterMonitor.cs
Currently if user doesn't specify the counter list, then this message is printed:
`counter_list is unspecified. Monitoring all counters by default`
Technically this is incorrect because it only monitors "System.Runtime" counters. This message is a remnant from all the way to 3.0 when System.Runtime was the only set of counters published by .NET but it's end of 2020 and we have a lot of counters now : ) 
This PR changes this message to:
`--counters is unspecified. Monitoring System.Runtime counters by default`
> Fix the default message written to console when no --counters is specified

- src/SOS/Strike/exts.cpp
Relates to https://github.com/dotnet/diagnostics/issues/522
Old
```
> pe
SOS does not support the current target architecture 0x0000014c
```
New
```
> pe
The SOS that is loaded does not support the current target architecture '0x014c'. A 32 bit target may require a 64 bit debugger or vice versa.
```
If it loads SOS but can't load the DAC you have always gotten a bit more help:
```
4) you are debugging on a platform and architecture that supports this
the dump file. For example, an ARM dump file must be debugged
on an X86 or an ARM machine; an AMD64 dump file must be
debugged on an AMD64 machine.
```
The ideal here of course is that it seamlessly just works as proposed by @davidfowl in https://github.com/dotnet/diagnostics/issues/522 just as Windbg launches EngHost.exe if it needs to …
> Improve mismatched debugger message

- src/tests/EventPipeStress/Common/BurstPattern.cs
- src/tests/EventPipeStress/Common/Common.csproj
- src/tests/EventPipeStress/Common/Options.cs
- src/tests/EventPipeStress/Orchestrator/CommandLine.cs
- src/tests/EventPipeStress/Orchestrator/Orchestrator.csproj
- src/tests/EventPipeStress/Orchestrator/Program.cs
- src/tests/EventPipeStress/Orchestrator/TestResult.cs
- src/tests/EventPipeStress/README.md
- src/tests/EventPipeStress/Stress/Program.cs
- src/tests/EventPipeStress/Stress/Stress.csproj
Adds a stress testing framework for EventPipe.  Can be used to collect statistics like throughput and efficiency.  It is not meant for automated CI (yet).  It also doesn't consume any live bits from the repo or automated version updates via DARC.  This can be changed if desired.
There's no rush on merging this in since we're right up on vacation season ☃️ 
CC @lateralusX
> Add EventPipeStress framework

- src/Tools/Common/Commands/ProcessStatus.cs
The ps command will fail with a Win32Exception. 
This fixes the ps command handler to look for Win32Exception and NullReferenceException (for Linux/macOS) and make it log if it fails with any other error instead of just crashing.
> "ps" command handler fix 

- src/Tools/dotnet-trace/Extensions.cs
We don't have the comprehensive list of CLR provider keywords that can be passed to `--clrevents` option in `dotnet-trace`. This adds the missing keywords. 
Also, I noticed that how to use the --clrevents option is not documented in our official docs for dotnet-trace so I'll be following up with a docs PR to document this option more in detail.
cc @davidwrighton
> add more well-known keywords in CLR event provider for --clrevents option

- src/Microsoft.Diagnostics.Monitoring.RestServer/ActionContextExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/ArtifactMetadataNames.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagControllerExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/MetricsController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/EgressStreamResult.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScope.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScopeExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/OutputStreamResult.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.json
- src/Tools/dotnet-monitor/ActivityExtensions.cs
- src/Tools/dotnet-monitor/ActivityMetadataNames.cs
- src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
- src/Tools/dotnet-monitor/Egress/AzureBlob/AzureBlobEgressProvider.cs
- src/Tools/dotnet-monitor/Egress/AzureBlobEgressFactory.cs
- src/Tools/dotnet-monitor/Egress/Configuration/EgressConfigureOptions.cs
- src/Tools/dotnet-monitor/Egress/FileSystem/FileSystemEgressProvider.cs
- src/Tools/dotnet-monitor/ExperimentalToolLogger.cs
- src/Tools/dotnet-monitor/Program.cs
- src/Tools/dotnet-monitor/Startup.cs
This is the initial set of changes to improve the logging information for the dotnet-monitor diagnostic tool.
Overview of changes:
- Log exceptions from controller actions and action context executions. Cancellations from an aborted HTTP request are logged at the Information level.
- Add artifact type and endpoint information as logging scopes to the diagnostics and metrics controllers.
- Add additional configuration for console and event log loggers.
- Refactor host builder to route lifetime events through logging and to include console logger by default.
- Write experiment warning message through logging.
TODO:
Example log output when attempting to capture a trace and write out to non-existent egress provider:
```
10:15:35 warn: …
```
> Logging improvements for dotnet-monitor

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.RestServer/appsettings.json
- src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
- src/Tools/dotnet-monitor/dotnet-monitor.csproj
These changes update the console logger to 5.0.0 which allow for JSON formatted console output. However, I've kept the default to be the simple console logger so that typical ad-hoc usage is still easily human readable. I will add environment variables to the Docker file to switch the tool to use the JSON formatter with UTC timestamps and sortable/parseable timestamp format.
The following is an example of it running in the Docker container with the described environment variables set:
```
{"Timestamp":"2021-01-13T19:23:42.6108693\u002B00:00","EventId":60,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository","Message":"Storing keys in a directory \u0027/root/.aspnet/DataProtection-Keys\u0027 that may not be persisted outside of the …
```
> Update console logger and set content root.

- src/Microsoft.Diagnostics.Monitoring.RestServer/KeyValueLogScope.cs
The JSON console logger checks if the log scope implements IReadOnlyCollection<KeyValuePair<string, object>> and then falls back to calling ToString. Add the IReadOnlyCollection<KeyValuePair<string, object>> implementation to better suit the formatted output.
> Update log scope to be more compatible with JSON console logger.

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClientExceptions.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs
Added the clear message without hex error code.
> Add ProfilerAlreadyActiveException in DiagnosticsClient.AttachProfiler()

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MonitoringSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Auth/ApiKeyConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Auth/AuthConstants.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Auth/AuthOptions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Auth/IAuthOptions.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/ConfigurationHelper.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/Controllers/DiagController.cs
- src/Microsoft.Diagnostics.Monitoring.RestServer/MetricsOptions.cs
- src/Microsoft.Diagnostics.Monitoring/ClientEndpointInfoSource.cs
- src/Microsoft.Diagnostics.Monitoring/RuntimeInfo.cs
- src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandler.cs
- src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandlerOptions.cs
- src/Tools/dotnet-monitor/Auth/AuthorizedUserRequirement.cs
- src/Tools/dotnet-monitor/Auth/UserAuthorizationHandler.cs
- src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs
- src/Tools/dotnet-monitor/ExperimentalToolLogger.cs
- src/Tools/dotnet-monitor/GenerateApiKeyCommandHandler.cs
- src/Tools/dotnet-monitor/Program.cs
- src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs
- src/Tools/dotnet-monitor/Startup.cs
- src/Tools/dotnet-monitor/dotnet-monitor.csproj
- Support for ApiKey based authentication
- On Windows, add support for Negotiate
- Change default binding to https. Allow partial success for missing cert.
Note for Windows, Negotiate falls back to NTLM. 
Example message if no cert is available:
```
Unable to bind to https://localhost:52323. Dotnet-monitor functionality will be limited.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
at …
```
> Add authentication to dotnet-monitor

- src/Tools/Common/Commands/Utils.cs
Fix #1988. 
I'm also going to follow-up with a PR that adds tests that launch the tool and check putting in invalid arguments exits with correct error messages.
> Fix dotnet-counters and dotnet-trace CLI arg validator

- eng/Versions.props
Many of these version numbers were added to support dotnet-monitor but are now no longer used.
> Remove unused versions.

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipelineSettings.cs
Enable the UseAppFilter setting for dotnet-monitor. Necessary to fix https://github.com/dotnet/dotnet-monitor/issues/15
> UseAppFilter for Logs pipeline

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcServerTransport.cs
- src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
@lateralusX observed an issue in the ReversedDiagnosticsServer where it will cause the underlying IpcServerTransport to recreate its stream/socket when the server is shutting down. The problem is caused by the token that is passed into ReversedDiagnosticsServer.ListenAsync is passed directly to IpcServerTransport.AcceptAsync; in both of the current implementations of IpcServerTransport.AcceptAsync, it will recreate the underlying stream/socket when the method call is cancelled. Since the IpcServerTransport is not disposed until after the call to AcceptAsync is cancelled, the IpcServerTransport implementation will create a new stream/socket and receive clients even though its about to be disposed. This leads to clients unnecessarily connecting to the server when it is shutting down.
The …
> Dispose transport on cancellation to prevent creation of new server stream/socket on shutdown of ReversedDiagnosticsServer.

- src/Microsoft.Diagnostics.ExtensionCommands/Microsoft.Diagnostics.ExtensionCommands.csproj
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/IRenderer.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/ParallelStack.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/RendererBase.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/RendererHelpers.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/StackFrame.cs
The external nuget is no more referenced. Instead, its implementation has been copied in dotnet-dump instead.
> Remove ParallelStack.Runtime nuget reference 

- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices.Implementation/BinaryLocator.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ImageMappingMemoryService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/MemoryCache.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/MetadataMappingMemoryService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleServiceFromDataReader.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Target.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/TargetFromDataReader.cs
- src/Microsoft.Diagnostics.DebugServices/ITarget.cs
- src/Microsoft.Diagnostics.DebugServices/MemoryServiceExtensions.cs
- src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
- src/SOS/SOS.Extensions/TargetFromFromDebuggerServices.cs
- src/SOS/SOS.Hosting/CorDebugDataTargetWrapper.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
- src/Tools/dotnet-dump/Analyzer.cs
Add ELF file module memory mapping
Rename PEImageMappingMemoryService to ImageMappingMemoryService .
Cache failures in MemoryCache used by image memory mapping service
Handled recursion in image mapping
Add MachO mapping support
Cleanup key generation in symbol service wrapper. Removed extension function.
Fixes issue: https://github.com/dotnet/diagnostics/issues/2043
> Cleanup metadata mapping memory service

- eng/Version.Details.xml
- eng/Versions.props
Update to version 1.0.215101 symstore that has the fix/workaround for the slash (/) fix in the downloader.
> Update symstore to fix forward slash escape download bug

- src/Microsoft.Diagnostics.Repl/Console/ConsoleProvider.cs
- src/Tools/dotnet-dump/Analyzer.cs
This change brings dotnet-dump up to the same level as lldb and cdb/windbg: they both persist the command history between sessions.
> Persist command history in dotnet-dump

- src/SOS/Strike/eeheap.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.h
Remaining bits of #2065 -- this PR adds committed memory as part of the reported stats for `gcheapstat` SOS command.
> Report committed memory as part of gcheapstat

- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/Strike/dbgengservices.cpp
- src/SOS/extensions/extensions.cpp
- src/SOS/lldbplugin/services.cpp
Removed the assumption that a process can't have a 0 id.  Because of a bug in lldb, MacOS dumps all have a process id of 0.
> Fixed MacOS generated coredumps process 0 bug

- src/Microsoft.Diagnostics.Monitoring/ServerEndpointInfoSource.cs
- src/tests/Microsoft.Diagnostics.Monitoring/EndpointInfoSourceTests.cs
The ServerEndpointInfoSource caches endpoints and implicitly prunes them upon demand via the GetEndpointInfoAsync method. This existing logic has an issue where if two or more processes are no longer active, then there is a race condition when trying to remove the endpoints from the _endpointInfos field. Access to the field is not synchronized thus if two pruning tasks attempt to modify the field at the same time, an exception is likely to be thrown:
```
Message: 
System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
Stack Trace: 
List`1.RemoveAt(Int32 index)
List`1.Remove(T item)
ServerEndpointInfoSource.PruneIfNotViable(EndpointInfo info, CancellationToken token) line 161 …
```
> Fix race condition when pruning processes and add test.

- src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
Fix #2101.
This fixes the ReverseDiagnosticServerHelper to use full path to create the reversed diagnostic server.
> Fix reverse connection mode in macOS

- documentation/dotnet-trace-instructions.md
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
fixes #560 
Example filename after patch: `dotnet_20210317_173254.nettrace`
This could be considered a breaking change for users with existing scripts/workflows that expect the old `trace.nettrace` filename by default.
> Change default trace name to app name + timestamp

- src/Tools/dotnet-counters/CounterMonitor.cs
Fix #2135. 
This is a regression from https://github.com/dotnet/diagnostics/pull/1635
> Fix printing exception upon graceful exit

- src/Tools/dotnet-counters/KnownData.cs
Corresponding runtime PR: https://github.com/dotnet/runtime/pull/50604
> Add GC committed bytes to known counters

- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
- Add database profile to dotnet-trace that captures ADO.NET and
EntityFramework events through DiagnosticSourceEventSource. Resulting
file can be viewed in Visual Studio with the PerformanceProfiler
- Add aspnet-requests profile to dotnet-trace that captures ASP.NET
requests and TPL events through DiagnosticSourceEventSource. Resulting
file can be viewed in Visual Studio with the PerformanceProfiler
> Add database and aspnet-requests profiles to dotnet-trace

- src/Microsoft.Diagnostics.TestHelpers/BaseDebuggeeCompiler.cs
- src/Microsoft.Diagnostics.TestHelpers/CliDebuggeeCompiler.cs
- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/Debuggees/DesktopClrHost/CMakeLists.txt
- src/SOS/SOS.UnitTests/Debuggees/Directory.Build.props
- src/SOS/SOS.UnitTests/Debuggees/DivZero/DivZero.csproj
- src/SOS/SOS.UnitTests/Debuggees/DotnetDumpCommands/DotnetDumpCommands.csproj
- src/SOS/SOS.UnitTests/Debuggees/GCPOH/GCPOH.csproj
- src/SOS/SOS.UnitTests/Debuggees/GCWhere/GCWhere.csproj
- src/SOS/SOS.UnitTests/Debuggees/LineNums/LineNums.csproj
- src/SOS/SOS.UnitTests/Debuggees/NestedExceptionTest/NestedExceptionTest.csproj
- src/SOS/SOS.UnitTests/Debuggees/Overflow/Overflow.csproj
- src/SOS/SOS.UnitTests/Debuggees/ReflectionTest/ReflectionTest.csproj
- src/SOS/SOS.UnitTests/Debuggees/SimpleThrow/SimpleThrow.csproj
- src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestApp/SymbolTestApp.csproj
- src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestDll/SymbolTestDll.csproj
- src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/RandomUserLibrary/RandomUserLibrary.csproj
- src/SOS/SOS.UnitTests/Debuggees/TaskNestedException/TaskNestedException/TaskNestedException.csproj
- src/SOS/SOS.UnitTests/Debuggees/WebApp3/WebApp3.csproj
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
This PR gets ready for single-file app testing, but doesn't add the app yet
because the current SDK can't build them and the new SDKs break building
the cli built debuggees.
Also works around that the DAC GetPEFileName()/GetAssemblyName() APIs don't return
the module or assembly name.
> Add single-file app SOS testing Part I

- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/strike.cpp
The `%%` looks a bit strange, it should be just `%`.
`help dumpheap`:
`gcheapstat` output:
> Fixed %% in sosdocs and gcheapstat output

- src/Tools/dotnet-counters/KnownData.cs
Committed bytes counter's unit was changed to MB via https://github.com/dotnet/runtime/pull/51031. All the counters whose units are different from the default value has units specified in their description (so that they show up when users run `dotnet-counters list`.
> Specify units in GC committed bytes counter description

- src/Microsoft.Diagnostics.Repl/Console/ConsoleProvider.cs
- src/Tools/dotnet-dump/Analyzer.cs
Fixes https://github.com/dotnet/diagnostics/issues/2169
With this change iif the console output is redirected
* `Console.CursorLeft` isn't set, as there is no handle which would crash the process
* REPL isn't started for `dump analyze`, just the given commands are executed
/cc: @mikem8361
> dotnet-dump analyze allows redirecting stdout

- diagnostics.sln
- eng/Version.Details.xml
- eng/Versions.props
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/inc/specialthreadinfo.h
- src/SOS/lldbplugin/services.cpp
- src/SOS/lldbplugin/services.h
- src/SOS/lldbplugin/setsostidcommand.cpp
- src/SOS/lldbplugin/sosplugin.h
Disable dotnet-dump tests; enable lldb tests on MacOS
Bump the SOS test runner time outs to 10min
'setsostid' with no parameters displays the thread info list.
> Use MacOS coredump special thread info

- src/SOS/Strike/gcroot.cpp
This fixes a couple of issues I found in the SOS support for regions.
1. In the case of regions, the `saved_sweep_ephemeral_seg` value will be `-1`, while it can never be the address of real segment, it doesn't hurt to do that extra check to make sure we are not doing the wrong thing in case the heap is corrupted.
2. When we translate `FindSegment`, the code is supposed to return `FALSE` if the address does not lie in the small object heap. The segment case is doing the right thing, but the regions' case is returning `TRUE` anyway.
The begs the question - why do we restrict to the small object heap only? - this leads to https://github.com/dotnet/diagnostics/issues/2199.
> A couple fixes for the SOS support for regions

- diagnostics.yml
Fixes #2059.
This leg only builds `Microsoft.Diagnostics.NetCore.Client` as it is the only prodcon asset in this repo. It does so in the default Linux container in a portable manner. 
Test internal run: https://dnceng.visualstudio.com/internal/_build/results?buildId=1120011
> Add sourcebuild leg

- src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
- src/Tools/dotnet-dump/Commands/ReadMemoryCommand.cs
Contributes to https://github.com/dotnet/diagnostics/issues/1460
Maybe it fixes that issue? I checked other places and they are written with https://github.com/dotnet/diagnostics/blob/c13a550fd8135e031678015743557ea2a543403f/src/Microsoft.Diagnostics.DebugServices/CommandBase.cs#L79 so work with and without the 0x prefix.
The remaining command was `readmemory` / `d`.
From the issue:
> cut and pasting addresses
This bit me...
/cc: @mikem8361
> dotnet-dump analyze allow hex-addresses with and w/o 0x prefix

- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
Test fails fairly regularly on Windows for each PR build. Disable for now while investigating cause. Issue already logged here: https://github.com/dotnet/diagnostics/issues/2234
> Skip logs pipeline test on Windows.

- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/Strike/strike.cpp
Right now it's a bit confusing that `dumpheap` displays size in decimal values, but `-min` and `-max` options must be given in hex values.
This PR adds `(hex)` to the info shown by `help dumpheap` so it's clear how to enter the desired byte-size range.
An alternative would be to allow `-min` / `-max` be entered as decimal values. But this would be a new behavior and kind of breaking change.
I have no strong opinion here, but at least there should be a hint if hex only is allowed (as I just wondered why it shows larger objects than wanted).
> Document that SOS dumpheap -min and -max must be in hex values

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/FormattedLogValues.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/IStateWithTimestamp.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/LogObject.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/LogValuesFormatter.cs
Some other design considerations:
- We could create an extended ILogger interface with a new Log<T> method that takes a timestamp. This seems to against the spirit of the established ILogger interface, as discussed at https://github.com/aspnet/Logging/issues/483#issuecomment-320558390
- We could attach additional data to the state object's IEnumerable implementation. This can potentially confuse clients (or cause issues in the formatters since there will be unexpected data), but it saves us from having to create an extra interface to understand the timestamp data.
- It's very unlikely any other ILogger implementation would leverage this; they would likely continue to create their own timestamps for example.
Addresses https://github.com/dotnet/dotnet-monitor/issues/21
Consumed by …
> Propagate timestamps for logger entries

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterRunner.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
Adds an additional router mode into dsrouter, server-client. In this router mode the front of router acts as an IPC server, where diagnostics tooling like dotnet-trace will connect, while backend acts as a TCP/IP client towards a runtime running a TCP/IP listener. 
This scenario could be beneficial if we can run on device TCP/IP listener (during development) and since it moves the TCP/IP listener over to a sandboxed app (normally accessed over a tunnelled usb connection), it will also reduce the need to open ports or bind to loopback interface on development machine.
In order to be more flexible in the architecture, this PR make some restructure of code in DiagnosticsServerRouterFactory moving over to a aggregation based architecture (instead of inheritance based) when constructing the …
> Add support for server-client mode in dsrouter.

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LogMessageType.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipelineSettings.cs
- src/tests/EventPipeTracee/Program.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.csproj
- src/tests/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.UnitTests.csproj
These changes allow for customized logs collection from a target process. Logs can be collected using:
- a default log level for all categories (`EventLogsPipelineSettings.LogLevel`)
- the application-defined categories and levels (`EventLogsPipelineSettings.UseAppFilters`)
- a custom mapping of categories and levels (`EventLogsPipelineSettings.FilterSpecs`)
This change adds the `FilterSpecs` property to the settings and allows all settings to be used in combination. It also adds logs tests to cover all combinations of usage of these settings.
These changes enable https://github.com/dotnet/dotnet-monitor/issues/54 for dotnet-monitor.
> Add FilterSpecs to EventLogsPipeline

- src/SOS/Strike/stressLogDump.cpp
- src/inc/sospriv.idl
- src/inc/stresslog.h
- src/pal/prebuilt/inc/sospriv.h
We would like to run tests with clrgc.dll activated and compiled with USE_REGIONS - as it turns out, the stresslog didn't yet work with the in-memory implementation of the stresslog. This PR has the changes required so we are actually able to dump this version of the stresslog as well.
> Make stresslog work for clrgc.dll, increment SOS_BREAKING_CHANGE_VERSION

- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventTracePipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/PipelineTestUtilities.cs
The pipeline unit tests quickly start and stop the pipeline which could allow for missed events. These changes allow the pipelines to run until the expected events have been observed and then stops the pipelines. A generous timeout is given for waiting for the events before the operation is canceled and fails the test.
This fixes the tests for counters and trace pipelines. I did not update the test for the logs pipeline (haven't seen this issue in that test), however I will do that in a subsequent change with some other modifications I'm making for that pipeline.
closes #2258
> Stop pipelines in tests after receiving expected events.

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
This fixes the EventLogsPipeline to throw PipelineException instead of NotSupportedException in the known case of when the default level was specified to be LogLevel.None. In general, pipelines should throw PipelineException for expected failures.
> Fix EventLogsPipeline to throw PipelineException when LoggingSourceConfiguration throws NotSupportedException

- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.Diagnostics.ExtensionCommands/ClrMDHelper.cs
- src/Microsoft.Diagnostics.ExtensionCommands/DumpGen.cs
- src/Microsoft.Diagnostics.ExtensionCommands/DumpGenCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/GCGeneration.cs
- src/SOS/SOS.UnitTests/Debuggees/DotnetDumpCommands/Program.cs
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/DumpGen.script
https://github.com/dotnet/diagnostics/pull/1816 introduced `dumpgen` command, https://github.com/microsoft/clrmd/pull/802 added support for the POH, so let's extend `dumpgen` to show the POH.
> Enabled POH in dotnet-dump dumpgen command

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Fix #2287. 
dotnet-trace can run into a NRE when it is launched in normal mode (i.e. not using the diagnostic port option) when the target process exits first, because it tries to `WaitForExit` on a ChildProc, which is null in that mode.
> Fix a NullRefException by finished process

- src/SOS/Strike/strike.cpp
- Depends on https://github.com/dotnet/runtime/pull/53471
- In the above change `ThreadCounts._data` was changed from `ulong` to `uint`. Its usage in SOS was reading 8 bytes and only using the lower 4 bytes. Updated to read 4 bytes instead. No functional change, just updated to match.
> Update `ThreadCounts` usage based on a change

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/TestStreamingLogger.cs
The RestServer assembly in https://github.com/dotnet/dotnet-monitor is being renamed to WebApi. Keep old IVTs until insertion is made into https://github.com/dotnet/dotnet-monitor
> Add IVT for Microsoft.Diagnostics.Monitoring.WebApi

- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Program.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Mono has option to push diagnostic server TCP/IP listener to device loopback interface. This opens up the ability to run dotnet-dsrouter in server-client mode, where diagnostic tooling connect using regular IPC server (using --process-id) and dsrouter will connect runtime as a TCP/IP client. Users/tooling use adb (on Android) or mlaunch (for all iOS devices), to do port forwarding/tcp tunnelling working in the same way on simulator/emulator as well as physical device connected over usb.
Another advantage of this configuration is security, since it opens up the ability and simplify working with loopback interface all the way over to device, meaning that dsrouter only acts as IPC server over namedpipes/unix domain sockets and as a TCP/IP client connecting 127.0.0.1:x (using port forwarding) …
> Add runtime resume option to dotnet-trace and dotnet-counters.

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterRunner.cs
- src/Tools/dotnet-dsrouter/ADBTcpClientRouterFactory.cs
- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
- src/Tools/dotnet-dsrouter/USBMuxTcpClientRouterFactory.cs
This PR together with https://github.com/dotnet/diagnostics/pull/2343 and https://github.com/dotnet/diagnostics/pull/2344 simplifies the diagnostics scenarios on Android/iOS simulator/devices. This PR adds support into dsrouter to setup/tear down adb port forwarding on Android matching configured dsrouter tcp client configuration and implementation of usbmux on iOS, setting up option to connect to iOS device over usb, using tcp client port configuration. All this pushes the listener all the way over to device using loopback interface together with dsrouter `server-client` mode, where dsrouter acts as a TCP/IP client, connecting towards 127.0.0.1:x for all scenarios (including runtime startup profiling).
Without this PR, Android scenario needs to manually setup adb port forwarding, and for …
> Add adb port forward and usbmux support to dsrouter.

- eng/build.sh
- eng/common/native/find-native-compiler.sh
- eng/gen-buildsys-clang.sh
TL;DR:
Version additions for LLVM/CLANG + fix typo. Should be low impact.
Overview:
`eng/build.sh`
- FreeBSD (and other BSD-like) return `amd64` for intel/amd 64bit from the `uname` command issued.
- I had to dig around on this one, but`$lowerI` appears to be left over from when some of the scripts were consolidated and a new function was made to lowercase things
`eng/common/native/find-native-compiler.sh`
- Add new cases for double digit compilers that don't use dot revision (e.g., 10, 11, 12)
- Added detection for the newer versions added in case
`eng/gen-buildsys-clang.sh`
- Same as second part of `find-native-compiler.sh`
Unnecessarily detailed stackexchange-like explanation: 
`uname` does not have many POSIX compliant options that can be passed to it. So trying to make the script use …
> Updates scripts for LLVM/Clang versions that are double digits

- src/SOS/Strike/util.h
Use a different way of recognizing a GC build using regions that works for SVR GC.
As it turns out, SOS didn't yet work for SVR GC because the DAC logic sets saved_sweep_ephemeral_seg to 0 always.
This may need fixing as well (see issue https://github.com/dotnet/runtime/issues/54368), but the simple change below at least enables SOS for SVR GC using regions.
> Fix SOS for SVR GC using regions

- src/Tools/Common/Commands/Utils.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Currently `dotnet-counters` returns zero upon error and 1 upon successful exit, which is confusing because `dotnet-trace` returns zero upon successful exit and nonzero upon error.
The standard practice for CLI tools is to return zero upon successful exit and nonzero upon error like `dotnet-trace` does, so `dotnet-counters` is breaking the rule here. 
This addresses the issue by sharing the `ErrorCodes` class between dotnet-counters and dotnet-trace and correcting the return code from `dotnet-counters`. 
Fix #2413
> Clean up error code used by dotnet-counters and dotnet-trace

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterRunner.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
- src/Tools/dotnet-dsrouter/USBMuxTcpClientRouterFactory.cs
Add last mode, client-client in dsrouter. With this mode dsrouter can now handle server-server, client-client, server-client and client-server, covering a wide range of configuration and deploy scenarios. This last mode also increase the security in dsrouter since it won't depend on any local IPC/TCP server in order to route traffic between remote runtime and local diagnostic tooling only acting as a IPC/TCP client.
> Add dsrouter client-client mode.

- compileoptions.cmake
- src/SOS/dbgutil/elfreader.cpp
- src/SOS/dbgutil/elfreader.h
- src/SOS/extensions/hostcoreclr.cpp
- src/SOS/lldbplugin/CMakeLists.txt
- src/pal/src/misc/sysinfo.cpp
- ifdef's for `__FreeBSD__` for missing sys/types.h and sys/sysctl.h where needed
- elfreader: link_map under Linux is different than FreeBSD 
- while we are here: add newer LLVM version paths for `LLDB_H` and disable, only for FreeBSD, two new warnings that LLVM10/11 use
> fix building native component for FreeBSD

- src/SOS/SOS.Hosting/CorDebugDataTargetWrapper.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/RuntimeWrapper.cs
The DataTargetWrapper (data target for DAC) and CorDebugDataTargetWrapper (data target for DBI) didn't increment the reference count initially. Normally this wasn't a problem because DAC/DBI don't release a reference except some debug/checked code in the DBI OpenVirtualProcess path that QI'ed for the data target interface and released as an assert.  The release would set the count back to zero which causes the wrappers to tear down the COM wrappers internals so when the next QI happened it failed. I don't know exactly why it seg faults because was running on Windows with the cross-DAC and got an assert in DBI instead.
> Fix clrstack -i crash

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
The fallback for the internal ResumeRuntime IPC command was erroring if it was used with a 3.1 runtime which doesn't support suspension. It should silently fail if the client receives an UnknownCommand error.
@hoyosjs can we get this merged in before we branch for release?
CC @lateralusX
> Fix fallback for resumeruntime

- src/SOS/Strike/strike.cpp
- Depends on https://github.com/dotnet/runtime/pull/56346
- Reverted commit 3d57bee719e6db6b19dce4026bdc7c47b1c3519b from PR https://github.com/dotnet/diagnostics/pull/2324 since the relevant change to `ThreadCounts` was reverted in https://github.com/dotnet/runtime/pull/56346
- No functional change from before, as only the lower 32 bits of the 64-bit value are used, just changing back to match the size of the field
> Revert "Update `ThreadCounts` usage based on a change (#2324)"

- src/SOS/Strike/strike.cpp
The new adjustment reason was added to the runtime in https://github.com/dotnet/runtime/pull/53471
> Add thread adjustment reason for cooperative blocking

- diagnostics.yml
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/Scripts/NestedExceptionTest.script
- src/SOS/SOS.UnitTests/Scripts/OtherCommands.script
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
Update alpine image that includes lldb python support
Enable lldb and dump tests (for 6.0) on Alpine
Don't run the bpmd portions of the tests on Alpine (see issue #2459)
> Update alpine image that includes lldb python support and enable tests on 6.0

- src/SOS/Strike/eeheap.cpp
This fixes a test failure for the SOS unit test named [GCTests](https://github.com/dotnet/diagnostics/blob/main/src/SOS/SOS.UnitTests/Scripts/GCTests.script) when the test is run under `USE_REGIONS`.
The problem is that `GCWhere` failed to locate a freshly allocated object because `heap_segment_allocated` is not updated yet.
@dotnet/gc
> We should check against alloc_allocated instead of heap_segment_allocated for ephemeral segment

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
This change removes IVTs for assemblies that no longer exist and adds a new one for dotnet-monitor to the Microsoft.Diagnostics.Monitoring.EventPipe assembly so that dotnet-monitor is not force to put all code that has internal dependencies into the Microsoft.Diagnostics.Monitoring.WebApi assembly.
Verified changes work with local build and test run in dotnet-monitor repository.
> Remove old IVTs and add new one for dotnet-monitor.

- src/Microsoft.Diagnostics.DebugServices.Implementation/ImageMappingMemoryService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/MetadataMappingMemoryService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleServiceFromDataReader.cs
- src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
Fixes some of the issues in https://github.com/dotnet/diagnostics/issues/2375
The problem is that the image mapping memory service didn't convert the rva from a
loaded layout calculated from the in-memory module to the file layout (the PEReader
with the downloaded image).
On Windows, images (native or managed) are always loaded layout so return false in
IModule.IsFileLayout without calling GetPEInfo() to avoid the recursion that broken
getting the info about coreclr.dll. It turns out that the heap dumps generated on
Windows don't have the image in-memory.
Don't get module version in GetPEInfo() to determine the layout. Cleanup.
Skip relocations that span cache blocks. This happens very rarely and should not affect
anything unless we get really really unlucky.
> Fix unknown type/methods in core dumps.

- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
Text was oddly shifting one character to the right during
updates. Fixed the off-by-one error in the update text
positioning.
> Fix dotnet-counters console alignment

- src/Microsoft.Diagnostics.ExtensionCommands/ClrMDHelper.cs
This is an incomplete fix for https://github.com/dotnet/diagnostics/issues/2451.
The extra check if the segment is `ephemeral_heap_segment` is bogus. CLRMD would guarantee the generation range have length 0 anyway.
https://github.com/microsoft/clrmd/blob/124b189a2519c4f13610c6bf94e516243647af2e/src/Microsoft.Diagnostics.Runtime/src/Builders/SegmentBuilder.cs#L47-L49
With this change, together with https://github.com/microsoft/clrmd/pull/945, I have got the unit test working locally for `USE_REGIONS`.
> Avoid checking for ephemeral heap segment in DumpGen

- src/Microsoft.Diagnostics.Monitoring.EventPipe/EventPipeStreamProvider.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcHeader.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcResponse.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/ProcessEnvironment.cs
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
- src/Microsoft.Diagnostics.NETCore.Client/StreamExtensions.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClientApiShim.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClientApiShimExtensions.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessEnvironmentTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessInfoTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
These changes add the ability to use async versions of the DiagnosticsClient methods as well as introduce cancellability.
The primary motivation for this change was to add cancellability so that diagnostic tools can cancel connections with runtime instances that are not behaving well (they are hung due to debugging, they are not responding to diagnostic requests in a timely manner, etc).
We've seen this type of issue appear when "dotnet run" is executed on a project but as a background process on Linux: https://github.com/dotnet/dotnet-monitor/issues/399. When dotnet-monitor attempts to send commands to the process via the diagnostics port, no response is produced by the target runtime instance; this causes all HTTP requests to hang when dotnet-monitor is running in 'connect' mode since …
> Refactor IPC communication to allow for async and cancellation.

- src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
Using the command dotnet-trace collect --diagnostic-port foo.sock, and pressing ctrl+C before the client connects used to leave a Unix Domain Socket file, this now cleans up the file to allow restart.
closes #2426
> In dotnet-trace/counters disposed of the server when we received ctrl+C while waiting for clients to connect. closes #2426

- src/SOS/SOS.UnitTests/Scripts/GCTests.script
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterTriggerTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
> Disabling EventLogsPipeUnitTests.TestLogsWildcardCategory and EventCounterTriggerTests.EventCounterTriggerWithEventPipePipelineTest

- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
Fallback using default ICP server port works for server-server mode in dsrouter, but was missing for server-client mode. PR adds same fallback into RunIpcServerTcpClientRouter, making sure default IPC server port gets setup, if no explicit IPC server port has been supplied using -ipcs argument.
> Fix default IPC port for IPC server, TCP client mode in dotnet-dsrouter.

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices.Implementation/ImageMappingMemoryService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
- src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
- src/Microsoft.Diagnostics.DebugServices/Microsoft.Diagnostics.DebugServices.csproj
- src/Microsoft.Diagnostics.ExtensionCommands/DumpConcurrentDictionaryCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/DumpGen.cs
- src/Microsoft.Diagnostics.Repl/Command/CommandProcessor.cs
- src/SOS/SOS.Hosting/SOSLibrary.cs
- src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/dbgengservices.cpp
- src/SOS/Strike/platform/cordebugdatatarget.h
- src/SOS/Strike/platform/datatarget.cpp
- src/SOS/Strike/util.h
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/tests/dotnet-counters/DotnetCounters.UnitTests.csproj
Load crash report json file and check some common values.
Enable Windows triage and heap dump testing
Check for ctrl-c on console writelines
Fix arm32/x86 sign extensions problems in C++ data targets
Fix dotnet-dump collect dump type and the exception display in commands
Fix eeversion command when private build version like 42.42.42.42424
Add the directory of the dump to the symbol search path
Remove "ChangeEngineState" message on every stop in windbg.
Fix module relocations fixes. It was using the wrong rva. Needed the original rva not the
translated file layout one.
Better SOS module load failure message.
> Enable crash dump report generation in SOS tests

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/DiagnosticPortsHelper.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessInfoTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/RemoteTestExecution.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
With https://github.com/dotnet/runtime/issues/54083 fixed, the DiagnosticsClient can now get additional information using the ProcessInfo2 command.
Overview of changes:
- Enable ProcessInfo2 in DiagnosticsClient.
- Update tests to reflect when entrypoint is available.
> Enable ProcessInfo2 in DiagnosticsClient.

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcServerTransport.cs
Running reverse connect (--diagnostic-port) against a runtime running with nosuspend, hangs/deadlocks IPC client and IPC server thread on start collect -> resume command sequence. Doing the same against a runtime using suspend will hang any trace session created after runtime has started up.
Happens since runtime IPC server thread will write out initial header data into session stream (when streaming is enabled) but client only waits for session id and will then issue a resume command. If the reverse server is not setup with any buffering this will cause IPC server thread to block when writing into session, runtime server thread won’t be able to handle incoming resume command, and client won’t read anything from session unblocking server thread, since its waiting on completion of resume …
> Fix reverse named pipe server start collect -> resume hang.

- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
Please see https://github.com/dotnet/diagnostics/issues/2541#issuecomment-927223626
> Disabling TestLogsAllCategoriesDefaultLevel on windows due to intermittent failures

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- Adds serialization for the type `Guid` when calling `SetStartupProfiler` on the diagnostic pipe
> Add Guid Serialization to Diagnostics Client

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/WriteDumpFlags.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
Uses new write dump command supported by 6.0 runtime to pass a set of flags instead
of just the logging enabled bool.
Issue: https://github.com/dotnet/diagnostics/issues/2698
> Add enable crash report flag to WriteDump client API

- src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ModuleServiceFromDataReader.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/TargetFromDataReader.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.Extensions/ModuleServiceFromDebuggerServices.cs
- src/SOS/SOS.Extensions/TargetFromFromDebuggerServices.cs
The exception in the service provider is caused by the recursion of the ImageMappingMemoryService memory
service. Remove the recursion by passing the "raw" memory service (the one without any "mapping" memory
service wrappers) to the module service to use to get the build id/PE reader, etc.
Fix Windows debugger SOS termination exception
> SOS crash fixes

- eng/native/build-commons.sh
1. idempotently generate version file.
2. allow double hyphen in args.
> Fix some workflow issues

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AggregateSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AspNetTriggerSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/EventPipeProviderSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/GCDumpSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MonitoringSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/SampleProfilerConfiguration.cs
Note that I wanted to accomplish the following:
- Although these types are not really a public API, I didn't want to make a breaking Api change
- Reasonable defaults for each particular configuration.
- The ability to further customize the property externally should it be necessary in the future.
> Better rundown defaults and parameterization

- src/SOS/SOS.Hosting/RuntimeWrapper.cs
- src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
- src/SOS/Strike/platform/runtimeimpl.cpp
- src/SOS/Strike/symbols.cpp
- src/tests/Microsoft.Diagnostics.DebugServices.UnitTests/TestDataReader.cs
Cleanup g_symbolStoreInitialized flag. DisplayStoreStore() wasn't displaying the symbol path set from the dbgeng .sympath change notification. Simplified the symbol service initialization logic.
Make DebugServices tests more reliable.
Always use diasymreader if no managed symbol service.
Actually flush the clrprocess/cordebug instances.
> Misc SOS fixes 

- src/SOS/lldbplugin/services.cpp
I've found that when a core dump is taken by the OS without the extra
settings that makes it copy shared libraries binaries into the dump,
SOS doesn't work as it relies on the libcoreclr.so ELF header to be
present.
I have discovered a way to make lldb read that data from the image of
the libcoreclr.so that it has loaded together with the dump.
This change makes it possible to use SOS even for the above mentioned
dump cases. In fact, it allows SOS to read any data that were mapped as
read only from any shared library loaded in the process.
> Enhance core dump debugging

- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/inc/crosscomp.h
This feature adds support for resolving byref fields via SOS. Used the [dotnet/runtime RefFields test](https://github.com/dotnet/runtime/tree/main/src/tests/Loader/classloader/RefFields) to validate. A design decision to retain the actual value was made in the display as opposed to resolving to the target and showing that in the pretty print.
There is a fair bit of whitespace change. Recommend using https://github.com/dotnet/diagnostics/pull/2829/files?diff=split&w=1 to view files.
Before:
```
0:000> !DumpVC 00007ff943c82c78 @rbp-10h
Name:        InvalidCSharp.WithRefField
MethodTable: 00007ff943c82c78
EEClass:     00007ff943c78938
Size:        24(0x18) bytes
File:        D:\runtime\artifacts\tests\coreclr\windows.x64.Release\Loader\classloader\RefFields\Validate\InvalidCSharp.dll
Fields: …
```
> Update SOS to resolve first level byref fields

- src/SOS/Strike/strike.cpp
The generated DML for the "Content" link of an array doesn't respect pointer size.
Review without whitespace changes - https://github.com/dotnet/diagnostics/pull/2832/files?diff=split&w=1
Before
```
0:000> !DumpObj /d 0000016088f63c78
Name:        System.Char[]
MethodTable: 00007ff95fd3a7e0
EEClass:     00007ff95fd3a720
Tracked Type: false
Size:        536(0x218) bytes
Array:       Rank 1, Number of elements 256, Type Char (Print Array)
Content:     ................................................................................................................................
Fields:
None
0:000> dw 88f63c88 L100
```
After
```
0:000> dw 16088f63c88 L100
```
/cc @mikem8361
> Fix the generated DML for Array contents.

- src/SOS/lldbplugin/services.cpp
This has been wrong since GetModuleBase was written but worked for the important modules like libcoreclr. It had problems when the actual module binary wasn't available for lldb to load for core dumps.
> Fix module base address calculation on lldb

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- Depends on https://github.com/dotnet/runtime/pull/64834
- Refactored the enumeration of the global queue and reused it to also enumerate the high-priority work item queue
- Omitted info that is specific to the native thread pool implementation, when the portable thread pool is being used for IO completions
> Update SOS for when the portable thread pool is used for IO completions on Windows

- src/SOS/Strike/util.cpp
- src/shared/pal/prebuilt/inc/sospriv.h
This is the SOS part for [this](https://github.com/dotnet/runtime/pull/66844), check that one out for more information.
Fixes #2929
> Fix heap walking with global allocation context

- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
Issue: https://github.com/dotnet/diagnostics/issues/2950
Changed to pinvoke directly to OpenProcess to get the process handle for MiniDumpWriteDump.
> Fix dotnet-dump collect on half exited process

- src/SOS/lldbplugin/soscommand.cpp
While investigating a macOS issue I noticed libsos exposed the export but lldb's plugin didn't see it. The command is quite useful while investigating several synchronization issues.
cc: @janvorli
> Add ThreadState to the set of allowed APIs in lldb

- src/Tools/dotnet-counters/CounterMonitor.cs
Want to talk with Windows folks about this behavior. For now, here is a patch that fixes #2970 and possibly #2934
> patch to fix dotnet-counters rendering issues

- src/Tools/Common/Commands/ProcessStatus.cs
Altered ProcessStatus.cs to create cleaner output. Fixes part of #2946 if IsOutputRedirected Console.WindowWidth throws an exception, removed that case.
> Fix rendering issues on dotnet-tool ps

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
When attempting to access Process.MainModule.Filename, if architectures are different between the app and dotnet-trace or if the app is running with admin privileges, a Win32Exception is thrown.  Fixes #2781
> Create clear error messages for dotnet-trace

- src/SOS/Strike/ExpressionNode.cpp
- src/SOS/Strike/disasm.cpp
- src/SOS/Strike/disasm.h
- src/SOS/Strike/disasmARM.cpp
- src/SOS/Strike/disasmARM64.cpp
- src/SOS/Strike/disasmX86.cpp
- src/SOS/Strike/eeheap.cpp
- src/SOS/Strike/gchist.cpp
- src/SOS/Strike/gcroot.cpp
- src/SOS/Strike/metadata.cpp
- src/SOS/Strike/platform/targetimpl.cpp
- src/SOS/Strike/sildasm.cpp
- src/SOS/Strike/sos.cpp
- src/SOS/Strike/sos.h
- src/SOS/Strike/stressLogDump.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/strike.h
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/SOS/Strike/vm.cpp
- src/SOS/extensions/config.h.in
- src/SOS/extensions/configure.cmake
- src/SOS/extensions/hostcoreclr.cpp
- src/shared/gcdump/gcinfodumper.cpp
- src/shared/gcdump/i386/gcdumpx86.cpp
- src/shared/minipal/getexepath.h
- src/shared/pal/src/include/pal/palinternal.h
- src/shared/pal/src/misc/errorstrings.cpp
- src/shared/pal/src/safecrt/input.inl
- src/shared/pal/src/synchmgr/wait.cpp
First commit: port https://github.com/dotnet/runtime/blob/f865423/src/native/minipal/getexepath.h, a self-dependent header, covers handful of corner cases to get executable path in a cross-platform manner. It is used throughout the runtime repo (clr, tests, corehost, mono and `Environment.ProcessPath` .NET API).
Second commit: use `ARRAY_SIZE` macro from the previously copied `minipal/utils.h` in more places and delete three redundant macros computing the same thing.
> Use minipal in more places

- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
dotnet-counters rendering had some issues because the code was using absolute coordinates in some functions, but viewport-relative coordinates in other functions to account for ansi escape codes. Unified the code to use viewport-relative coordinates.
> use viewport-relative coordinates

- src/SOS/Strike/eeheap.cpp
Without passing by reference, the committed size for the POH would not be counted as the total committed in `!eeheap`
> Pass by reference

- src/Microsoft.Diagnostics.DebugServices/MemoryServiceExtensions.cs
- src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
- src/dbgshim/dbgshim.cpp
- src/shared/pal/src/thread/process.cpp
- src/tests/DbgShim.UnitTests/DbgShimAPI.cs
- src/tests/DbgShim.UnitTests/DbgShimTests.cs
Fixed some dbgshim issues found with Samsung's netcoredbg managed debugger.
Fix some sign-extension issues on alpine arm32 in SOS. Found investigating https://github.com/dotnet/diagnostics/issues/3003.
Fix DbgShim.UnitTest's Microsoft.Diagnostics.DbgShimAPI+NativeRuntimeStartupCallbackDelegate being called after collected by the GC
> Misc dbgshim and SOS fixes

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcMessage.cs
- src/Tools/dotnet-dump/Dumper.Windows.cs
- src/Tools/dotnet-dump/Dumper.cs
Add the new generate core dump command that can receive error text on failure.
> Add error message to WriteDump response

- src/Microsoft.Diagnostics.DebugServices.Implementation/SymbolService.cs
- src/SOS/SOS.InstallHelper/InstallHelper.cs
- src/Tools/dotnet-dump/Analyzer.cs
The BCL API `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` (returns non-nullable and non-empty string) provides fallback in case environment variable, corresponding to platform-specific home directory, is not set. e.g. on Unix it fallback to `getpwuid_r` call and similarly on Windows it calls a similar Win32 API. Using this API aligns dotnet tools with other popular utilities like `git`, which do not give up in $HOME-less scenarios.
Prior art: https://github.com/dotnet/runtime/commit/cef245d28ae8d50f3bf0ad7adedc461cd45b085c and https://github.com/dotnet/sdk/commit/e0456aaf3d9df757b76af6f055eedcca3b51e4da
Second commit runs dotnet-format on the files changed in the first commit.
> Use Environment.GetFolderPath to obtain home directory

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- Depends on https://github.com/dotnet/runtime/pull/69386
- The PR above added new queues of work items. This change updates the `ThreadPool -wi` command to include showing work items from those new queues.
- Verified that the updated SOS works with and without the above PR
> Update SOS to show thread pool work items from new queues

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
- src/Tools/dotnet-dsrouter/dotnet-dsrouter.csproj
Source-build will automatically pickup the current source-built versions of Versions.props properties that follow the standard naming convention.  Picking up the latest Microsoft.Extensions.Logging causes other packages to be loaded which results in the following error:
```
.../7.0.0-preview.5.22266.11/buildTransitive/netcoreapp2.0/System.Diagnostics.DiagnosticSource.targets(4,5): error : System.Diagnostics.DiagnosticSource doesn't support netcoreapp3.1. Consider updating your TargetFramework to net6.0 or later. [.../Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj]
```
Using a pinned Microsoft.Extensions.Logging version will avoid this issue.
> Pin Microsoft.Extensions.Logging version to prevent source-build from picking up latest

- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
This was causing incorrect commands in
markup for WinDBG scenarios.
> DML formats array missing DML_Async entry

- src/Tools/dotnet-dump/Program.cs
> Add help for command flag of dotnet-dump

- src/Tools/dotnet-dsrouter/USBMuxTcpClientRouterFactory.cs
When receiving data from the other end in usbmux mode, we need to return any
data we get, not wait to fill the input buffer.
Otherwise any clients waiting for data will wait forever: in fact the initial
handshake would fail to complete, because we wouldn't pass along the 28-byte
success response because we were trying to fill the 1028-byte buffer with
data.
Also add some input validation to make sure we don't write data into random
memory + take the requested offset into account when writing data into the
output array.
> Fix usbmux to return any received data.

- src/Microsoft.Diagnostics.DebugServices.Implementation/SymbolService.cs
Issue: https://github.com/dotnet/symstore/issues/358
> Fix symweb URL in symbol service

- src/SOS/SOS.Extensions/DebuggerServices.cs
- src/SOS/SOS.Extensions/RemoteMemoryService.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/HostWrapper.cs
- src/SOS/SOS.Hosting/ServiceWrapper.cs
- src/SOS/SOS.Hosting/TargetWrapper.cs
> Change return value type from HResult to int to avoid crash on Linux x86

- src/SOS/Strike/Strike.vcxproj
- src/SOS/extensions/extensions.vcxproj
- src/dbgshim/dbgshim.vcxproj
- src/shared/dbgutil/dbgutil.vcxproj
- src/shared/gcdump/gcdump.vcxproj
- src/shared/utilcode/utilcode.vcxproj
Using the below syntax performs a complete replacement of warning codes which should be treated as errors.
```xml
<TreatSpecificWarningsAsErrors>aaaaa;bbbbb;ccccc;...</TreatSpecificWarningsAsErrors>
```
Instead, the following syntax should be used, which inherits the base list coming from the SDK (or a higher level props file) and augments the list with your desired warning codes.
```xml
<TreatSpecificWarningsAsErrors>$(TreatSpecificWarningsAsErrors);aaaaa;bbbbb;ccccc;...</TreatSpecificWarningsAsErrors>
```
> Exception: If you're intentionally trying to suppress the inherited list, please ignore this rule.
> Change WarningsAsErrors elements to inherit

- documentation/sos-debugging-extension.md
- src/SOS/SOS.Hosting/Commands/SOSCommand.cs
- src/SOS/Strike/sos_unixexports.src
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/Strike/strike.cpp
- src/SOS/lldbplugin/soscommand.cpp
I took this for a spin locally, and both `objsize` and `gchandles` worked for me.
```
(lldb) GCHandles
Handle Type                  Object     Size             Data Type
000000010BF91000 WeakShort   000000018CD97210      224                  Mono.Addins.Description.AddinDescription
000000010BF91008 WeakShort   000000018CD91300      224                  Mono.Addins.Description.AddinDescription
000000010BF91010 WeakShort   000000018CD90690      224                  Mono.Addins.Description.AddinDescription
000000010BF91018 WeakShort   000000018CD7FEB0      224                  Mono.Addins.Description.AddinDescription
000000010BF91020 WeakShort   000000018CD77948      224                  Mono.Addins.Description.AddinDescription
000000010BF91028 WeakShort   000000018CD6C960      224 …
```
> Add gchandles and objsize commands to lldb debugger extension

- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Exporters/CSVExporter.cs
- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
- src/Tools/dotnet-counters/Exporters/ICounterRenderer.cs
- src/Tools/dotnet-counters/Exporters/JSONExporter.cs
dotnet-counters currently adds new metrics and tags that it discovers to the console
UI but never removes anything, even if the data for those metrics/tags stops coming.
For gauges the lack of data is meaningful because the user code explicitly chose not
to provide a value when queried. This change removes metrics/tags from the UI if the
gauge in the monitored process stops sending data.
Fixes https://github.com/dotnet/runtime/issues/72099
> Remove stale gauges from dotnet-counters UI

- src/Tools/dotnet-sos/Program.cs
This aligns us better with the usage in `dotnet tool install`
> Allow dotnet-sos install parameter to use --arch

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/build.sh
- eng/common/cross/build-rootfs.sh
- eng/common/sdl/sdl.ps1
- eng/common/templates/job/execute-sdl.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/templates/steps/execute-codeql.yml
- eng/common/templates/steps/execute-sdl.yml
- global.json
- Bump Netwonsoft JSON used in test
- Move arcade to bar build ID: 143014
> Update Newtonsoft usage

- eng/Versions.props
- src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs
The TraceEvent versions here and in dotnet/runtime diverged. [Dotnet/Runtime is taking 3.0.3 ](https://github.com/dotnet/runtime/pull/71813) as it contains https://github.com/microsoft/perfview/pull/1658, necessary for RuntimeSku to show up as `Mono` in .mibc files instead of `4`.
Update Graph NodeCount type to long https://github.com/microsoft/perfview/pull/1486
> Align TraceEvent Version with dotnet/runtime

- src/SOS/Strike/strike.cpp
Context: https://github.com/dotnet/runtime/pull/71719#discussion_r943414900
> Update SOS for removal of unmanaged threadpool

- src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
In the current code of the ReversedDiagnosticsServer, if the server fails to bind to the provided address, the Start method succeeds and the SocketException is not observed until the server is disposed. This prevents any tool that uses the reverse server to not know that the binding failed until the server is shut down. See https://github.com/dotnet/dotnet-monitor/issues/2017#issuecomment-1162370671 for an example of this problem.
This change fixes this by binding the transport in the Start method, which will allow the caller to immediately observe the binding failure if it occurs.
cc @dotnet/dotnet-monitor
> Make ReversedDiagnosticsServer.Start method throw if address is in use

- eng/Version.Details.xml
- eng/Versions.props
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/Scripts/StackAndOtherTests.script
- src/SOS/SOS.UnitTests/Scripts/StackTests.script
- src/SOS/Strike/strike.cpp
- src/SOS/lldbplugin/services.cpp
Fixed lldb's ReadVirtual to support partial reads
Fixed the DumpRuntimeTypes command to build the GC heap info. It was looking up segments uninitialized.
Update dependencies from https://github.com/dotnet/installer build 20220819.24
Microsoft.Dotnet.Sdk.Internal
From Version 7.0.100-rc.1.22407.1 -> To Version 7.0.100-rc.2.22419.24
> Installer update and fixed lldb's ReadVirtual to support partial reads

- eng/build.yml
- eng/common/templates/job/source-build.yml
- eng/common/templates/job/source-index-stage1.yml
- eng/prepare-release.yml
This change is required to continue building PRs in the dotnet public repo.  The agents and images used in the new project / organization are identical and build regressions are not expected.
For questions / concerns, please stop by the .NET Core Engineering Services [First Responders Teams Channel](https://teams.microsoft.com/l/channel/19%3aafba3d1545dd45d7b79f34c1821f6055%40thread.skype/First%2520Responders?groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).
> Update public pool names

- diagnostics.yml
- documentation/building/linux-instructions.md
- documentation/lldb/centos7/build-install-lldb.sh
- documentation/lldb/fedora24/build-install-lldb.sh
- documentation/lldb/opensuse/build-install-lldb.sh
Reverts dotnet/diagnostics#3336
Sorry @am11, I didn't get to see your cross message for validation until after the merge was done and the official build broke (cross images seem to only have 3.6 installed in the crossroot?). Also, on debug ubuntu 22.04 seems to fail a lot of tests.
> Revert "Update Ubuntu 16.04 images"

- src/shared/palrt/bstr.cpp
This fixes the below compile error with clang-14
```cpp
/home/leee/dotnet/diagnostics/src/shared/palrt/bstr.cpp:50:13: error: use of bitwise '&' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
if (SUCCEEDED(ULongMult(cchSize, sizeof(WCHAR), &temp)) &
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&&
```
Related patch in runtime repo: https://github.com/dotnet/runtime/pull/72313
> Fix use of bitwise '&' with boolean operands in palrt

- src/dbgshim/dbgshim.cpp
- src/dbgshim/debugshim.cpp
- src/dbgshim/debugshim.h
Need to check for the architecture named CLRDEBUGINFO (i.e. "CLRDEBUGINFOCORESYSAMD64", etc.) resource in
coreclr.dll for the live debugging APIs.
> Fix debugging on UWP/.NET Core 1.0

- src/Microsoft.Diagnostics.DebugServices.Implementation/DiagnosticLoggingService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/FileLoggingConsoleService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/SymbolService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Tracer.cs
- src/Microsoft.Diagnostics.DebugServices/IConsoleFileLoggingService.cs
- src/Microsoft.Diagnostics.DebugServices/IDiagnosticLoggingService.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/ConsoleLoggingCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/LoggingCommand.cs
- src/Microsoft.Diagnostics.Repl/ConsoleService.cs
- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
- src/Microsoft.Diagnostics.TestHelpers/TestRunner.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/OtherCommands.script
- src/Tools/dotnet-dump/Analyzer.cs
Added "logopen" and "logclose" commands to control console file logging.
Added the IConsoleFileLoggingService and implementation to control the console file logging.
Issue: https://github.com/dotnet/diagnostics/issues/3095
Add internal diagnostic logging to a file also.
Added the IDiagnosticLoggingService and implementation to control internal diagnostic logging.
Move Tracer.cs to Microsoft.Diagnostics.DebugService.Implementation.
Add tests for logging commands
> Add console file logging

- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.UnitTests/Scripts/NestedExceptionTest.script
- src/SOS/SOS.UnitTests/Scripts/Reflection.script
- src/SOS/SOS.UnitTests/Scripts/TaskNestedException.script
- src/SOS/Strike/exts.cpp
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/Strike/strike.cpp
Issue: https://github.com/dotnet/diagnostics/issues/2978
> Fix SOS message context

- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
Fixes #3036.  If the console width was lowered while dotnet-counters was being run or the console was not wide enough, the output would not render correctly.:
This was fixed by keeping track of the console size and refreshing the output with a every new payload. If the console is not wide enough, the labels are truncated to make the output fit properly.: 
This was tested in powershell, Linux via WSL, and with consoles with widths as low as 20 units.
> Fixed dotnet-counters rendering issues

- src/Microsoft.Diagnostics.Repl/ConsoleService.cs
dotnet-dump analyze causes an Exception when a console returns `CursorTop` as -1.
```
[root@localhost tmp]# dotnet dump analyze core_19700108_100550 
Loading core dump: core_19700108_100550 ...
Ready to process analysis commands. Type 'help' to list available commands or 'help [command]' to get detailed help on a command.
Type 'quit' or 'exit' to exit the session.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
at System.Console.SetCursorPosition(Int32 left, Int32 top)
at System.Console.set_CursorLeft(Int32 value)
at …
```
> Check CursorTop before changing CursorLeft to prevent ArgumentOutOfRangeException

- diagnostics.yml
- src/dbgshim/pkg/microsoft.diagnostics.dbgshim.linux-musl-arm.proj
- src/sos-packaging.props
Issue: https://github.com/dotnet/diagnostics/issues/1552
> Add linux-musl-arm SOS support

- src/shared/dbgutil/elfreader.h
- src/shared/pal/src/init/pal.cpp
`src/shared/pal/src/init/pal.cpp` missing include was causing build failures
`src/shared/dbgutil/elfreader.h` this change was in past versions but got lost/reverted/missed when files got moved around
> FreeBSD fixes

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Microsoft.Diagnostics.Monitoring/Microsoft.Diagnostics.Monitoring.csproj
These libraries do not need to be versioned `5.0` and can version along with the other diagnostics libraries.
cc @dotnet/dotnet-monitor
> Unpin monitoring assembly versions

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AspNetTriggerSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/AspNet/AspNetTrigger.cs
- src/Microsoft.Diagnostics.TestHelpers/DotNetBuildDebuggeeTestStep.cs
This serves as a partial fix to an issue that caused AspNet* collection rules to no longer function after collecting a trace with the Http profile.
@jander-msft
> [Dotnet Monitor] Standardize DiagnosticFilterString, No Longer Assume TraceEvent Arg Ordering

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AspNetTriggerSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/AspNet/AspNetTrigger.cs
Revert TraceEvent version to 2.0.64 (#3473)
[Dotnet Monitor] Standardize DiagnosticFilterString, No Longer Assume TraceEvent Arg Ordering (#3425)
> Merge some main commits into release/stable

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
When running client-client mode in dotnet-dsrouter connects the backend tcp client against runtimes tcp server and then connects the front end ipc client towards reverse diagnostic server's ipc server (running in tools like dotnet-trace, dotnet-monitor). When both completes it will send advertise message to reverse diagnostic server and consider the router instance connected and ready for use. This works fine on tools that is rather short lived, like dotnet-trace, but for long running tools like dotnet-monitor this will lead to extensive connect/disconnect behaviors since reverse diagnostic server will ask for a new connection right away and dotnet-dsrouter is setup to handle parallel router instances and since runtime uses a TCP server in listen mode it will accept multiple parallel …
> Enhance client-client dotnet-dsrouter mode.

- src/SOS/SOS.UnitTests/Scripts/GCPOH.script
- src/SOS/SOS.UnitTests/Scripts/GCTests.script
- src/SOS/Strike/eeheap.cpp
In order to maintain the old format for backward compatibility, the presentation of `!eeheap` command contained questionable data that does not make sense for regions. 
In this change, I optimized the presentation of `!eeheap` for regions so that:
- It eliminated the `Generation starts at 0x...` lines, they don't apply for regions.
- It replaced the `Large (or pinned) object heaps starts at 0x...` with just `Large object heap`, the starting address also doesn't make sense for regions.
- It added a line `Small object heap` before the small object heap segments.
- It added the column headers for the pinned object heap.
- It includes the `Frozen object heap` section, it is optional (but very likely to be present in some heap for .NET 8+). If we don't have a frozen object heap it will not be …
> Optimize eeheap presentation for regions

- src/SOS/Strike/dbgengservices.cpp
- src/SOS/Strike/dbgengservices.h
- src/SOS/Strike/exts.cpp
- src/SOS/Strike/exts.h
- src/SOS/extensions/extensions.cpp
- src/SOS/extensions/extensions.h
This fixes breakpoint commands like `bm foo_function "k;!clrstack;g"`
/cc: @cshung
> Flush target state on breakpoint hit under dbgeng

- src/SOS/Strike/util.h
This change was used to test https://github.com/dotnet/runtime/pull/77328 so that we know the DAC changes there work.
We are not currently making any use of that flag yet, but it will be useful when we need to know if `BACKGROUND_GC` is defined, for example, for https://github.com/dotnet/diagnostics/issues/3482.
> BackgroundGC check

- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
https://github.com/dotnet/diagnostics/blob/bfed18c6bf6867fd70300ab7366e9fc6c18bbdbe/src/Tools/dotnet-dump/Dumper.cs#L85
```console
root:~> dotnet dump collect --type Triage -p 2750
Writing  to /root/core_19700109_050032
----------
root:~> dotnet dump collect --type Mini -p 2750
Writing dump to /root/core_19700109_061913
----------
root:~> dotnet dump collect --type Heap -p 2750
Writing dump with heap to /root/core_19700109_061949
```
> Added missing 'Triage' dump type option

- documentation/tutorial/src/triggerdump/Program.cs
- documentation/tutorial/src/triggerdump/triggerdump.csproj
- src/Tools/dotnet-trace/Extensions.cs
`dotnet build documentation/tutorial/src/triggerdump/triggerdump.csproj` was broken because RuntimeClient.csproj does not exist.
> Moderenize triggerdump in docs

- src/SOS/extensions/hostcoreclr.cpp
- src/shared/pal/src/thread/process.cpp
The buffer used for getline() function should be freed by user even if getline() failed.
> Fix memory leaks detected by static analyzer

- src/SOS/SOS.UnitTests/Scripts/OtherCommands.script
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
Example output:
```
0:000> !DumpMT /d 00007ffaeb7b88a0
EEClass:             00007ffaeb7ad6a0
Module:              00007ffaeb7b68f0
Name:                Program
mdToken:             0000000002000004
File:                ...\Hello\bin\Debug\net6.0\Hello.dll
AssemblyLoadContext: Default ALC - The managed instance of this context doesn't exist yet.
BaseSize:            0x18
ComponentSize:       0x0
DynamicStatics:      false
ContainsPointers:    false
Slots in VTable:     7
Number of IFaces in IFaceMap: 0
0:000> !DumpMT /d 00007ffaeb7cf360
EEClass:             00007ffaeb7d6518
Module:              00007ffaeb7c8318
Name:                Program
mdToken:             0000000002000004
File:                ...\Hello\bin\Debug\net6.0\Hello.dll
AssemblyLoadContext: 0x20ecb360
BaseSize: …
```
> Add the ALC to `DumpMT`

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/ICounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterTriggerTests.cs
These changes are the first part of addressing https://github.com/dotnet/dotnet-monitor/issues/430; the second part will be integrated directly into the `dotnet-monitor` repo.
> [Dotnet Monitor] Add Metadata Support For `CounterPayload`

- src/Tools/dotnet-dump/Dumper.cs
```
root:~> dotnet dump collect -p -1
Writing full to /root/core_19700105_070307
Process -1 not running compatible .NET runtime.
```
```
root:~> dotnet gcdump collect -p -1
The PID cannot be negative: -1
```
> Check if the process ID value is less than 0 in dotnet-dump

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterFilter.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/EventCounterPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/EventPipeCounterPipelineSettings.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/ICounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/ICountersLogger.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/EventCounter/EventCounterTrigger.cs
- src/Tools/dotnet-stack/ReportCommand.cs
This is still in development and going into a feature branch.
> [Dotnet Monitor] Ignore - Adding System.Diagnostics.Metrics Support

- src/dbgshim/dbgshim.cpp
- src/shared/dbgutil/elfreader.cpp
- src/shared/dbgutil/elfreader.h
- src/tests/DbgShim.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
Issue: https://github.com/dotnet/diagnostics/issues/3510
Add GetBuildIdFromSectionHeader that used when getting the build id note from the program headers failures.
> Fix dbgshim fails to decode libcoreclr.so headers from Snap install

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/EventCounterPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/ICountersLogger.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/EventCounter/EventCounterTrigger.cs
Note that this feature is in-progress and this PR is going into a feature branch.
@wiktork
> [Dotnet Monitor] Revert To Logging a single payload (not a list)

- src/Tools/dotnet-counters/CounterMonitor.cs
Changed parsing of event data to always use `InvariantCulture`.
Fixes #3542
> Change metrics parsing to use InvariantCulture

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
Switching from using "quantile=" to "Percentile=" for histograms.
> [Dotnet-Monitor] [Feature Branch] Switched quantile to Percentile

- eng/Versions.props
- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapInfo.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/GCHeapDump.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/Graph.cs
- src/Tools/dotnet-gcdump/DotNetHeapDump/MemoryGraph.cs
dotnet-gcdump broke when running on recent version of perfview, after investigation the root cause was that `Microsoft.Diagnostics.FastSerialization.SegmentedList` had its `Count` field changed from an int to a long.
In the `Graph.ToStream()` method we called `serializer.Write(m_nodes.Count)` which would now write a 64 bit value, and when the deserializer expected a 32 bit value the deserializer would be 32 bits off and everything appeared corrupted.
I went through all files that we keep copies of and took all the updates I could find, but that is the core one that fixes the issue.
> Port GCDump fixes from PerfView

- eng/build.sh
```build-commons.sh``` puts ```-DCLR_CMAKE_KEEP_NATIVE_SYMBOL=true``` to ```__CMakeArgs``` for ```keepnativesymbols``` option. Yet it is forgotten as ```build.sh``` doesn't use it.
https://github.com/dotnet/diagnostics/blob/000766177bb4dfc353029c23844f8e7931174c8d/eng/native/build-commons.sh#L339-L341
> Add missing '$__CMakeArgs' option in build.sh

- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
Adds the profile mentioned in https://github.com/dotnet/diagnostics/issues/3521 in order to include private gc events in the gc-collect profile. Can see this working by using the following sample application:
```
using System.Collections;
class ConsoleTest{
public static void Main(){
List<int> nums = new List<int> {};
Console.WriteLine("Currently Running");
while(true){
List<object> objects = new List<object>();
for (int i = 0; i < 100000; ++i)
{
objects.Add(new object());
}
objects.Clear();
}
}
}
```
and dotnet-trace to collect a trace:
```
dotnet-trace collect --profile gc-collect -n sampleapp
```
This results in the following events being generated, making note of the private gc events:
> Add new provider for gc-collect profile

- documentation/design-docs/ipc-protocol.md
I noticed an environment variable name in the IPC protocol doc was incorrect.
> Fix environment variable name

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPipelineSettings.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
Feedback for https://github.com/dotnet/diagnostics/pull/3587
> PR feedback

- src/Microsoft.Diagnostics.ExtensionCommands/DumpAsyncCommand.cs
- src/SOS/SOS.UnitTests/SOS.cs
- src/tests/DbgShim.UnitTests/DbgShimTests.cs
- src/tests/Microsoft.Diagnostics.DebugServices.UnitTests/DebugServicesTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterTriggerTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventTracePipelineUnitTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/EventPipeSessionTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessEnvironmentTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetProcessInfoTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/GetPublishedProcessesTests.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/ReversedServerTests.cs
- src/tests/dotnet-counters/JSONExporterTests.cs
- src/tests/dotnet-trace/ChildProcessTests.cs
Fixes the build errors when newer SDKs are installed or building under VS.
> Fix/disable nullable warnings treated as errors with newer SDKs installed

- eng/Versions.props
Escaping characters in the Chromium file was added in this [pr](https://github.com/microsoft/perfview/commit/3f06e493e1935c1846ccef6170469ca0c6cd5c00#diff-ce00bfa58a5fff2e9a08746a4e41803d6e66488f6e5483cad8adb4ea114ada1fR74). Version 3.7 contains this solution to resolve https://github.com/dotnet/diagnostics/issues/3607, just needed to bump the version of TraceEvent to have it properly convert nettrace files to Chromium.
> Updated version of TraceEvent to 3.0.7 in order to add escaped characters to Chromium files

- src/Tools/dotnet-counters/KnownData.cs
- src/Tools/dotnet-counters/Program.cs
Fixes https://github.com/dotnet/diagnostics/issues/3622. Bumps the default version to be 6.0 and adds profile support for up to 8.0.
> Update the default version of dotnet-counters to be 6.0

- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/StackFrame.cs
Fixes https://github.com/dotnet/performance/issues/2890 . I've opened it in dotnet/performance by mistake.
What this does:
When Type is ILGenerated it's methods do not have a name or signature. TypeName which is also null in such case was handled but MethodName and MethodSignature weren't. This improves handling of those values.
> StackFrame.cs null handling

- src/dbgshim/dbgshim.cpp
Remove check in dbgshim.cpp to ensure the file is less than 100 MB. This allows single file apps with larger sizes to be debugged under a managed debugger.
> Allow larger single file apps debugging in DbgShim

- src/Microsoft.Diagnostics.ExtensionCommands/ClrMemoryPointer.cs
- src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
I made a few improvements from using this on a couple of investigations.
We now print a warning when we notice that regions we know exist in memory are missing from IMemoryRegionService.  This shouldn't happen on Windows, but in ELF dumps we do not have a debug stream describing memory...we only use what was put into the coredump as the known memory regions.
We now split up VirtualAlloc regions when we go to tag CLR memory regions.  CLR might VirtualAlloc one big chunk and sub-divide it into its own regions.  Note that MAddress isn't actually trying to show VirtualAlloc/memmap addresses (just use !address for that), instead it's trying to take what !address knows and annotate more information.
Renamed "IMAGE" -> "Image" in output, because it better fits in with how we name other regions. …
> Missing memory improvements

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterFilter.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/MetricsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
Dotnet-monitor filters out any events if they do not match the requested interval. This change allows the filtering to be configured on a per provider basis.
> Enable per provider filtering

- eng/build.sh
Simple PR to fix native non-x64 builds.
This will place the bin folder for arm64/arm/x86 builds in the correct path.
> Fix propogating BuildArch.

- .devcontainer/devcontainer.json
- eng/build.sh
Updates it to work with the newer vs code releases, and in addition, adds --priviledged to allow debugging SOS under the devcontainer.
In addition, fixes typo in the last build pr.
Note: for arm64 macs, running x64 container images can be run with:
devcontainer.json:
`"runArgs": ["--platform=linux/amd64" ]`
and `FROM --platform=linux/amd64 `
in the dockerfile
> Small change to dev container setup.

- eng/build.sh
This reverts https://github.com/dotnet/diagnostics/pull/3684 to fix official builds
> Fix build target architecture passing

- src/Microsoft.Diagnostics.DebugServices.Implementation/Module.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Utilities.cs
- src/Microsoft.Diagnostics.DebugServices/IRuntime.cs
- src/SOS/SOS.Hosting/RuntimeWrapper.cs
Fallback to parsing the embeded version string for single-file apps if ClrInfo.Version is null or invalid.
> Fix the runtime version for single-file apps

- documentation/FAQ.md
- documentation/tutorial/app_running_slow_highcpu.md
- src/Microsoft.Diagnostics.TestHelpers/ProcessRunner.cs
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/sosdocsunix.txt
- src/SOS/lldbplugin.tests/testsos.sh
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/shared/inc/switches.h
- src/shared/pal/src/include/pal/dbgmsg.h
- src/shared/pal/src/map/virtual.cpp
- src/tests/EventPipeStress/Orchestrator/Program.cs
The configuration system in coreclr and mono started supporting `DOTNET_` prefix in net6.0. Using `DOTNET_` is preferred because [it has precedence](https://github.com/dotnet/runtime/blob/2876baf289e8e06fc1ec00cc2d22ea7f61b2634d/src/coreclr/inc/clrconfignocache.h#L75) over `COMPlus_`.
> Rename COMPlus_ to DOTNET_

- src/Tools/Common/Commands/Utils.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
Apply feedback. 
https://github.com/dotnet/diagnostics/pull/3635#issuecomment-1420001603
Now it looks like the below when `System.Console.SetCursorPosition(Int32 left, Int32 top)` throws exception.
```
[?1h=No profile or providers specified, defaulting to trace profile 'cpu-sampling'
Provider Name                           Keywords            Level               Enabled By
Microsoft-DotNETCore-SampleProfiler     0x0000F00000000000  Informational(4)    --profile
Microsoft-Windows-DotNETRuntime         0x00000014C14FCCBD  Informational(4)    --profile
Process        : /usr/bin/dotnet-launcher
Output File    : /tmp/dotnet-launcher_20230222_063808.nettrace
[6n[?25l[6n[6nRecording trace in progress. Press <Enter> or <Ctrl+C> to exit...
```
cc/ @gbalykov @noahfalk
> Handle exception in System.Console.SetCursorPosition in some environments

- src/Microsoft.Diagnostics.ExtensionCommands/EEHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/HeapWithFilters.cs
- src/Microsoft.Diagnostics.ExtensionCommands/TableOutput.cs
- src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
- !eeheap now only operates on the currently selected runtime (again)
- This feature request came from the GC team.  !eeheap can grow very long and unhelpful on larger dumps
- Added the same -segment, -heap, and [memory, range] arguments to !eeheap to filter the output down to the requested ranges, segments, or heaps.
- Loader/Modules heaps will also be filtered by "[memory, range]" (not not -heap and -segment).
- Added a few key DML entries to dump the heap in the given ranges.  (For example, if click on the segment address in !eeheap, it will run !dumpheap for just that segment, or just that heap, etc.)
- Changed "Total" to "Partial" whenever we filter the heap.  e.g. 'Total bytes consumed by CLR' -> 'Partial bytes consumed by CLR'.
> Add a way to filter !eeheap

- src/Microsoft.Diagnostics.ExtensionCommands/ExtensionMethodHelpers.cs
- src/Microsoft.Diagnostics.ExtensionCommands/FindEphemeralReferencesToLOHCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/FindReferencesToEphemeralCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Generation.cs
- src/Microsoft.Diagnostics.ExtensionCommands/SizeStatsCommand.cs
Added SOS commands requested by the GC team:
- **!sos FindEphemeralReferencesToLOH** - Finds references between gen0/gen1 objects and the Large Object Heap.
- **!sos FindReferencesToEphemeral** Finds all object references which point to a lower generation than the current object
- **!sos SizeStats** - Prints statistics about objects sizes
> Add GC inter-generational analysis commands

- src/Microsoft.Diagnostics.ExtensionCommands/FindPointersInCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/GCToNativeCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
- Using single '-' instead of '--' for Options to match the rest of SOS
- Change the default behavior of maddress to print the entire list of memory, this matches !address
- Only display the HandleTable if we can efficiently do so (or if the user requests that we show HandleTable data anyway)
- Use the RootCacheService to only walk the handle table once per runtime
> Improve !maddress

- src/Microsoft.Diagnostics.Repl/ConsoleService.cs
WriteDmlExec is meant to work even if DML is disabled, but the Repl project throws NotSupportedException instead of passing the text argument.
Fixes #3793.
> Fix issue where DmlExec isn't implemented in Repl

- src/Microsoft.Diagnostics.ExtensionCommands/MAddressCommand.cs
Added an option to order the output of !maddress by size descending, as requested by the GC team.
> Add maddress -orderBySize

- src/SOS/lldbplugin/soscommand.cpp
I think this is all of them.  I went back through things implemented in ExtensionCommands and updated them here.
> Change lldb behavior for new managed command implementations

- src/Tools/dotnet-dump/Dumper.Windows.cs
dotnet-dump will now retry 11 times then throw after the last attempt if `ERROR_PARTIAL_COPY` is returned by the `NativeMethods.MiniDumpWriteDump` API call.
Fixes issue #3829.
> dotnet-dump returns failure after exhausting retries on ERROR_PARTIAL_COPY

- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
This PR addresses two problems in dotnet-counters.  
1. When the console offset is greater than zero we incorrectly truncate counter row assignment and description output
2. When the console height is less than the total number of counters that can be shown, we can sometimes incorrectly assign row numbers to counters that should not be drawn.  This causes the values to be overwritten for different counter names.
Fixes #3665
> Fix incorrect rendering of counters

- src/Microsoft.Diagnostics.ExtensionCommands/TraverseHeapCommand.cs
Previous changes to !traverseheap did not properly set the encoding which ended up leaving a BOM in the middle of the output.
Fixes #3843.
> Remove BOM marker from the middle of !traversexml

- eng/build.sh
Copied blocks from https://github.com/dotnet/diagnostics/blob/90f96ce56246e1c379874bc6d243673d68b7af73/eng/common/native/init-compiler.sh#L46
it will help with https://github.com/dotnet/diagnostics/pull/3535#issuecomment-1522782582 (newer images will not have ancient lldb).
cc @mikem8361
> Improve lldb discovery for tests

- diagnostics.yml
- eng/build.yml
- eng/cibuild.sh
- src/SOS/SOS.UnitTests/SOSRunner.cs
Revives https://github.com/dotnet/diagnostics/pull/3337
Supersedes https://github.com/dotnet/diagnostics/pull/3492
> Update docker images to latest tags

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
This is an updated version of #3795 - values for `UpDownCounters` are now being published as of https://github.com/dotnet/runtime/pull/84846; this change consumes those events for dotnet-monitor and dotnet-counters. Goes along with https://github.com/dotnet/dotnet-monitor/pull/4310 in the dotnet-monitor repo.
@wiktork @noahfalk 
Closes https://github.com/dotnet/diagnostics/issues/3742
> Enable UpDownCounter For Dotnet-Counters and Dotnet-Monitor

- src/Tools/dotnet-stack/ReportCommand.cs
Fix parsing thread frames with names like: `Thread (4008) (.NET IO ThreadPool Worker)`.
> Fix parsing of thread names

- src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
Previous refactoring accidently eliminated the case where the CLR region perfectly overlapped the memory region.
> Fix issue with !sos maddress

- src/dbgshim/dbgshim.cpp
Fix implementation of RegisterForRuntimeStartupRemotePort and CreateCoreDbgRemotePort
> Call PUBLIC_CONTRACT to initialize PAL on Unix

- src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/GCRootCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/PathToCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/StaticVariableService.cs
Static variables can be opaque to the user when looking at !gcroot, since they show up as a pinned handle to an object array.  It's also difficult to distinguish things _other_ than static variables which follow the same pattern.  This change adds the static variable name to the output of !gcroot to help distinguish these differences.
- Remove "this will take a while" warning output from !dumpheap -short.
- Added StaticVariableService to resolve the address/objects of static variables.  This can be a relatively expensive operation, so it's important to cache the result.
- Updated GCRootCommand with the heuristic.
> Add static variable names to !gcroot

- src/Microsoft.Diagnostics.ExtensionCommands/Output/Formats.cs
Using `object value = (nint)1;  StringBuilder.Format("{0:x}", value);` fails to format the given value as hex, since `nint` and `nuint` do not have a `ToString(string format)` method.  This manifested as assert failures on x86 where we expected an 8 digit hex value, but got a longer integer (non-hex).  Both x86 and x64 were affected, but only x86 asserted.
> Fix issue with nint/nuint formatting

- src/Microsoft.Diagnostics.ExtensionCommands/DumpAsyncCommand.cs
> Update DumpAsync to allow method table and object address to not have 0x prefix

- src/SOS/Strike/util.cpp
- src/shared/inc/dacprivate.h
PGO introduces two new native code version types. The runtime already has this change, but SOS does not.
> Add PGO to DacpTieredVersionData

- src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeProvider.cs
Lee found in his investigations that ClrRuntime isn't being flushed in Runtime.Flush().  This may fix it.  The RuntimeService.Flush is called first (though there isn't any order guarantee) which disposes of all the Runtime instances (instead of flushing) which Runtime.Dispose removes/deregisters the OnFlushEvent handler so Runtime.Flush is never called.
If you followed that great, but it is confusing (and why there might be bugs).  The intent was to cleanup (flush), remove and dispose of Runtime instances on Flush so the RuntimeService re-creates them the next time a runtime service instance is requested. What got lost in one of my big changes was the "cleanup" flush part.
> Clean up IRuntime instance flushing

- diagnostics.yml
- eng/pipelines/pipeline-resources.yml
Enable testing against the Ubuntu 22.04 image that now contains the lldb python script fix in the internal build.
> Test against new Ubuntu 22.04 image

- src/Microsoft.Diagnostics.DebugServices.Implementation/DataReader.cs
The SOS DataReader impl given to clrmd didn't copy the thread context correctly.
A future PR will improve the IThread.GetThreadContext() interface method to reduce these kind of bugs.
> Fix gcroot test failures

- src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/HeapWithFilters.cs
- src/SOS/SOS.UnitTests/Scripts/GCPOH.script
- src/SOS/SOS.UnitTests/Scripts/GCTests.script
This is a very small change to address https://github.com/dotnet/diagnostics/issues/3963#issuecomment-1585505859
Few questions:
1) Should I add tests for this?
2) I've asked about GCGeneration custom type that is a clone of Generation "official" type in that issue. It is a part of dumpgen command which itself, after this change, kinda loses it's meaning. I think the way forward is just to either remove dumpgen command or leave it as a proxy for dumpheap.
> Add generation option to dumpheap command

- documentation/design-docs/ipc-protocol.md
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
These changes add a new command that provides the .NET runtime a path to a managed assembly that contains a startup hook. Issuing this command during diagnostic suspension would be similar to prepending the path to the `DOTNET_STARTUP_HOOKS` environment variable before launching the target process.
Corresponding runtime change: https://github.com/dotnet/runtime/pull/86813
cc @dotnet/dotnet-monitor
> ApplyStartupHook diagnostic IPC command

- src/Microsoft.Diagnostics.ExtensionCommands/Output/ColumnKind.cs
Added more columns so s_text is not initialized for something different than text and other columns are not formatted as text.
If that behavior is intentiaonal then please close.
> Fix Image/TypeName columns using s_text field.

- src/Microsoft.Diagnostics.ExtensionCommands/DumpExceptionsCommand.cs
Please look at this. Left some questions inside the code. Mainly about ux/printing stuff.
Should messages be printed in multiple rows just for convenience?
Or alternatively should message be printed in another row? It's not like a really long message can be shown anyway I guess. But at least more chars can be shown. This way StackTrace can be partially shown too.
0262a3816710    7ffc556d2da0     System.InvalidOperationException
Message: The Settings Storage This computer was corrupted upon loading from XML Settings Stor ... (more chars)?
StackTrace: little bit of stacktrace?
For tests should I somehow validate that all output lines except for header and the last "Total" one contain "Exception" is the name?
P.S. Look at screenshots below first
> Added dumpexceptions command

- .github/fabricbot.json
This introduces a few rules:
- Resolved issues will close within a day if no further feedback is received.
- All issues marked with "Needs: Author Feedback" will wait for 4 days for author responses to questions, after which they are marked as stale. After that, 3 days will be given before closing the issue. 
- Any issues that are closed as stale give a 30-day window after closing in which the issue will automatically reopen.
- Any issues that are closed for more than 30 days are locked.
- Any issue that's waiting for feedback and gets an author reply will be marked as "Needs: Attention :wave:" 
cc: @dotnet/dotnet-diag
> Update fabricbot.json to include issue maintenance rules

- diagnostics.yml
Enabling **BinSkim** scan over build artifacts in CI based on company requirements.
We are required to run SDL tools on official builds and implement automated bug filling for the tools output. Currently we are running SDL checks over the source code in the nightly builds, inline in the builds for some of the product repos and in the .NET staging pipeline, but to be compliant we need to also run BinSkim over the produced artifacts.
This PRs is enabling **BinSkim** checks in the `Run SDL tool job` of [dotnet-diagnostics](https://dev.azure.com/dnceng/internal/_build?definitionId=528).
More information is in the [Automate BinSkim runs over official builds issue](https://github.com/dotnet/arcade-services/issues/2647)
> Enable Binskim scan in CI builds

- eng/Version.Details.xml
- eng/Versions.props
Contributes to https://github.com/dotnet/source-build/issues/3551
Sourcelink dependency isn't needed anymore. Arcade uses sourcelink tooling that is included in .NET SDK 8.0 preview 6.
> Remove sourcelink dependency

- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
dotnet-dsrouter can be a little hard to configure for mobile use cases since it needs a number of arguments, both to setup its local IPC client|server and the corresponding TCP client|server and what arguments to use depends on what mobile platform and scenario the user runs.
There are currently a number of different scenarios described in different sources of documentation:
Runtime docs:
https://github.com/dotnet/runtime/blob/main/docs/design/mono/diagnostics-tracing.md
iOS SDK docs:
https://github.com/xamarin/xamarin-macios/wiki/Profiling
Android SDK docs:
https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/tracing.md
They all fall into a number of predefined scenarios and a number of "default" parameters that should be used.
This PR creates 4 new commands in …
> Add default iOS/Android commands to dotnet-dsrouter.

- src/dbgshim/dbgshim.cpp
- src/dbgshim/dbgshim.h
Now it's tested on all platforms: Windows, Linux and Mac, connecting to iOS and Android, devices and emulators.
> Adding more parameters to connect to mono runtime

- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.Diagnostics.ExtensionCommands/ThreadPoolCommand.cs
Uses the properties exposed in https://github.com/microsoft/clrmd/pull/1175 to show relevant Windows thread pool information if it's enabled
> Update SOS to show the relevant information for the !ThreadPool command when using the Windows thread pool

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
* Add support for -v none, suppressing all logging making dotnet-dsrouter quiet.
* Add support for --info option for new iOS/Android preconfig commands, outputs details on how to configure app and diagnostic tools to connect to current running dsrouter instance.
*  Improve error handling when failing to find or execute adb binary.
*  Specify and validate supported verbose logging levels.
> Improve dotnet-dsrouter log levels and info.

- src/SOS/Strike/sosdocs.txt
- src/SOS/Strike/sosdocsunix.txt
fixing some incorrect info for the explaination of the -allReady arg for the !fq cmd.
> fix doc for fq -allReady

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
This PR addresses an issue were certain log messages could be dropped:
- A log message with placeholders can have an entirely null state (e.g. `_logger.LogInformational("Test {A}", args: null)`). In this scenario, the event source args payload will only contain the original format string, not the null args. 
- The current code assumes all placeholders will exist in the event source args payload, which results in an exception being thrown and the log message being dropped.
The changes in this PR are only used by dotnet-monitor so there should be no/minimal impact to the rest of the repo.
(This is subset of https://github.com/dotnet/diagnostics/pull/4284)
cc @dotnet/dotnet-monitor @noahfalk
> Handle log messages with null state

- src/Microsoft.Diagnostics.ExtensionCommands/NativeAddressHelper.cs
More issues found by the GC team.  With this fix the output of !maddress now exactly lines of with GC data structures.
> Additional !maddress fixes

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/SystemDiagnosticsMetricsTrigger/SystemDiagnosticsMetricsTriggerImpl.cs
Small bug fix on the dotnet-monitor side from the unification work - we previously didn't create a payload for `BeginInstrumentReporting`, and thus only checked that a payload wasn't an error or the end of a counter. The code now leverages the newly-added `IsValuePublishedEvent` from the unification to only apply to the correct payloads.
> [Dotnet Monitor] Small Fix For SDM Triggers

- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
The use of automatic port forwarding on Android device used the same port as local and remote, that should be possible, but turns out there is some issue with `adb` around that configuration when running against a physical Android device (works when using port forwarding/reverse against Android emulator).
This PR change the port defaults and align to Xamarin Android documentation as well as using different ports for local and remove when using -`tcps` or -`tcpc` arguments together with `--forward-port android`.
When running using the "Android" connect profile, `dotnet-dsrouter android` we will default to 9001 as local/host and 9000 as remote/device port.
When running with -`tcps` or -`tcpc` we will use passed port as local/host port and then set the remote/device port to local/host port - …
> Fix dotnet-dsrouter Android port reverse local/remote ports.

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/EventLogsPipelineSettings.cs
- src/tests/EventPipeTracee/Program.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventLogsPipelineUnitTests.cs
This PR reworks how log scopes are reconstructed. The current implementation has a several issues that results in it only working in single-threaded contexts. Once multiple threads are involved, scopes will be incorrectly associated to log messages in addition to scopes being deleted early while they are still active.
I've described how the new approach works in the source code so it doesn't get lost after this PR is merged. I've also left a comment with a visual representation of edge cases with concurrent traces.
/cc @dotnet/dotnet-monitor
> Fix log scope construction

- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
The ModuleLoadUnload events ModuleID is typed as a uint64 in the EventPipe manifest and emitted as a uint64 in the event payload. However, the parsing logic in ModuleLoadUnloadTraceDataevent in trace event:
https://github.com/microsoft/perfview/blob/a6c87911fe1aef8f59c9ce54aa4e16a1be6db91e/src/TraceEvent/Parsers/ClrEtwAll.cs.base#L4963
handles it as a long. Android devices running arm64 can use pointer tagging meaning that high bits can be set in 64-bit addresses and since module id is a memory address, it will be returned as a negative long from ModuleLoadUnload event and since all diagnostic tooling is build with overflow checking enabled by default, casting it to a ulong will trigger and overflow exception when high bit is set.
Fix is to do an unchecked cast in this case since the …
> Fix ModuleLoadUnloadTraceData.ModuleID cast to be unchecked since its really a ulong member.

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSessionConfiguration.cs
Session id is a uint64 in runtime as well as specified as a uint64 in IPC protocol, https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#returns-as-an-ipc-message-payload.
EventPipeSession.cs however handled it as a long instead of an ulong, currently that doesn't affect release builds since it doesn't do much with the id except passing it back to stop the session, but in debug builds there is an assert that validates that session id > 0. On Android physical devices it is not uncommon to get code and memory allocated at high addresses, including having the high order bit set and when that happens, EventPipeSession.cs will see a negative session id and assert on debug builds.
Fix adjust session id as ulong inline with IPC protocol, it also makes sure …
> Handle sessionId as ulong instead of long in EventPipeSession.cs.

- src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
!dumpheap and !verifyheap used to warn you that the GC Heap was not walkable.  That error was lost when I converted the code from C++ to C#.
Added a way to override the error so that it doesn't become blocking when we still want to validate or dump the parts of the heap that we can.
> Restore error message when the heap isn't walkable

- src/Microsoft.Diagnostics.DebugServices.Implementation/ThreadService.cs
- src/SOS/SOS.Extensions/TargetFromFromDebuggerServices.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/DbgEng/Interop/Enums/ImageFileMachine.cs
- src/SOS/SOS.Hosting/SOSHost.cs
- src/SOS/Strike/CMakeLists.txt
- src/SOS/Strike/disasm.cpp
- src/SOS/Strike/disasm.h
- src/SOS/Strike/disasmRISCV64.cpp
- src/SOS/Strike/exts.cpp
- src/SOS/Strike/exts.h
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.h
- src/shared/gcdump/gcdumpnonx86.cpp
- src/shared/gcdump/gcinfodecoder.cpp
- src/shared/gcdump/gcinfodumper.cpp
- src/shared/inc/gcinfodecoder.h
Changes:
- add partial SOS 'clrstack' command implementation;
- add more RISC-V related code (some still not tested or NYI, but need for proper SOS build);
This changes allow start and use dotnet-dump+SOS with current runtime upstream on RISC-V board:
```
mkurinnoi@starfive:~$ ./dotnet/corerun ./tools/dotnet-dump.dll ps                                           
221935  corerun  /home/mkurinnoi/dotnet/corerun  ./dotnet/corerun ./test_hr.dll  
mkurinnoi@starfive:~$ ./dotnet/corerun ./tools/dotnet-dump.dll collect --process-id 221935
Writing full to /home/mkurinnoi/core_20231024_104410
Complete
mkurinnoi@starfive:~$ ./dotnet/corerun ./tools/dotnet-dump.dll analyze /home/mkurinnoi/core_20231024_104410 
Loading core dump: /home/mkurinnoi/core_20231024_104410 ...
Ready to process analysis …
```
> [RISC-V] Add partial SOS 'clrstack' command implementation.

- src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
- src/Microsoft.Diagnostics.ExtensionCommands/DumpHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/EEHeapCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/HeapWithFilters.cs
- src/Microsoft.Diagnostics.ExtensionCommands/VerifyHeapCommand.cs
Update extension command parsing to allow a single \` in the middle of addresses.  We allow "\`0123" because the user might have copied the \` marker in "0000\`0123".  This makes commands more consistent since the C++ based SOS commands allow for \` in the addresses.
Updated a location where we didn't use TryParseAddress but should have.
Feature request from the GC team.
> Allow ` in hex strings

- src/Microsoft.Diagnostics.Monitoring.EventPipe/EventMonitor.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.csproj
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/dotnet-trace.csproj
Fixes https://github.com/dotnet/diagnostics/issues/3125
This PR provides users another method to stop a dotnet-trace via a stopping event similar to that of dotnet-monitor, originally implemented in https://github.com/dotnet/dotnet-monitor/pull/2557. 
Three arguments are added to the `dotnet-trace collect` command to specify a stopping event:
| Argument | Description |
|----------|----------|
|`--stopping-event-provider-name` | A string, parsed as-is, that will stop the trace upon hitting an event with the matching provider name. For a more specific stopping event, additionally provide `--stopping-event-event-name` and/or `--stopping-event-payload-filter`. |
| `--stopping-event-event-name` | A string, parsed as-is, that will stop the trace upon hitting an event with the matching event …
> [tools][trace] Add stopping event options to dotnet-trace

- src/Tools/dotnet-counters/Exporters/JSONExporter.cs
In dotnet-counters JSON Exporter, change time formatting to universal time formatting. Fixes #3905
> Universal Time formatting

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
This allows user code to pass a cancellation token without wrapping the call to StartEventPipeSession() in Task.Run() or similar. Resolves #3727.
> Make DiagnosticsClient.StartEventPipeSessionAsync public

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSessionConfiguration.cs
validate that providers are > 0 otherwise START Failed 0x80131384 get…s thrown and it's not clear what the issue is.
The current behavior when an empty list of providers is provided is to throw START Failed 0x80131384 (BadEncoding) and that doesn't make it very clear about what the issue is. This PR proposes validating the number of providers so developers  know that they should be providing 1 provider at least.
Before:
After:
> validate that providers are > 0 to provide clear error when using Diagnostics Client

- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/ParallelStack.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacksCommand.cs
This adds "-r" flag to include Runtime stacks to pstacks output
It will still ignore the frame if it's method is null. It's just a matter of checking for both Runtime and Managed kinds
Sometimes it might be useful to have those too, for example like in https://github.com/dotnet/diagnostics/issues/4418 when it is still useful to know which threads are in locked state
> An additional flag to parallel stacks to include runtime stacks to pstacks command

- src/tests/dotnet-counters/ConsoleExporterTests.cs
It looks like #4324 hadn't run a build in a while, and was checked in without validating against the new tests in https://github.com/dotnet/diagnostics/pull/4376 (causing the builds in main to fail). I don't believe there are any other issues, but this should give us a fresh build to confirm that.
> Update `ConsoleExporterTests` To Use Updated `RatePayload`

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/MetricsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/MetricsPipelineSettings.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Exporters/ConsoleWriter.cs
- src/Tools/dotnet-counters/Program.cs
- src/tests/dotnet-counters/CSVExporterTests.cs
- src/tests/dotnet-counters/ConsoleExporterTests.cs
- src/tests/dotnet-counters/JSONExporterTests.cs
- src/tests/dotnet-counters/MockConsole.cs
Fixes #3751
Previously we always showed counter instruments as a rate, but
for a variety of counters that isn't the most useful value. Now
we are showing the absolute value as long as the target process
is running .NET 8. For cases where it was useful to see rate of change
there is now a --showDeltas option which enables a 2nd column
of output for dotnet-counters monitor. The deltas show the difference
between the previous value and the current value. Making the new
column optional rather than a default setting is intended to minimize
consuming horizontal line space which is already at a premium. When
using csv or json outputs it is assumed the user's tool that processes
the data later can compute the rate if desired so there is no special
delta handling added for those.
Take a look at …
> Counter instruments display absolute values now in dotnet-counters

- .github/fabricbot.json
With the pending migration away from FabricBot to the Policy Service bot, the `noActivitySince` event condition will no longer be supported. This PR removes the only occurrence of that condition in this repository's configuration, as the condition was redundant with other automation anyway.
The condition was used in an idle issue management task such that:
* A comment was made on a closed issue by the issue's author and the issue has the label of `Needs: Author Feedback`
* Filtered to the condition of "NOT noActivitySince 30 days ago", thus there _has_ been other activity within 30 days (this event does not count as activity)
* Reopen the issue, remove the `Needs: Author Feedback` and `Status: No Recent Activity` labels, and add the `Needs: Attention 👋` label
This condition of ensuring …
> [FabricBot] Remove usage of 'noActivitySince' operand condition

- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
- src/Tools/dotnet-trace/Profile.cs
and have gc-collect not collect them.
dotnet trace right now always collects rundown events but they are not needed in some scenarios, eg, the gc-collect profile. it's much preferred to not include these unnecessary events which could take up way more space than the GC events.
> added an option to collect rundown events

- eng/Version.Details.xml
- eng/Versions.props
The changes in this pull request aim to [improve the UX and guideance around the SourceBuild metadata](https://github.com/dotnet/source-build/issues/3373) by placing the metadata on explicit source-build intermediates.
The changes include:
- Removing existing SourceBuild metadata from all non-intermediate dependencies.
- Defining new explicit intermediate dependencies and adding SourceBuild metadata to those dependencies.
Related to https://github.com/dotnet/source-build/issues/3373 and https://github.com/dotnet/source-build/issues/4073
> Move SB metadata to intermediates

- .github/fabricbot.json
This updates the FabricBot configuration to address issues we've seen migrating other repositories to the Policy Service automation. There are no behavioral changes.
> Prepare the FabricBot config for migration to Policy Service

- diagnostics.sln
- src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeService.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Target.cs
- src/Microsoft.Diagnostics.DebugServices/CommandBase.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/ClrDebugResource.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/ClrEngineMetrics.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/CommandExtensions.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/CommandFormatHelpers.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/HelpCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/ModulesCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimeInfo.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/SpecialDiagInfoHeader.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/StatusCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/ThreadsCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Output/ArrayExtensions.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/tests/Microsoft.Diagnostics.DebugServices.UnitTests/WriteTestData.cs
Added some new options and display the various special runtime exports and data structures to help diagnose common SOS and managed debugging failures.
The runtimes, sosstatus and modules -v commands now displays the special module exports g_dacTable, g_CLREngineMetrics, DotNetRuntimeInfo (single-file info), DotNetRuntimeDebugHeader (Native AOT data contract).
The "modules -r" or "!sos modules -r" now displays the module's resources and displays CLRDEBUGINFO in a readable format.
Use Microsoft.FileFormat to read the various in-memory structs like SpecialDiagInfoHeader, RuntimeInfo, ClrEngineMetrics, etc. by adding a Microsoft.FileFormat Reader instance to the target services.
> Add some diag info options to host commands

- src/Microsoft.Diagnostics.ExtensionCommands/DumpHttpRequestsCommand.cs
- src/SOS/Strike/managedcommands.cpp
- src/SOS/Strike/sos.def
- src/SOS/Strike/sos_unixexports.src
- src/SOS/lldbplugin/soscommand.cpp
Hello everyone, I created a simple extension to dump out all active incoming http requests.
I'm also planning to add time spent column but need help in getting the dump time stamp. Any idea which api to use?
> added new command to dump all active incoming http requests

- src/Microsoft.Diagnostics.DebugServices.Implementation/CommandService.cs
- src/Microsoft.Diagnostics.DebugServices/DiagnosticsException.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ClrMDHelper.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.Hosting/SOSLibrary.cs
- src/SOS/Strike/exts.cpp
- src/SOS/Strike/managedcommands.cpp
- src/SOS/Strike/util.cpp
- src/SOS/extensions/hostcoreclr.cpp
- src/SOS/extensions/hostdesktop.cpp
- src/SOS/inc/hostservices.h
- src/SOS/lldbplugin/services.cpp
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-dump/Commands/SOSCommand.cs
- src/tests/Microsoft.Diagnostics.DebugServices.UnitTests/CommandServiceTests.cs
Add command not found error message when managed hosting fails for managed only commands.
Removed displaying ClassLoader address in !dumpassembly command.
Better SOS hosting error messages.
> Fix/clean up command service 'command not found' paths.

- src/Microsoft.Diagnostics.ExtensionCommands/DumpHttpCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/DumpRequestsCommand.cs
- src/SOS/Strike/managedcommands.cpp
- src/SOS/Strike/sos.def
- src/SOS/lldbplugin/soscommand.cpp
Add a new command mentioned in https://github.com/dotnet/diagnostics/issues/536#issuecomment-1521192550
Options:
```
> help dumphttp
dumphttp:
Displays information about HTTP requests
Usage:
> dumphttp [options]
Options:
--stats                      Summarize all HTTP requests found rather than showing detailed info.
--pending                    Show only requests without response
--completed                  Show only requests with response
--uri <uri>                  Show only requests with with specified request uri
--statuscode <statuscode>    Show only requests with with specified response status code
Examples:
Summarize all http requests:                                dumphttp --stats
Show only completed http requests:                          dumphttp --completed
Show failed …
```
> feat: dumphttp command initial implementation

- diagnostics.yml
- eng/pipelines/pipeline-resources.yml
This is a more pragmatic approach as proposed earlier. Use the old Alpine version for build and the new one for testing.
We can move to cross-build images when .NET 6 goes EOL.
> Update Alpine versions

- src/SOS/Strike/metadata.cpp
- src/SOS/Strike/sildasm.cpp
- src/SOS/Strike/sos.cpp
- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/SOS/Strike/util.h
- src/shared/inc/dacprivate.h
- src/shared/pal/src/include/pal/palinternal.h
This change fixes build on recent Alpine Linux where the NULL is defined as std::nullptr instead of the former 0.
I've hit the problem when trying to build it on Alpine arm32, but I believe all architectures would be affected the same way.
> Fix recent Alpine repo build

- src/Tools/dotnet-trace/Extensions.cs
A useful event to debug thread starvations. Introduced there https://github.com/dotnet/runtime/pull/94737 for .NET 9.
> Add waithandle to --clrevents option

- documentation/design-docs/ipc-protocol.md
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AggregateSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/AspNetTriggerSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/EventPipeProviderSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/GCDumpSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/GcCollectConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/HttpRequestSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/LoggingSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MetricSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/MonitoringSourceConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/RetryStrategies.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Configuration/SampleProfilerConfiguration.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/EventPipeStreamProvider.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSessionConfiguration.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsIpc/IpcCommands.cs
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/CommandLine/Commands/ListProfilesCommandHandler.cs
- src/Tools/dotnet-trace/Profile.cs
- src/Tools/dotnet-trace/RetryStrategies.cs
- src/tests/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClientApiShim.cs
This change supports collecting GCSettingsEvent for gc-collect profile. The change will work for both dotnet-trace and dotnet-monitor.
The depends on the underlying mechanism built in https://github.com/dotnet/runtime/pull/101189
> Supports collecting GCSettingsEvent for gc-collect profile

- src/Microsoft.Diagnostics.DebugServices.Implementation/SymbolService.cs
- src/Microsoft.Diagnostics.DebugServices/ISymbolService.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/SetSymbolServerCommand.cs
- src/Microsoft.Diagnostics.TestHelpers/TestHost/TestDump.cs
- src/Microsoft.SymbolStore/SymbolStores/SymwebSymbolStore.cs
- src/SOS/SOS.Hosting/SymbolServiceWrapper.cs
- src/Tools/dotnet-dump/Analyzer.cs
- src/Tools/dotnet-symbol/Program.cs
- src/Tools/dotnet-symbol/Properties/Resources.Designer.cs
- src/Tools/dotnet-symbol/Properties/Resources.resx
- src/Tools/dotnet-symbol/README.md
- src/tests/DbgShim.UnitTests/LibraryProviderWrapper.cs
- src/tests/Microsoft.Diagnostics.DebugServices.UnitTests/SymbolServiceTests.cs
- src/tests/Microsoft.SymbolStore.UnitTests/SymbolStoreTests.cs
Removes the dotnet-symbol --internal-server option. Use the --authenticated-server-path option instead.
Removes the internal server/symweb options from the setsymbolserver command and ISymbolService interface.
> Remove the symweb symbol server support

- src/shared/gcdump/gcinfodumper.cpp
Port commits from `runtime` upstream:
https://github.com/dotnet/runtime/commit/3c5123ebf0cd6ec2c722a7881b08ee8c5ba28ee4 (partial, that not in `diagnostics` upstream yet)
https://github.com/dotnet/runtime/commit/a39a2643ae2abbb4b57291639bdafd0eb95f6e70
This code changes tested with `gcinfo` SOS command.
Test output for riscv64 with this changes:
```
> gcinfo 0000003f206fe840
entry point 0000003F2063B8B8
Normal JIT generated code
GC info 0000003F2073C840
Pointer table:
Prolog size: 0
Security object: <none>
GS cookie: <none>
PSPSym: caller.sp-8
Generics inst context: <none>
PSP slot: caller.sp-8
GenericInst slot: <none>
Varargs: 0
Frame pointer: fp
Has tailcalls: 0
Size of parameter area: 0
Return Kind: Scalar
Code size: 1e0
Untracked: +fp+50 +fp+48 +fp+40 +fp+38 +fp+30 +fp+28 +fp+20 +fp+18 …
```
> [RISC-V] Add gcinfodumper implementation.

- src/Microsoft.Diagnostics.ExtensionCommands/PathToCommand.cs
Fix `pathto` SOS command arguments parsing logic.
Current status:
```
> pathto 0x1234
ERROR: Could not parse argument 'source': 4660
> pathto 0x4444
ERROR: Could not parse argument 'source': 17476
```
With this changes:
```
> pathto 0x003f1d1182d8
ERROR: Could not parse argument 'target': 0
> pathto 0x003f1d1182d8 0x003f1d1182d8
ERROR: Object reference not set to an instance of an object.
> pathto 0x003f1d1182d8 0x003b7180bfc0
Could not find a path from 3f1d1182d8 to 3b7180bfc0
```
CC @clamp03 @wscho77 @HJLeee @gbalykov
> Fix `pathto` SOS command.

- src/SOS/Strike/strike.cpp
To eliminate global spinlock in stack trace saving to exceptions, the format of the stack trace storage has changed. The `_stackTrace` array can now be either a `byte[]` with the actual stack trace as before or an `object[]` where the first element references the byte[] with the actual stack trace and the following elements contain references to `System.Resolver` or `System.Reflection.LoaderAllocator` instances that keep code of methods that can be collected alive.
This change modifies SOS to handle the `object[]` case properly, while staying compatible with the old way. Since the same code to get the stack trace was duplicated at two places, I have taken this opportunity to refactor it into a separate function.
> Add support for new exception trace storage format

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.cpp
- src/Tools/dotnet-dump/Analyzer.cs
* Change DAC breaking change behavior from warning to error.
* Better dotnet-dump analyze error message for cross OS dumps.  Don't allow Linux and Windows dumps when running on MacOS; don't allow OSX and Windows dumps when running on Linux.
> Change SOS breaking change from warning to error; better dotnet-dump target errors

- src/shared/inc/sospriv.idl
- src/shared/pal/prebuilt/inc/sospriv.h
> Update SOS breaking change version for Exception's _stackTrace changes in .NET 9

- src/Microsoft.SymbolManifestGenerator/Microsoft.SymbolManifestGenerator.csproj
- src/Microsoft.SymbolManifestGenerator/SymbolManifestGenerator.cs
- Change signature of `GenerateManifest` to return success or failure and take a parameter requesting manifest generation to consider only special indexes for files collocated to runtime modules.
- Improved detection of layouts we can't handle: multiple runtimes where special files can't be unambiguously correlated.
- Improved logging on error cases.
> Add collocation option by default for manifest generation and improve error detection and logging

- src/SOS/lldbplugin/services.cpp
- src/shared/inc/regdisp.h
cc @viewizard @gbalykov
```sh
docker run --rm -v$(pwd):/diagnostics -w /diagnostics --platform linux/riscv64 alpine:edge sh -c \
'apk add build-base cmake bash curl clang llvm-dev   &&   ./build.sh -skipmanaged'
```
> Fix build on alpine-riscv64

- src/Tools/dotnet-trace/CommandLine/PrintReportHelper.cs
Before:
```
> dotnet-trace report dotnet_tracing_20240802_082746.nettrace topN -n 10
[ERROR] System.OverflowException: Arithmetic operation resulted in an overflow.
at Microsoft.Diagnostics.Tools.Trace.CommandLine.PrintReportHelper.TopNWriteToStdOut(List`1 nodesToReport, Boolean isInclusive, Boolean isVerbose) in /_/src/Tools/dotnet-trace/CommandLine/PrintReportHelper.cs:line 99
at Microsoft.Diagnostics.Tools.Trace.ReportCommandHandler.TopNReport(CancellationToken ct, IConsole console, String traceFile, Int32 number, Boolean inclusive, Boolean verbose) in /_/src/Tools/dotnet-trace/CommandLine/Commands/ReportCommand.cs:line 93
```
After:
```
> /home/gukov/diagnostics/artifacts/bin/dotnet-trace/Debug/net6.0/dotnet-trace report dotnet_tracing_20240802_082746.nettrace topN -n 10 -v
[WARNING] …
```
> dotnet-trace: don't fail if the trace file has no method calls

- src/Microsoft.FileFormats/PDB/IMSFFile.cs
- src/Microsoft.FileFormats/PDB/MSFFile.cs
- src/Microsoft.FileFormats/PDB/MSFZFile.cs
- src/Microsoft.FileFormats/PDB/PDBFile.cs
- src/tests/Microsoft.FileFormats.UnitTests/PDB/Tests.cs
This is a follow-on to my previous PR, #4868 . This allows users of the `PDBFile` class to query for the "kind" of the container that a given PDB file uses.  Normal (uncompressed) PDBs use a container format called "MSF".  Compressed PDBs use a container format called "MSFZ".
This adds two properties to `PDBFile`.  The `ContainerKind` property returns an enum which allows the caller to distinguish between MSF, and MSFZ. This also allows for new container formats (as yet unspecified) in the future.  However, the `ContainerKind` enum intentionally does not distinguish between the version of the container.  For that, the `ContainerKindSpecString` returns a string which contains a textual identifier ("msf" vs. "msfz") and for MSFZ, a version number.  For now, the only version number defined …
> Provide info about PDB container type (MSF vs. MSFZ)

- src/Microsoft.Diagnostics.ExtensionCommands/ParallelStacks.Runtime/RendererHelpers.cs
Sometimes a stack can be shared in a way where some thread's top frame is the current frame but there are still frames/threads present in the stack
In this case print the unique thread ids in the current stack frame. Otherwise this information is lost:
```
~~ Thread_T1 - unique thread id(s) for the current frame, this thread id is not currently displayed
~~ Thread_T2
1 Next_Stack_Frame
2 Current_Stack_Frame - this is actually a top frame for thread T1
```
Another way would be printing in a slightly different order but it will chop stack a little:
```
~~ Thread_T2
1 Next_Stack_Frame
~~ Thread_T1
2 Current_Stack_Frame
```
> A small fix to preserve thread ids when parallel stack is shared

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices.Implementation/Microsoft.Diagnostics.DebugServices.Implementation.csproj
- src/Microsoft.Diagnostics.DebugServices.Implementation/SymbolService.cs
- src/Microsoft.Diagnostics.DebugServices/ISymbolService.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/SetSymbolServerCommand.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
- src/Microsoft.SymbolStore/Microsoft.SymbolStore.csproj
- src/Microsoft.SymbolStore/SymbolStores/HttpSymbolStore.cs
- src/Tools/dotnet-symbol/Program.cs
- src/Tools/dotnet-symbol/dotnet-symbol.csproj
Add back -mi (add symweb symbol server), -nocache and -interface options to setsymbolserver command.
Add back --internal-server support to dotnet-symbol.
Clean up the HttpSymbolStore.cs - fix HttpResponse not being properly disposed. Removed the separate authenticated client instance/var.
Fix dotnet-symbol for some heap dumps. Some didn't have coreclr.dll's debug directory contents. Catch error and continue downloading files.
> Add cloud symweb support

- src/SOS/Strike/strike.cpp
- src/SOS/Strike/util.h
.NET 9 adds a new GC handle type which is used in the collectible assemblies implementation. This PR adds support for it.
> Add support for weak interior pointer GC handles

- src/Microsoft.SymbolManifestGenerator/SymbolManifestGenerator.cs
Bumping the DebugInformationLevel to be preferred over the default
> [Symbol] Increase DebugInformationLevel for manifest entries

- src/Microsoft.Diagnostics.ExtensionCommands/LiveObjectService.cs
I have a dump with GiB size, and has more than 200M objects, and encountered arithmetic overflow when run `dumpheap -live -stat`.
> Fix arithmetic overflow when memory dump has too many objects.

- src/SOS/Strike/sos.def
- Sets `DumpLocks` as an alias for `dumplocks`
- Alternatively, `DumpLocks` could be made the main command and `dumplocks` an alias
> Update alias for `dumplocks` command

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/tests/EventPipeTracee/DuplicateNameMetrics.cs
- src/tests/EventPipeTracee/EventPipeTracee.csproj
- src/tests/EventPipeTracee/Program.cs
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/EventCounterPipelineUnitTests.cs
In .NET 8.0 we added tags on Meters and Instruments but MetricsEventSource only included the names when emitting value publishing events. This made it ambiguous when there was more than one Meter or Instrument with the same name. In 9.0 MetricsEventSource started included InstrumentIDs in the BeginInstrumentReporting events and in the value publishing events that provides a stronger correlation identifier. This change consumes the IDs in those events within Microsoft.Diagnostics.Monitoring.EventPipe, allowing dotnet-counters (and presumably dotnet-monitor too) to track time series that differ only by the tags provided to the Meter/Instrument constructors.
I also re-enabled a disabled test that got broken when .NET 9.0 added the System.Runtime Meter.
Fixes #4843, #4564
> Metric name disambiguation

- documentation/FAQ.md
@mikem8361 Does this apply to just the M1? Or is it relevant to all MacOS arm64 machines?
> Nit documentation fix

- NuGet.config
- eng/Versions.props
- eng/pipelines/templateInternal.yml
- eng/release/DiagnosticsReleaseTool/DiagnosticsManifestGenerator.cs
- eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseCommandLine.cs
- eng/release/DiagnosticsReleaseTool/DiagnosticsReleaseTool.csproj
- eng/release/DiagnosticsReleaseTool/DiagnosticsRepoHelpers.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Microsoft.Diagnostics.DebugServices.Implementation.csproj
- src/SOS/SOS.UnitTests/Debuggees/SymbolTestApp/SymbolTestApp/SymbolTestApp.csproj
- src/SOS/Strike/clrma/thread.cpp
- src/Tools/dotnet-dump/dotnet-dump.csproj
- src/Tools/dotnet-symbol/dotnet-symbol.csproj
- Turn on nuget audit
- Enable TSA
- Fix audit issues and retarget release tool
> Enable TSA, nuget auditing, and necessary cleanup

- src/SOS/SOS.Extensions/MemoryServiceFromDebuggerServices.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
Improve support for LoongArch64 . Fix the issue where m_pLegacyTarget ->GetPointerSize (&ulPointerSize) cannot retrieve values and add testing support.@shushanhf
> [LoongArch64] Improve support for LoongArch64

- src/SOS/Strike/eeheap.cpp
```sh
$ ./build.sh
...
[ 97%] Building CXX object src/SOS/Strike/CMakeFiles/sos.dir/platform/hostimpl.cpp.o
/foo77/diagnostics/src/SOS/Strike/eeheap.cpp:439:11: error: cannot initialize a variable of type 'DWORD' (aka 'unsigned int') with an rvalue of type 'std::nullptr_t'
DWORD Value = NULL;
^       ~~~~
```
> Fix alpine-arm64 build

- src/shared/debug/dbgutil/dbgutil.cpp
This changes resource  iteration in `GetNextLevelResourceEntryRVA` to explicitly cast a potential overflow. It's safe since it will just not iterate any resources.
> Update resource iteration

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/EventPipeSession.cs
- src/Tools/dotnet-stack/ReportCommand.cs
Fixes https://github.com/dotnet/diagnostics/issues/4826
When running dotnet-stack against an unresponsive target process, there were various points where dotnet-stack wouldn't correctly cancel when Ctrl-C was pressed. There were several underlying issues:
- Cancellation caused EventPipeSession.Dispose() to run which attempted to send a Stop IPC command that might block indefinitely
- Several of the async operations dotnet-stack performed did not pass a cancellation token and so ignore when Ctrl-C is pressed
- The calls to start and stop the session were still using the synchronous API which both ignored the cancellation token and create the standard async-over-sync issues.
The change in behavior for EventPipeSession.Dispose() is strictly speaking a breaking change, although callers would …
> Improve cancellation handling for dotnet-stack

- src/Microsoft.Diagnostics.ExtensionCommands/DumpRequestsCommand.cs
Fixed an issue with the `!dumprequests` command that was causing an error when reading dumps from a Kestrel host.
```
0:000> !dumprequests
Field 'Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream<Microsoft.AspNetCore.Hosting.HostingApplication+Context>.<Method>k__BackingField' is not of type 'string'.
```
In Kestrel host dumps, the `<Method>k__BackingField` field in the `HttpContext` object is of `Enum` type, whereas in IIS host dumps, it is of `String` type. To address this, the `_methodText` field in the `HttpContext` object is now read if the `<Method>k__BackingField` field is not of `String` type.
Also added min width for each column for better readability.
> Fix error in dump requests command

- src/Microsoft.Diagnostics.DebugServices.Implementation/DataReader.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Thread.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/ThreadService.cs
- src/Microsoft.Diagnostics.DebugServices/IThread.cs
- src/Microsoft.Diagnostics.DebugServices/IThreadService.cs
- src/Microsoft.Diagnostics.DebugServices/IThreadUnwindService.cs
- src/Microsoft.Diagnostics.DebugServices/ThreadExtensions.cs
- src/SOS/SOS.Extensions/DebuggerServices.cs
- src/SOS/SOS.Extensions/ThreadUnwindServiceFromDebuggerServices.cs
- src/SOS/SOS.Hosting/CorDebugDataTargetWrapper.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/LLDBServices.cs
- src/SOS/SOS.Hosting/SOSHost.cs
Change GetThreadContext to return an ReadOnlySpan because the original API allowed the array returned to be changed. Fixed a couple of other APIs to that a ReadOnlySpan.
Added some common GetThreadContext extensions
> Clean up thread and thread service interfaces

- src/Microsoft.Diagnostics.DebugServices.Implementation/ServiceManager.cs
- src/Microsoft.Diagnostics.DebugServices/IServiceManager.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/StatusCommand.cs
Add loaded extension version display to !sosstatus
Example:
```
Extensions loaded:
-> 8.0.0-dev.24525.1+64eecc7e689a42bf979dd1339e90cd92a9843021 c:\diagnostics\artifacts\bin\Windows_NT.x64.Debug\Microsoft.Diagnostics.ExtensionCommands.dll 
-> 8.0.552406+f5de0a8ffe15b5aa596a8089c5d6a1c9472ac54b c:\diagnostics\artifacts\bin\Windows_NT.x64.Debug\extensions\Microsoft.Diagnostics.DataContractReader.dll
-> 8.0.552406+f5de0a8ffe15b5aa596a8089c5d6a1c9472ac54b c:\diagnostics\artifacts\bin\Windows_NT.x64.Debug\extensions\Microsoft.Diagnostics.DataContractReader.Extension.dll
-> 8.0.552406+f5de0a8ffe15b5aa596a8089c5d6a1c9472ac54b c:\diagnostics\artifacts\bin\Windows_NT.x64.Debug\extensions\Microsoft.Diagnostics.DebuggerCommands.dll
```
> Add extension loaded service manager property

- eng/Versions.props
- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
- src/tests/EventPipeStress/Orchestrator/Orchestrator.csproj
- src/tests/Grape/Grape.csproj
- src/tests/Microsoft.Diagnostics.Monitoring.EventPipe/Microsoft.Diagnostics.Monitoring.EventPipe.UnitTests.csproj
The referenced Microsoft.Diagnostics.Tracing.TraceEvent package version is fairly old and newer versions have bug fixes and other feature updates.
Another motivation to update this reference is that downstream consumers of the Microsoft.Diagnostics.NETCore.Client library cannot transitively update the Microsoft.Diagnostics.Tracing.TraceEvent version. Starting with the 3.1.14 release, the Microsoft.Diagnostics.Tracing.TraceEvent assembly itself has a dependency on Microsoft.Diagnostics.NETCore.Client. Projects that prerelease versions of Microsoft.Diagnostics.NETCore.Client are blocked from updating to the latest version of Microsoft.Diagnostics.Tracing.TraceEvent because the prerelease version of Microsoft.Diagnostics.NETCore.Client is a lower version (e.g. 0.2.0-preview.24564.1) than the …
> Update Microsoft.Diagnostics.Tracing.TraceEvent version

- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
This change ensures that newer builds of the Microsoft.Diagnostics.NETCore.Client package have a higher version than previously built versions. This change has no effect on released version as this library already adopts the lack of prerelease label in the `release/stable` branch; it effectively only changes the non-release builds to align the versioning scheme to be the same as the release build (always increasing, no prerelease versions). This is the same behavior that the other `dotnet-*` tools have in this repository.
Fixes #5085
> Remove prerelease label from Microsoft.Diagnostics.NETCore.Client

- documentation/symbols/SSQP_Key_Conventions.md
These conventions are used by Microsoft Edge to obtain source maps from Symbol Server. They don't need to be matched precisely but are useful.
> Add JavaScript and WASM symbols conventions

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClientConnector.cs
Followup of #5070 that introduced a non-viable approach (Comment https://github.com/dotnet/diagnostics/pull/5070#discussion_r1866519860)
This PR adds `DiagnosticsClientConnector` that is `IAsyncDisposable` and offers the method `FromDiagnosticPort`.
> Add DiagnosticsClientConnector to support creating a DiagnosticsClient from a diagnostic port

- eng/Versions.props
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.556
> Bump `StyleCop.Analyzers` to `1.2.0-beta.556`

- src/Tools/dotnet-counters/dotnet-counters.csproj
- src/Tools/dotnet-dsrouter/dotnet-dsrouter.csproj
- src/Tools/dotnet-dump/dotnet-dump.csproj
- src/Tools/dotnet-gcdump/dotnet-gcdump.csproj
- src/Tools/dotnet-sos/dotnet-sos.csproj
- src/Tools/dotnet-stack/dotnet-stack.csproj
- src/Tools/dotnet-symbol/dotnet-symbol.csproj
- src/Tools/dotnet-trace/dotnet-trace.csproj
Fixes issue: #5254
Invariant Globalization removes a dependency on libicu which allows the dotnet-* tools to run in a wider variety of environments.
PTAL: @dotnet/dotnet-diag
> Enable InvariantGlobalization

- eng/Versions.props
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterMetadata.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/CounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/ICounterPayload.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/DotnetCountersCounterPayloadExtensions.cs
- src/tests/EventPipeTracee/CustomMetrics.cs
- src/tests/EventPipeTracee/EventPipeTracee.csproj
- src/tests/EventPipeTracee/Program.cs
- src/tests/dotnet-counters/CSVExporterTests.cs
- src/tests/dotnet-counters/ConsoleExporterTests.cs
- src/tests/dotnet-counters/CounterMonitorPayloadTests.cs
- src/tests/dotnet-counters/JSONExporterTests.cs
- src/tests/dotnet-counters/TestConstants.cs
This PR expands the metrics artifacts to support OpenTelemetry.
To see how this will be used, I did a proof-of-concept. The final work will change somewhat, but this should explain the changes.
* Listener is here: https://github.com/CodeBlanch/dotnet-monitor/blob/b84ba9229f5996d99f934ef862008c138d294b0e/src/Tools/dotnet-monitor/OpenTelemetry/OpenTelemetryService.cs#L374
* MetricsStore gains an OTel-style snapshot which understands how to do proper delta aggregation using some of these changes: https://github.com/CodeBlanch/dotnet-monitor/blob/b84ba9229f5996d99f934ef862008c138d294b0e/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs#L161-L178
* The aggregated data is exported periodically as a "metrics producer" in the OTel world: …
> Update metrics to support OpenTelemetry specification

- eng/Versions.props
- eng/pipelines/prepare-release.yml
- eng/release/Scripts/AcquireBuild.ps1
- src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeProvider.cs
- src/Microsoft.Diagnostics.DebugServices/ISettingsService.cs
- src/Microsoft.Diagnostics.ExtensionCommands/ClrRuntimeCommandBase.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
- src/Microsoft.Diagnostics.TestHelpers/RemoteExecutorHelper.cs
- src/Microsoft.Diagnostics.TestHelpers/TestHost/TestDump.cs
- src/SOS/SOS.Extensions/DebuggerServices.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.Hosting/RuntimeWrapper.cs
- src/SOS/SOS.UnitTests/ConfigFiles/Unix/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/ConfigFiles/Windows/Debugger.Tests.Config.txt
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/Strike/clrma/managedanalysis.cpp
- src/SOS/Strike/dbgengservices.cpp
- src/SOS/Strike/dbgengservices.h
- src/SOS/Strike/platform/runtimeimpl.cpp
- src/SOS/inc/debuggerservices.h
- src/SOS/lldbplugin/services.cpp
- src/SOS/lldbplugin/services.h
- src/Tools/dotnet-dump/Analyzer.cs
- src/inc/releaseholder.h
- **Merged PR 47050: Use WIF connection for release management**
- **Fix runtime lifetime issues on error path in SOS**
- **Merged PR 47053: Add auth call to release**
- **Merged PR 47050: Use WIF connection for release management Code cleanup and configuration update. This pull request updates the release management process to use WIF (Workload Identity Federation) connection. - Modified `prepare-release.yml` to remove SAS token generation steps and update Azure subscription. - Updated `AcquireBuild.ps1` to remove SAS suffixes parameter and use Azure credentials for blob access.**
> Merge release changes into main

- src/Tools/dotnet-counters/CounterMonitor.cs
- src/Tools/dotnet-counters/Program.cs
- src/tests/dotnet-counters/CounterMonitorPayloadTests.cs
- src/tests/dotnet-counters/CounterMonitorTests.cs
We've had --counters for a while, and handling two argument lists (one for counter_list,
and the other one for the launch params) is pretty gnarly with the new version of system.commandline
as https://github.com/dotnet/command-line-api/commit/4b605851d45131db2374ba711f2443040521d702 dropped the
flag that enabled this parsing mode.
Since dotnet/diagnostics#1770 we've said that the option was hidden, and we'd eventually deprecate it.
This commit removes the counter_list argument from dotnet-counters and we assume that all arguments are
for the launch params.
Fixes https://github.com/dotnet/diagnostics/issues/5317
> Remove counter_list support from dotnet-counters

- src/Microsoft.Diagnostics.NETCore.Client/Microsoft.Diagnostics.NETCore.Client.csproj
- src/Tools/dotnet-dump/Dumper.cs
- src/Tools/dotnet-dump/Program.cs
> Add a diagnostic port option to dotnet-dump

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsClient/DiagnosticsClient.cs
The PR #3918 introduced `ApplyStartupHook`. This PR is making the API public.
It seems that the only client of this API today is dotnet-monitor [here](https://github.com/dotnet/dotnet-monitor/blob/ef3b48791edc90be54297155ccfb092aed71581b/src/Tools/dotnet-monitor/StartupHook/StartupHookApplicator.cs#L73-L85)
This API is particularly useful for loading assemblies in the target process that could add additional capabilities in what is being traced.
cc: @jander-msft
> Make DiagnosticsClient.ApplyStartupHook public

- src/SOS/Strike/util.cpp
Update the display of `ThreadStatic` values.
Before
```
00007ff95fe14b10  4000008       10        System.Object  0 TLstatic  MyStatic
>> Thread:Value 8274:0000027e5dccb088 8b68:0000027e5dcc3008 9db4:0000027e5dcc9068 7bf8:0000027e5dcc5028 2d6c:0000027e5dcd0fe8 9818:0000027e5dccf0c8 9104:0000027e5dcc7048 6680:0000027e5dccd0a8 313c:0000027e5dcd3008 9f78:0000027e5dcd5028 <<
```
After
```
00007ff95fe14b10  4000008       10        System.Object  0 TLstatic  MyStatic
Thread static values (Thread:Value)
8274:0000027e5dccb088
8b68:0000027e5dcc3008
9db4:0000027e5dcc9068
7bf8:0000027e5dcc5028
2d6c:0000027e5dcd0fe8
9818:0000027e5dccf0c8
9104:0000027e5dcc7048
6680:0000027e5dccd0a8
313c:0000027e5dcd3008
9f78:0000027e5dcd5028
```
> Update thread statics format

- eng/InstallRuntimes.proj
- eng/build.ps1
- eng/testsoscdac.cmd
- eng/testsoscdac.sh
- src/Microsoft.Diagnostics.TestHelpers/TestConfiguration.cs
- src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
- src/SOS/SOS.UnitTests/SOS.cs
- src/SOS/SOS.UnitTests/SOSRunner.cs
- src/SOS/SOS.UnitTests/Scripts/StackTraceFaultingExceptionFrame.script
- src/SOS/SOS.UnitTests/Scripts/StackTraceSoftwareExceptionFrame.script
https://github.com/dotnet/runtime/issues/110758
Given the cDAC only supports a small subset of the DAC apis, I have created some pared down tests that are `CDACCompatible`.
Steps to run tests with cDAC:
1. Build diagnostics repo.
2. Build runtime repo.
3. Run `eng\privatebuild.cmd` in the diagnostics repo
4. Copy over relevant files from runtime repo to `.\dotnet-test`. See https://github.com/dotnet/diagnostics/blob/main/documentation/privatebuildtesting.md for example.
Note, with the addition of the cDAC, `cdacreader.dll` and all of the dll's under `cdaclibs` must be copied over as well.
5. Run `eng\testsoscdac.cmd` in the diagnostics repo.
The cDAC can be debugged in these tests by running the tests script with `$env:VSTEST_HOST_DEBUG=1` which waits for a debugger to attach to the test …
> [cDAC] Add support to run SOS tests against the cDAC

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/MetricsPipeline.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Counters/TraceEventExtensions.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/EventCounter/EventCounterTrigger.cs
- src/Microsoft.Diagnostics.Monitoring.EventPipe/Triggers/SystemDiagnosticsMetricsTrigger/SystemDiagnosticsMetricsTrigger.cs
The introduction of static caches for metric data in https://github.com/dotnet/diagnostics/pull/4324 combined with https://github.com/dotnet/diagnostics/pull/5120 causes metrics with the same name but different units across two processes to fail. This was observed in 10.0 when a different bug caused metrics to have no units.
> Fix metrics caching

- src/Microsoft.Diagnostics.NETCore.Client/DiagnosticsServerRouter/DiagnosticsServerRouterFactory.cs
- src/Microsoft.Diagnostics.NETCore.Client/ReversedServer/ReversedDiagnosticsServer.cs
- src/Microsoft.Diagnostics.WebSocketServer/WebSocketServerImpl.cs
- src/Tools/dotnet-dsrouter/Program.cs
- make the default value valid `ws://127.0.0.1:8088/diagnostics`
- fix parsing the URL, so that HTTP server could be started based on `ws://` or `wss://` as it only accepts `http://` or `https://` schema
Contributes to https://github.com/dotnet/runtime/issues/76316
> [dsrouter] fix web socket startup

- eng/Versions.props
- src/Microsoft.Diagnostics.DebugServices.Implementation/Host.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
- src/Microsoft.Diagnostics.DebugServices.Implementation/RuntimeProvider.cs
- src/Microsoft.Diagnostics.DebugServices/IRuntime.cs
- src/Microsoft.Diagnostics.DebugServices/ISettingsService.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/CommandFormatHelpers.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
- src/Microsoft.Diagnostics.TestHelpers/TestHost/TestDataWriter.cs
- src/Microsoft.Diagnostics.TestHelpers/TestHost/TestDump.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.Hosting/DataTargetWrapper.cs
- src/SOS/SOS.Hosting/RuntimeWrapper.cs
- src/SOS/SOS.Hosting/SOS.Hosting.csproj
- src/SOS/Strike/clrma/managedanalysis.cpp
- src/SOS/Strike/platform/runtimeimpl.cpp
- src/SOS/Strike/platform/runtimeimpl.h
- src/SOS/Strike/util.cpp
- src/SOS/inc/runtime.h
- src/Tools/dotnet-dump/Analyzer.cs
- src/shared/inc/clrdata.idl
- src/shared/pal/prebuilt/idl/clrdata_i.cpp
- src/shared/pal/prebuilt/inc/clrdata.h
- src/tests/DbgShim.UnitTests/DbgShimTests.cs
Add --usecdac and --forceusecdac options "runtimes" to control cdac loading.  Currently --usecdac enables using the CDAC for only the CLRMA APIs.  --forceusecdac forces all SOS to use the CDAC for testing.
Move ISettingsService impl's to Host class. Add UseContractReader property.
Add IRuntime.GetCDacFilePath() and add a "bool verifySignature" parameter to IRuntime.GetDacFilePath.
Add DotNetRuntimeContractDescriptor address to !runtimes info. Clean up the formatting a little.
Publish SOS.Hosting package
> Add CDAC support to SOS

- eng/Build.props
- eng/DotNetBuild.props
This allows to eventually remove the DotNetBuild.props file and just use the standard entry point.
> Move DotNetBuild defines into Build.props

- src/SOS/Strike/metadata.cpp
- src/SOS/Strike/strike.cpp
It isn't uncommon to want to examine a .NET signature, but not care about resolving tokens. This change makes providing the associated module optional and emits the token value instead. This change also makes this behavior the failure case in the event the associated `IMetaDataImport` returns a failure code.
View without whitespace diffs - https://github.com/dotnet/diagnostics/pull/5480/files?diff=split&w=1
> Permit the Module address to be optional for sig parsing.

- src/Microsoft.Diagnostics.DebugServices.Implementation/Runtime.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/CommandFormatHelpers.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/RuntimesCommand.cs
- src/Microsoft.Diagnostics.ExtensionCommands/Host/StatusCommand.cs
- src/SOS/SOS.Extensions/HostServices.cs
- src/SOS/SOS.Hosting/RuntimeWrapper.cs
Running `clrstack` a second time after a verify DAC failure succeeds.
Runtime.GetDacFilePath wasn't caching the verifySignature parameter so the DAC wasn't being verified once the dac path was cached.
Verify the DAC path passed to the DBI entry points for the `clrstack -i` path in RuntimeWrapper.CreateCorDebugProcess.
Display the ISettingsService values in both `runtimes` and `sosstatus`.
> Fix DAC verify signature issue

- src/SOS/SOS.UnitTests/SOS.UnitTests.csproj
Remove the cDAC test filter.
With the fallback, the cDAC should pass all the same tests as the DAC.
> Run all SOS tests against cDAC with fallback

- src/shared/pal/src/thread/process.cpp
- This logic always assumed that the lowest address of a mapped file was its "base address", but in the presence of dotnet/runtime#114462 that is no longer correct. We may map stubs at lower addresses.
- Fix by checking the start of the mapped region for the magic value for the start of a MachO binary
> Fix enumerating loaded process modules on Apple platforms

- src/Tools/Common/Commands/Utils.cs
It's stated that none of the `process-id`, `name`, or `diagnostic-port` options should be configured when launching a child process with `dotnet-trace collect ... -- <child process to launch>`, yet the check only errors when all are configured.
Additionally makes the exclusive check on `process-id`, `name`, `diagnosic-port`, and `dsrouter` more readable.
```
SUCCESS
PS C:\Users\mihw\source\repos\mdh1418\diagnostics\latest> .\artifacts\bin\dotnet-trace\Debug\net8.0\dotnet-trace.exe collect -p 1418 --show-child-io  -- dotnet package search json
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="dotnet-trace-26020-20250616_135956.socket,suspend,connect" …
```
> [ProcessLauncher] Fix Child Proc Arg Validation

- src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
Partly addresses https://github.com/dotnet/diagnostics/issues/5501
Child processes started by diagnostic tooling set a `DOTNET_DiagnosticPort` environment variable, specifying only the path.
The runtime [defaults to a connect type port in suspend mode](https://github.com/dotnet/runtime/blob/22ccb0563cbb79e950b8d8e2d8bed306b125e7d8/src/native/eventpipe/ds-ipc.c#L628-L637), which isn't clear from the end user's viewpoint, as [logging will only reveal the DiagnosticPort value](https://github.com/dotnet/runtime/blob/22ccb0563cbb79e950b8d8e2d8bed306b125e7d8/src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h#L390-L412). Instead, we can mitigate confusion by explicitly setting the config from the tooling side.
```
The runtime has been configured to pause during startup and is awaiting a …
```
> [ProcessLauncher] Explicitly set diagnostic port configs

- src/Tools/dotnet-gcdump/DotNetHeapDump/DotNetHeapDumpGraphReader.cs
Pretty much just adjusts what we had for Project N:
* `IsProjectN` is not true for native AOT because we use the same provider GUID as JIT-based CoreCLR and not Project N (which is by design)
* It is still possible to handle both Project N and native AOT the same way where it matters because both Project N and native AOT emit the same flags (`TypeFlags.ModuleBaseAddress` and `ModuleFlags.Native`)
* Looks like Project N GCDump always relied on Windows kernel module load data only. I'm adding a path that can also use our own module load events (Project N also generates those)
Cc @dotnet/ilc-contrib
> Make dotnet-gcdump work with native AOT

- eng/build.sh
Build.sh looked at the exit code of the tee command for the native build. Check the 0th exit code for the native build.
Co-authored-by:  Steve Pfister <steveisok@users.noreply.github.com>
> Update build.sh to error on native build failures

- src/Tools/Common/Commands/Utils.cs
- src/Tools/Common/DsRouterProcessLauncher.cs
- src/Tools/Common/ProcessTerminationHandler.cs
- src/Tools/Common/ReversedServerHelpers/ReversedServerHelpers.cs
- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
- src/Tools/dotnet-dsrouter/dotnet-dsrouter.csproj
- src/Tools/dotnet-trace/CommandLine/Commands/CollectCommand.cs
- src/Tools/dotnet-trace/Program.cs
Changing the cmd line tooling implementation in the following commit:
https://github.com/dotnet/diagnostics/commit/6837b8f319b08a458142605bcac76aff4e5af00a#diff-d33d6d23aba37ebcfc05462b2fa260136a11df1b03f129f1912a856c36a8d7f3
broke Ctrl+C handling in dotnet-trace, since it disabled the process termination handler leading to process termination without
being able to close the session, creating a corrupt file.
dotnet-trace and dotnet-dsrouter tooling needs better control of its Ctrl+C shutdown, so this commit implements a custom process termination handler and disable the default handler implemented by the cmd line tools. This handler makes sure to signal a cancelation token if one of the configured signals hits the process.
This commit also fix an issue with the integrated execution of …
> Improve Ctrl+C support in dotnet-trace tool

- src/SOS/Strike/strike.cpp
Found while investigating a COM double free in the cDAC. Not my issue, but a small issue.
Previously, if a call to `pVal->GetBytes` in `ShowArgs` failed it would return without freeing `pVal`. This makes use of `ToRelease<T>` to manage the COM objects lifetime.
> Fix possible COM leak

- src/Tools/Common/Commands/Utils.cs
- src/Tools/Common/DsRouterProcessLauncher.cs
Context: https://github.com/dotnet/diagnostics/pull/5494
Context: https://github.com/dotnet/diagnostics/pull/5241
Fixes: https://github.com/dotnet/diagnostics/issues/5435
We added `--dsrouter` switch to both `dotnet-trace` and `dotnet-gcdump`, which runs `dotnet-dsrouter` as a child process.
Many of `dotnet-dsrouter`'s console messages are pretty useful for developers, but we are simply ignoring them:
private static async Task ReadAndIgnoreAllStreamAsync(StreamReader streamToIgnore, CancellationToken cancelToken)
{
Memory<char> memory = new char[4096];
while (await streamToIgnore.ReadAsync(memory, cancelToken).ConfigureAwait(false) != 0)
{
}
}
To make this a bit more useful, we now log the output to either `Console.Out` or `Console.Error` where appropriate.
If we simply did:
string line; …
> [dsrouter] log redirected console output

- src/Microsoft.Diagnostics.TestHelpers/RemoteExecutorHelper.cs
When debugging different parts of the test pipeline it is good to see the different pids of launched processes in case there is need to attach debugger to it. For the debuggee we output the pid, but for the debugger executed through remote executor we didn't. This PR adds logging to output pid of started process.
> Log pid of remote executed process.

- src/shared/pal/src/thread/process.cpp
As identified by https://github.com/dotnet/runtime/issues/116545, macOS26 have broken semaphores in case debugger and debuggee have been signed with different team ids, currently only mentioned for iOS/iPadOS, https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-26-release-notes, but testing shows its broken for regular apps as well.
This PR adds support for a different startup handshake protocol for debugger/debuggee using FIFO file (aka named pipes) on Apple platforms due to limitation introduced in macOS26. All other POSIX platforms will continue to use the semaphore based handshake protocol.
The implementation is backward compatible on Apple platforms. Implementation will always setup semaphores to support runtimes using semaphore protocol, but on Apple …
> Fix broken debugger/debuggee startup handshake protocol on macOS26.

- src/Tools/dotnet-dsrouter/ADBTcpRouterFactory.cs
This improves upon d7d85009 by caching the Android SDK path in a `static` field.
I was testing `dsrouter` and noticed it logging duplicate messages:
> dotnet-trace collect --dsrouter android
For finer control over the dotnet-dsrouter options, run it separately and connect to it using -p
WARNING: dotnet-dsrouter is a development tool not intended for production environments.
How to connect current dotnet-dsrouter pid=45036 with android device and diagnostics tooling.
Start an application on android device with ONE of the following environment variables set:
[Default Tracing]
DOTNET_DiagnosticPorts=127.0.0.1:9000,nosuspend,connect
[Startup Tracing]
DOTNET_DiagnosticPorts=127.0.0.1:9000,suspend,connect
Run diagnotic tool connecting application on android device through dotnet-dsrouter …
> [dsrouter] cache Android SDK path

- src/Tools/Common/DsRouterProcessLauncher.cs
- src/Tools/dotnet-dsrouter/DiagnosticsServerRouterCommands.cs
- src/Tools/dotnet-dsrouter/Program.cs
- src/Tools/dotnet-dsrouter/dotnet-dsrouter.csproj
`dotnet-trace collect --dsrouter android` logs an unnecessary message currently:
Run diagnotic tool connecting application on android device through dotnet-dsrouter pid=38004:
dotnet-trace collect -p 38004
`dotnet-trace` is launching and controlling `dotnet-dsrouter`, and so you would not need to run `dotnet-trace collect -p 38004`.
To solve this:
* Pass `--parentprocess pid:name` when launching `dotnet-dsrouter` from `dotnet-trace`
* `dotnet-dsrouter` checks `--parentprocess` switch to tell if it is running as a subprocess
* Only log this message when *not* a subprocess
> [dsrouter] improve log message when launched as a subprocess

- src/sos-packaging.props
When packaging, exclude the bin related sos binaries because they will come along in the published assets. Failure to do this will cause a warning as error and the official build will fail.
> Fix official build packaging

- src/SOS/extensions/hostcoreclr.cpp
The generic UNIX code in this function seem 100% appropriate for FreeBSD too. Not sure why this was ifdef'ed.
@Thefrank @sec You might want to look on this.
> Remove a seemingly bogus ifdef HOST_FREEBSD block

- src/Microsoft.Diagnostics.Monitoring.EventPipe/Logs/TraceEventExtensions.cs
Fixes #5557
**Description:**
This PR fixes a bug in `TraceEventExtensions.GetLogMessageJsonEventData` where `ActivityTraceId`, `ActivitySpanId`, and `ActivityTraceFlags` were never read because the method gated on `traceEvent.Version >= 2`.
Since `Microsoft-Extensions-Logging.LoggingEventSource` uses TraceLogging (`EtwSelfDescribingEventFormat`), the ETW event header always reports `Version=0`. As a result, the correlation fields introduced in .NET 9 were silently ignored.
**Changes:**
- Replace `traceEvent.Version >= 2` check with a payload name lookup for `"ActivityTraceId"`, `"ActivitySpanId"`, and `"ActivityTraceFlags"`.
- This ensures:
- On runtimes where the fields don’t exist (<= .NET 8): values remain `null`.
- On .NET 9+: fields are parsed correctly.
**Result**:
Out-of-process …
> Fix correlation field parsing for Microsoft-Extensions-Logging TraceLogging events

- src/Microsoft.SymbolStore/KeyGenerators/ELFCoreKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/ELFFileKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachCoreKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachOFatHeaderKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MachOKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/MinidumpKeyGenerator.cs
- src/Microsoft.SymbolStore/KeyGenerators/PEFileKeyGenerator.cs
- src/Tools/dotnet-symbol/Program.cs
Fixes https://github.com/dotnet/diagnostics/issues/5556
> [dotnet-symbol] Add lookup symbolstorekey generation diagnostics

- src/SOS/SOS.UnitTests/Scripts/StackTraceSoftwareExceptionFrame.script
Runtime frames changed and this ICF is no longer present at execution point.
runtime-diagnostics on head of runtime with fix: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1163752&view=results
https://github.com/dotnet/runtime/pull/119863
runtime-diagnostics on head of diagnostics before runtime change above: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1163755&view=results
> Remove check from SOS test

- src/SOS/SOS.UnitTests/Debuggees/FindRootsOlderGeneration/Program.cs
- src/SOS/SOS.UnitTests/Scripts/FindRootsOlderGeneration.script
This test is still being flaky due to server GC attempting to collect the gen2 heap. I modified the test to force the entire LOH array to be alive which should prevent the GC from doing a gen2 collection.
Distinct invocations of `runtime-diagnostics` to test flakiness:
* https://dev.azure.com/dnceng-public/public/_build/results?buildId=1164893
* https://dev.azure.com/dnceng-public/public/_build/results?buildId=1164894
* https://dev.azure.com/dnceng-public/public/_build/results?buildId=1164895
> FindRootsOlderGeneration refactor
